### ISSUE TITLE
Assign dark blue to "pumped storage"

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap#1006]
It's hard to distinguish hydro generation from pumped storage generation, since they use the same "blue" and are placed next to each other. 
There is a thin line between them, but a slightly darker blue (like the blue of the "frontend" label) would be really nice to emphasize these peaks :)

![image](https://user-images.githubusercontent.com/25743609/34947198-b6f53798-fa09-11e7-9527-25185aeb8f43.png)

**Comment by corradio** [comment]
Good idea!
Relevant code is here in case someone wants to play with this:
https://github.com/tmrowco/electricitymap/blob/master/web/app/main.js#L330

**Comment by systemcatch** [comment]
@alixunderplatz this is using the colour for the frontend label, thoughts?
![hydro_storage](https://user-images.githubusercontent.com/30196510/35194935-c2af0330-feb3-11e7-81ad-1cd1720c1124.png)

**Comment by alixunderplatz** [comment]
@systemcatch looks intense! I think it's good! hope it will also be okay with some biomass next to it in the diagram below.

**Comment by alixunderplatz** [comment]
Looks good, so I'll close this :)

![image](https://user-images.githubusercontent.com/25743609/35282831-d42bca18-0056-11e8-8f68-beabd6e6274e.png)

![image](https://user-images.githubusercontent.com/25743609/35282903-145d4dbe-0057-11e8-85fb-43383018a2c2.png)

![image](https://user-images.githubusercontent.com/25743609/35283010-4ed7550c-0057-11e8-8e90-b96d9ac1dfa9.png)
