### ISSUE TITLE
provide  fallback for browsers without webgl

### ISSUE THREAD

**Issue by maep--** [tmrowco/electricitymap#1012]
Not all browsers have webgl enabled or even have a choice (company security policy). There whould be a fallback mode.

**Comment by corradio** [comment]
Hi @maep--,

There is a fallback mode (it hides the map and only shows the menu).
Did you have something else in mind?

Olivier

**Comment by maep--** [comment]
Well, last time I visited I was able to view the map. Now the page is empty and I see "Error: WebGL: Failed to create WebGL context" errors in the console which I assume is the cause.

**Comment by corradio** [comment]
Can you help me reproduce the issue? Normally, we should be able to handle those cases and display at least the left menu.
It's unfortunately going to be hard to code and maintain two versions of the map system..

**Comment by maep--** [comment]
Oh, I can see the left menu "Ranking" but not the map on the right. Sorry that I can't give you more right now but I'm at work and already spent more time on this than I should have :D

**Comment by corradio** [comment]
Fallback UI is already implemented.  The map however has no fallback for non webgl users.

**Comment by maep--** [comment]
FYI, this similar map works well even without Webgl: https://airvisual.com/earth
