### ISSUE TITLE
Scale does not adjust to negative values with hydro storage capacity

### ISSUE THREAD

**Issue by brunolajoie** [tmrowco/electricitymap#1021]
Although it does for the exports
![image](https://user-images.githubusercontent.com/22095643/35276519-f137822c-0043-11e8-8788-06fda5a501f8.png)

**Comment by alixunderplatz** [comment]
@brunolajoie I have a question related to pumped storage: does the pumped storage scale actually cover a case, where generation and consumption happen at the same time? Or is it a sum of both? This may for example happen for grid stability reasons / supplying secondary power / etc.
The generated power must be **entirely** assigned to the electricity mix, else it will be distorted more or less.
Showing the negative value is for info-purposes is fine, but subtracting consumption from generation is not, as this seems to be the case now.

This is an excerpt from the German generation and consumption from yesterday:
![image](https://user-images.githubusercontent.com/25743609/35439708-29d3237a-029c-11e8-883e-331bbd98bc35.png)

This is from Portugal:
![image](https://user-images.githubusercontent.com/25743609/35439756-75ada46e-029c-11e8-9c23-3a48597e9998.png)

**Comment by corradio** [comment]
Additional insights into the bug.
![image](https://user-images.githubusercontent.com/1655848/35446042-cb653630-02b3-11e8-8ae0-b8e29a6e2d1d.png)
In this example storage capacities are missing, even though they are defined in the capacity object:
![image](https://user-images.githubusercontent.com/1655848/35446117-07d6502c-02b4-11e8-82ee-72b2c6e68ca6.png)
This is a backend issue.

**Comment by brunolajoie** [comment]
Issue fixed in latest deploy
