### ISSUE TITLE
MISO <-> Canada interconnector

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#1031]
..needs to be updated as it still pointing to Montana instead of MISO
![image](https://user-images.githubusercontent.com/1655848/35481513-36ff7488-0425-11e8-91f4-b487c037240a.png)

**Comment by systemcatch** [comment]
There's 2 exchanges from MISO to Ontario, Montana & and Michigan. Since both are part of the same region now we should probably simplify to one. I'm assuming we can't have 2 exchanges with the same name.

**Comment by corradio** [comment]
OK for merging both into a single arrow. You're right that we can't have
two with the same name.
