### ISSUE TITLE
Newly discovered data sources for electrical grids in India

### ISSUE THREAD

**Issue by anirudh-ramesh** [tmrowco/electricitymap#1037]
1. [State Load Dispatch Centre of Gujarat (GJ)](http://www.sldcguj.com/RealTimeData/RealTimeDemand.php) - the power plants indicated on the dashboard have a corresponding description in the following file (CSV):
[gujarat.txt](https://github.com/tmrowco/electricitymap/files/1672514/gujarat.txt)
2. [State Load Dispatch Centre of Uttar Pradesh (UP)](http://www.upsldc.org/real-time-data) - this doesn't have a scrapable webpage, but the data could possibly be retrieved through an API.
3. [Western Regional Load Dispatch Centre](http://www.wrldc.in/onlinestate.aspx) - doesn't provide a breakdown of plants, so this can't be used to determine carbon emissions, but it provides a breakdown of states within the region, so the fuels for the generation can currently be marked as "unknown".

**Comment by corradio** [comment]
@anirudh-ramesh can you merge this with https://github.com/tmrowco/electricitymap/issues/304 ?

**Comment by anirudh-ramesh** [comment]
Duplicate of #304
