### ISSUE TITLE
Add Aruba

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#1038]
https://en.wikipedia.org/wiki/Aruba
Data: https://www.webaruba.com/renewable-energy-dashboard/aruba
Seen here: https://www.reddit.com/r/energy/comments/7dj5sc/electricitymap_has_new_features_carbon_intensity/dtcjw8a/?context=3
Installed capacity: https://www.webaruba.com/energy-production/power-production-figures

**Comment by systemcatch** [comment]
Nice! I think Aruba is currently being removed from the map in the conversion/simplification to topjson https://github.com/tmrowco/electricitymap/blob/master/web/topogen.sh#L67

**Comment by alixunderplatz** [comment]
"Fossil fuels" value can be mapped to the "oil" category.

See: https://www.nrel.gov/docs/fy15osti/62709.pdf

In this report by NREL it says that 84% of electricity generation were from heavy fuel oil. I assume this won't have changed. Report is from March 2015.

![image](https://user-images.githubusercontent.com/25743609/35945295-03d5ccb8-0c60-11e8-98f8-536730b41bfe.png)

**Comment by pascalheraud** [comment]
I'll start working on it

**Comment by alixunderplatz** [comment]
Let's keep in mind that a biogas category is "coming soon" on WEBaruba's front page! 👍 👍 👍 
https://www.webaruba.com/

![image](https://user-images.githubusercontent.com/25743609/36092937-66ab52c2-0fe9-11e8-8263-2a69123e4181.png)
