### ISSUE TITLE
Emissions per capita?

### ISSUE THREAD

**Issue by qwjhvbxi** [tmrowco/electricitymap#1039]
I think it would be interesting to add the option of displaying carbon intensity per capita in the map view, that is, adding the variable of how much electricity is consumed per person. This is also an important factor connected with energy efficiency. 
(I am not sure if this is the right place to suggest this, and I am sorry if it's not)

**Comment by corradio** [comment]
Hi @qwjhvbxi,
Indeed this is the right place to suggest this.
This issue was already responded to here: https://github.com/tmrowco/electricitymap/issues/169#issuecomment-269651836
However I'll keep in opened so we can add it in the FAQ.

**Comment by thomasgibon** [comment]
Hi, to complement and exemplify what @corradio answered in #169, I think it is indeed methodologically questionable to show per-capita numbers without using a consumption-based approach. In short, Chinese citizens are not responsible for the emissions associated with all the products that China exports, but only for what they consume. What is called "consumption-based accounting" (CBA) is actually a very important aspect of climate policy.

If you are interested in the topic (I personally think it's fascinating), @qwjhvbxi, there is a great deal of literature discussing exactly that: the responsibility of the consumer vis-à-vis GHG emissions in a global economy. I can suggest:
- great paper showing the difference between production- and consumption-based accounting http://www.pnas.org/content/107/12/5687 (see Figure 2, which illustrates my example),
- the case for and against CBA: onlinelibrary.wiley.com/doi/10.1002/wcc.438/full (main criticism is that mitigation measures are hard to implement, given enough political will, it's easier to close a coal power plant than to tell millions to consume less),
- and this visualization of environmental footprints of countries: https://www.environmentalfootprints.org/infographics

To take the Chinese example again from that visualization...

_Total GHG emissions of electricity production in China:_
![image](https://user-images.githubusercontent.com/23332955/35634994-606b929a-06ad-11e8-88e2-f8ab85a49e61.png)

_Total GHG emissions of electricity **consumption** in China (direct and embodied in consumption products):_
![image](https://user-images.githubusercontent.com/23332955/35634903-2254fbb8-06ad-11e8-9e2e-08ea531907b7.png)

(note the y-axis difference) The ratio is huge for China, produced emissions for electricity in the territory are about 6 to 7 times that of electricity needed for Chinese final consumption. Sorry for the long post, I thought it would be useful to show that it's a more complex issue than it seems :)

**Comment by corradio** [comment]
@thomasgibon this is amazing! Do you think you could help in updating our per capita map in https://tmrow.com/climatechange.html ? Would love to have latest GHG/cap [consumption] per country.

**Comment by thomasgibon** [comment]
@corradio Yes, definitely! For a start, I could output data from the public multiregional input-output (MRIO) database [EXIOBASE2](http://www.exiobase.eu/index.php/data-download/exiobase2-year-2007-full-data-set), which is publicly available. It's 2007 data. EXIOBASE3 should be out soon, with more up-to-date data [the paper is out](http://onlinelibrary.wiley.com.proxy.bnl.lu/doi/10.1111/jiec.12715/abstract) (paging @konstantinstadler here). What is nice with MRIO is that you can do it by sector. Other databases exist, but I'm less familiar.

I can probably do that in the next few days.

**Comment by corradio** [comment]
Great. Let's use https://github.com/tmrowco/tmrow.com/issues/35 to discuss about that.
