### ISSUE TITLE
Dash lines to mark US states within RTOs

### ISSUE THREAD

**Issue by Hyric89** [tmrowco/electricitymap#1046]
A question for the US territories: could states within the RTOs be outlined with dash lines? This would make it easier to tell which state is located where within the RTO block. This is all aesthetics as placing the mouse of the state of Iowa versus the state of Minnesota will still display MISO as a whole regardless.

I will put forward two reasons to argue in favor of such a modification:

-When toggling the wind and/or solar potential function, it is difficult to distinguish which states are getting more wind and/or solar irradiance than others. Adding dash lines to mark state borders within RTOs would make it clear where the states' borders are within the RTO

-It could act as a (temporary) substitute for having specific, clear data of electricity generation and transport within specific state borders and at this moment, that doesn't seem to be available. The next best thing would be to simply add data for RTOs and the [unfettered boundaries](https://www.wapa.gov/newsroom/NewsFeatures/PublishingImages/ISO-RTOmap_slider.jpg) they come with. It would allow Electricitymap's representation of RTOs in the USA to be more accurate geographically while making it clear which states or which pieces of states the RTOs cover and which they do not. FOr example, it would make clear which parts of Texas are covered by SPP, MISO and ERCOT.

I would like to hear your thoughts.

**Comment by systemcatch** [comment]
I like the idea of having state lines show when the RTO area is hovered over. Personally I don't think we will get generation by state anytime soon, see #899 .

**Comment by systemcatch** [comment]
@Hyric89 what do you think of this?

![states](https://user-images.githubusercontent.com/30196510/35743839-a94b7dec-0836-11e8-9245-3f6cabe2c680.png)

**Comment by Hyric89** [comment]
Yes, it's much more clear! Now I don't have to guess where the state borders are. It's also very pleasant on the eyes.
