### ISSUE TITLE
CAISO capacity

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap#1047]
Hi, folks!

Is there any reason the installed capacity is missing for CAISO? Maybe I had missed something, but I couldn't find any related info here.
Is it because only 80% of the State of California is actually covered by CAISO?

Anyways, here we have some fresh numbers from CAISO for their **renewables capacity:**
http://www.caiso.com/informed/Pages/CleanGrid/default.aspx

As of 4th January 2018:

![image](https://user-images.githubusercontent.com/25743609/35539460-ee26ec36-0551-11e8-8a78-ea53c440ad4b.png)

Small hydro must be added to large hydro, but I couldn't find the numbers for large.

I could only find something for the entire State of California, but these will not be applicable, right?
http://www.energy.ca.gov/renewables/tracking_progress/documents/installed_capacity.pdf

However, I am sure that the only nuclear power plant (Diabolo Canyon) is within CAISO, so we could set its capacity to nuclear (gross or net?).

This is what I consider to be "valid" for CAISO at the moment:

```
"capacity": {
      "battery": 136,
      "biomass": 997,
      "geothermal": 1799,
      "solar": 11172,
      "wind": 6269
    },
```

**Comment by corradio** [comment]
What we can do is at least add the "valid" values that you found?

**Comment by systemcatch** [comment]
I had a look around but couldn't find anything more for other capacities. Suggest we close this unless there's anything else to say/do
