### ISSUE TITLE
Canary islands

### ISSUE THREAD

**Issue by strassburger** [tmrowco/electricitymap#1049]

**Comment by strassburger** [comment]
Not very importand, but the locals see it different.
The names of the Country -Spain- and the islands are not translated in different languages.
Checked it in english, german and spanish
Country: allways Spain
The names of the Islands are allways in english also.
One  special: The locals want to see "El Hierro" and not Hierro only. They are absolutely right.
Like La Palma that is absolutly correct.
Sorry, i did not recognize earlier. My fault.
Refernce to #1028

**Comment by systemcatch** [comment]
Hey @strassburger do you want provide a list of what the Islands should be named. Alternatively the translations are done in https://github.com/tmrowco/electricitymap/tree/master/web/locales which you can update.

**Comment by strassburger** [comment]
Hey @systemcatch,
Take the first option, Do not think it is a really local problem.

Did look around:
There is different handling of translating the names.
The official touristic web side does not translate the island names at all.
They keep the Island names in spanish.
Only the Island group "Canary Islands" are translated in the different languages.
But the Island group "Canary Island" is not used any more in EM.
Source:
https://www.hellocanaryislands.com/
Think that is the most convenient way to handle the island names.

So only two points are left:
- change "Hierro" in "El Hierro" that really was my fault.
- Translate "Spain" in the correct language, what is done with the country Spain in the country and the Baleares section of EM.

**Comment by systemcatch** [comment]
Ok so in https://github.com/tmrowco/electricitymap/blob/master/web/locales/en.json (English translation) only Hierro needs to be changed to El Hierro, Spain will remain as Spain as that is the correct English translation.

We should update https://github.com/tmrowco/electricitymap/blob/master/web/locales/es.json (Spanish translation) to reflect the new split by islands.

**Comment by strassburger** [comment]
@systemcatch 
both done. Thanks for the help and the trust.

**Comment by strassburger** [comment]
hope got it now,
thanks again

**Comment by corradio** [comment]
Thanks for taking over here guys! I'll push to production asap.
