### ISSUE TITLE
UI update when importing from a missing country

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#1051]
Currently, when importing from a missing country, the mix of the importer is shown instead of "?".

Raised by @strassburger

**Comment by strassburger** [comment]
Think similar Problem: Mistake in Ranking
Idea: make a plausibility test  before publishing.
Sometimes ree.es did not send all data complete.
It was corrected by ree.es10 minutes later.
Unfortunaly i was to late to catch the ree.es source with the missing data.
In this case i could catch the data of oil was missing for El Hierro and Fuerteventura/Lanzarote.
The statistic says 100% REE but REE was ca 10% of all production.
This could be an indicator for incomplete data.
The screen shots of the situation:
![mistake-in ranking- 2018-02-13 14 46 14](https://user-images.githubusercontent.com/28303688/36156635-95f164e0-10cf-11e8-8a03-7b70c915229c.png)
![hiero-01-2018-02-13 14 44 54](https://user-images.githubusercontent.com/28303688/36156674-ad47b338-10cf-11e8-9966-03105439aea0.png)
![hierro_02-2018-02-13 14 43 42](https://user-images.githubusercontent.com/28303688/36156684-b232ceb4-10cf-11e8-92b0-0871ae08e9a5.png)
![fuerteventura-01-2018-02-13 14 48 08](https://user-images.githubusercontent.com/28303688/36156706-c34f72b0-10cf-11e8-86e6-6846c0e650c0.png)
![fuerteventura-02- 2018-02-13 14 47 22](https://user-images.githubusercontent.com/28303688/36156710-c6a74780-10cf-11e8-8ed6-a7f0bed44734.png)
Hope helps

**Comment by corradio** [comment]
@strassburger this is a different issue.
You can look here:
https://github.com/tmrowco/electricitymap/blob/master/parsers/lib/quality.py
for the data validation code.
We should probably force oil to be present / non-zero

**Comment by strassburger** [comment]
@corradio,
think that we can not do.
Till Monday El Hierro had a oil value of 0 for 18 days. That was / is correct if the diesels are not working.
That happens regular en El Hierro.
Did study your hint to the data validation code. As far i understand there is not a quick way.
Sprry,i am not able to form it in python right away.
Also not in math way.
Try to give my idea here:
If  demand is higher than generation there have to be a problem in data.
But i am afraid that EM do not read demand from source. 
I wrote:
 "The statistic says 100% REE but REE was ca 10% of all production."
To say it better: 
The statistic did not have the information of the demand. I had the information just in mind.
The good side is that ten minutes later all was solved by the correction of the source data of REE.
But i think we should really solve the problem. That permanent wrong rank of New Brunswik really made a dubious impression. The sudden jumping in wrong ranking do not really produce impression of reliability.

**Comment by corradio** [comment]
Yeah we would need to update the parser in order to compare demand with generation. Maybe there's a *minimum* generation we should expect, and if it's under, then we ignore the data?

We'll try to fix the NB error soon, but we're a bit out of manpower.

**Comment by strassburger** [comment]
I am not sure with the minimum generation, but may work if we compare overall generation of the last data value with the new value. If we take less then 50% there is a mistake of data OR a partly / complete breakdown.
Sorry i can not really help in the case of manpower. Will have to update this year my system from 32 to 64bit. That really takes time. Till May i only have my laptop and do not want to mess it up. If that is done i can install a test system and may help a little.

**Comment by corradio** [comment]
ok!

**Comment by corradio** [comment]
Closing this issue as I don't think it makes sense anymore now that countries can have default export mixes.
