### ISSUE TITLE
Incomplete highlight on some zones

### ISSUE THREAD

**Issue by systemcatch** [tmrowco/electricitymap#1058]
Observed on Firefox 57 and Chromium 63;

When I hover the mouse on MISO (and sometimes Ontario) it doesn't always highlight the full area. It seems to occur more often when zoomed in, I haven't seen it happen on the first 3 zoom levels yet.

![miso_hover](https://user-images.githubusercontent.com/30196510/35693482-3e9f4e76-0776-11e8-8ce8-8ea7b8c92e7c.png)

**Comment by alixunderplatz** [comment]
Have observed the same issue with other regions and countries, just like described. Happens for quite many regions starting from a certain zoomstage and depending on which side the cursor is coming from.

**Comment by corradio** [comment]
Yeah it seems to be related to the mapbox-gl map implementation.. No clear clue on how to fix yet.

**Comment by jarek** [comment]
The highlight boxes seem to be rectangles, and depend on where the hover area was entered.

It's particularly visible on Jan Mayen fairly reliably highlighting only a bit of Norway:

![screenshot - 050218 - 19 26 36](https://user-images.githubusercontent.com/47415/35821874-c5c1a73c-0aaa-11e8-933e-157fef1e713d.png)

Maybe there's just a default highlight area somewhere that's too small for our purposes?

**Comment by corradio** [comment]
The way it works right now is that a new white geometry is draw with a
certain opacity. The geometry is the proper one, so it must be a rendering
issue.
Maybe we should open an issue on mapbox-gl to check if it's on their side.
