### ISSUE TITLE
Add Macedonia MK (retrospective data)

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap#1059]
Digging around on ENTSO-E, I found out the data for FYR Macedonia is added with a delay. 
It is including generation from coal, hydro and wind.

![image](https://user-images.githubusercontent.com/25743609/35695716-a814979e-0785-11e8-9246-74f93b5d7305.png)

The data set for the hours of the previous day is published at least more than half a day later for the entire previous day (so D-1). While I was checking it this noon (around 12:00), only data for the 30th Jan was there, now (19:00 CET) even data for 31st Jan is displayed. So this will rather be something for the database.

Here is the site of the TSO with the data in a PDF file for D-2, but the seperation of the types from my understanding is worse (thermal, hydro, renewable).
http://www.mepso.com.mk/ListanjeIzveshtai.aspx?categoryID=113#

And finally, to include even biogas and solar, there is the site of the market operator:
https://opee.mepso.com.mk/Public/pocetna
I had a warning from my browser opening the site, but it's fine.

![image](https://user-images.githubusercontent.com/25743609/35695785-d67c7de0-0785-11e8-8740-6992891e513a.png)

Select the boxes above the second diagram and you can explore the different categories MHEC (small hydro), VEC (wind),  BIOGAS, PV. Only the last 2 will be relevant because they are not yet disclosed on ENTSO-E.
The forecast for the recent day is available for each category, and actual generation again only for the previous day (D-1).

**Comment by corradio** [comment]
Seems like the ENTSOE id is `10YMK-MEPSO----8`. Feel free to add it to the ENTSOE parser so we can start collecting data and see how it looks!

**Comment by alixunderplatz** [comment]
Looks like it is in the parser already. 🤔 If there is no live-data on entso-e in general, how many hours does the parser go back in time to collect it, if it is there?

**Comment by corradio** [comment]
It goes 24 h in the past. I've added the MK parsers to zones.json. Let's
see!

[image: Inline image 1]

**Comment by systemcatch** [comment]
Have we managed to collect any data so far?

**Comment by corradio** [comment]
Since I updated the parser to get values from the last two days, we're
getting wind, coal and hydro values.
Unfortunately we only display last 24 hrs on the map

**Comment by systemcatch** [comment]
Excellent, still a significant improvement.

**Comment by corradio** [comment]
@systemcatch @alixunderplatz should we close this if we already collect data?

**Comment by alixunderplatz** [comment]
@corradio @systemcatch we could close. 

Unfortunately the data reporting on ENTSO-E has been irregular/totally lost in the last weeks.

Historical and yesterday's "Biogas" and "PV" (and optionally wind) could be collected from that one link above, but that's <20 MW.
But at least it is reported there constantly compared to hydro, lignite and wind on ENTSO-E.
