### ISSUE TITLE
Add Albania AL (retrospective/scheduled data)

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap#1062]
Hey everyone! Very good news for another country! 😃 

Albanian electricity generation is based on ~100% hydro power. This allows us to take total generation data from the national TSO "OST" for the map, as long as it is still not reported to ENTSO-E.

There are 3 possibles sources for the data:

1.) Each day (with a delay of ~2 days) a PDF-file with a data chart is published, which contains hourly generation and load data. This will be something **for the database** (with a better precision than 2.) and 3.)).

https://www.ost.al/index.php/en/consume-generation-year-2018/
![image](https://user-images.githubusercontent.com/25743609/35770495-5fec98ca-091c-11e8-973c-a2e5cc022d94.png)

2.) **For the live-map**, we can actually take the day-ahead scheduled generation. It's not yet available for tomorrow (20:00 CET), but I'll keep watching it.
https://www.ost.al/Data%20Flow.html
https://www.ost.al/index.php/sq/scheduled-generation-day-ahead/

There is a data chart with hourly scheduled generation.
![image](https://user-images.githubusercontent.com/25743609/35770529-3b74861e-091d-11e8-8852-d291d7174198.png)

3.) Surprisingly, I found data on ENTSO-E for day ahead scheduled generation (already available for tomorrow as opposed to 2.) ) which is also a possible thing **for the live-map** and probably the best solution.
https://transparency.entsoe.eu/generation/r2/dayAheadAggregatedGeneration/show

I made a quick chart in Excel to compare scheduled generation of 2.) and 3.) vs. actual generation of 1.): the result is pretty good! 

![image](https://user-images.githubusercontent.com/25743609/35770655-82c8c000-091f-11e8-8d68-e2eb02f05bdf.png)

There are hydro plants only, so there won't be many unforeseen outages like for more complex fossil plants. So I'd say using scheduled data is absolutely not a problem here!
The installed hydro capacity is something between 1700 and 1800 MW, I'll try and look for more capacity data. On ENTSO-E it says 1492 MW, which is a bit too low and not containing smaller hydro.

**Comment by brunolajoie** [comment]
Hey alex! great detective job again!! 🔍 

First thing: We populate the historical DB from the same parser than we populate the live map, so the pdf is cool but we can't use it for now :( What we do however from time to time is to re-run the parsers in later on with past datetimes as input when the TSO's API allows it, in order to get better (corrected) data compared to the live one. Here, we'll have to deal with day-ahead data only.

Second thing: So far, we had always refrained ourself from mixing  forecasted data (Albania) with real-time data (its neighbours for instance) because it could end up creating strange results in case of unplanned event...I'm thinkning, especially, will it problematic for training forecasts models? But given that Albania it's a special case with only hydro, I tempted to give it a try. You agree @corradio ?

**Comment by corradio** [comment]
Unfortunately this is against the philosophy of the map: we always want to show measured data (not scheduled). Allowing to use scheduled data or models will reduce our credibility.

**Comment by alixunderplatz** [comment]
@brunolajoie @corradio 

I had not yet contacted the TSO. They have a decent English version of the site, too, so language won't be an issue, I hope. 
info@ost.al is their contact adress.

Yeah, I can totally understand that a day ahead forecast is against the "live" philosophy of the map. I had not checked if any of the forecasted day ahead schedules is being updated up to the next hours, so it becomes a "few hours ahead final schedule". I will check this out!

On the other hand, it would add another green spot (at least at the moment) to an area that is mainly coal powered and could also draw attention to a state and an area as a whole with a high remaining potential for renewables/hydro (bunch of more hydro is being developed / is under construction). 

Stumbling across the fact that Albania is generating entirely from hydro (although they have huge oil reserves!) made me very optimistic we could try using the scheduled values.
Their largest dam has 600 MW and four seperate units with 150 MW. The other hydro plants also have many smaller units in the 100-MW range or smaller. So outages will only really "hurt" when the transmission grid is involved. 
https://de.wikipedia.org/wiki/Liste_der_gr%C3%B6%C3%9Ften_Wasserkraftwerke_Albaniens

In summer 2017 generation dropped below 200 MW due to low water levels in their reservoirs. That does affect all hydro generation in that geographical area. The forecasts will include this info, as it is based on near time weather and water levels. Imports will be dominant in Albania in that period.

Maybe live generation data for Albania will be reported to ENTSO-E very soon? We could ask them, too. At least, generation forecasts are there, which is a good sign. There seems to be no seperate market place yet from where we could receive further info.

One thing that I could do to check the applicability is comparing the forecasted generation and the actual generation for a longer period. I am very curious about the outcome of this.

**Comment by brunolajoie** [comment]
Hello @Dalius-ENTSO-E! 
May I ask you what is ENTSOE's status related to real-time generation data for Albania? Are you sourcing your data from [OST](https://www.ost.al) ? Thanks a lot!

**Comment by Dalius-ENTSO-E** [comment]
Hi,
OST is starting slowly to report more and more data. OST should start also reporting of actual generation per generation type. I contacted them to clarify when this happy day can be expected.
Yes, regarding load and generation data for AL,  the source is OST.

**Comment by brunolajoie** [comment]
Awesome!
Best for us is to wait a bit then!

**Comment by corradio** [comment]
I've added AL to our map, so as soon as we'll have data from ENTSOE it will appear on the map
