### ISSUE TITLE
a possible mistake in Energy Map

### ISSUE THREAD

**Issue by alsarago** [tmrowco/electricitymap#1070]
Hi, great idea your Energy Map, I hope you'll soon add new countries: to know about China power generation would be particularly interesting. 
But I think there is an error in the California daily power graph shown in the map: the maximum power is shown around  20 GW, but I think it should be at least twice than that. 

I hope it helped you to improve the service, best regards, 
Alex

**Comment by ThierryOllivero** [comment]
Hi Alex,

Data for California is coming from http://www.caiso.com

You can look at it. The current demand is 22 GW, the current production is 18 GW + 4 GW of imports.

The total generation capacity is currently not shown for California. If you have data to help us on that, don't hesitate to share.

Best regards,

T.
