### ISSUE TITLE
Wind and Solar generation data for Belgium is incomplete/missing

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap#1075]
On Slack we have discussed that **data for Belgium** was **incomplete for generation from wind and solar**.

Recently, the live-values for solar are 0 MW, although Belgium [has 3.8 GW of solar installed](https://solarmagazine.nl/nieuws-zonne-energie/i15369/belgie-wallonie-plaatst-33-megawattpiek-en-brussel-5-megawattpiek-in-2017) and it's a sunny day.
On the websites of ENTSO-E as well as Elia, only measured data for the previous day is given. Only a "most recent forecast" and a "day ahead forecast" are available as live data for the recent day. 😢 

See the graphs: http://www.elia.be/en/grid-data/power-generation/Solar-power-generation-data/Graph
and the map: http://www.elia.be/en/grid-data/power-generation/Solar-power-generation-data/Map

![image](https://user-images.githubusercontent.com/25743609/35913689-e2fc6218-0c00-11e8-8242-ff12aef59dbe.png)

For generation from wind, the live data reported to ENTSO-E seems to be too low/incomplete.
Comparing the measured live data on Elia's website, you will see the difference to what is shown on the electricitymap/reported to ENTSO-E. 
http://www.elia.be/en/grid-data/power-generation/wind-power
![image](https://user-images.githubusercontent.com/25743609/35913872-78fde958-0c01-11e8-9455-fd53ff188671.png)

I suspect that only data for Elia-connected wind farms (some onshore and entire offshore) is reported to ENTSO-E. So only everything that is directly connected to the TSO's 220/380 kV-system.
To track this, Select "Elia-connected" in "filter 2". These values are in good coincidence with the range of what is on the map and ENTSO-E, if you calculate the average for an hour. 
So I am pretty sure all the onshore-wind farms that are connected to the distribution system (DSO) are not being reported to ENTSO-E. 
11 MW onshore was the latest value on entso-e, while the DSO onshore wind farms had something > 50 MW.

**DSO onshore:**
![image](https://user-images.githubusercontent.com/25743609/35914380-5e0e66c0-0c03-11e8-9048-c83a3c146b59.png)

**TSO onshore:**
![image](https://user-images.githubusercontent.com/25743609/35914472-aa4c85f8-0c03-11e8-83c5-50fe340eb795.png)

**ENTSOE:**
![image](https://user-images.githubusercontent.com/25743609/35914304-179ab5b8-0c03-11e8-88e9-7118af9a4d15.png)

**Comment by alixunderplatz** [comment]
Very good news!: Looks like **solar data** for Belgium is there / is back!!! 🌞 

![image](https://user-images.githubusercontent.com/25743609/36785082-f76908aa-1c81-11e8-968a-69f81027458c.png)

**Comment by alixunderplatz** [comment]
Complete wind data is there now, so this data issue was fixed entirely :)

Let's keep this in mind: Granularity for wind & solar data on Elia's website is 15 min, as compared to 60 min on ENTSO-E.

In these screenshots you can see that data is in the same range now.

![image](https://user-images.githubusercontent.com/25743609/37144765-5370d522-22bf-11e8-9a51-6cab84cead81.png)


![image](https://user-images.githubusercontent.com/25743609/37144834-83fa090c-22bf-11e8-9bc7-7a15f890c65e.png)

**Comment by brunolajoie** [comment]
Nice!
