### ISSUE TITLE
Missing some french translation

### ISSUE THREAD

**Issue by pascalheraud** [tmrowco/electricitymap#1077]
A lot of translations are missing in French.

**Comment by brunolajoie** [comment]
Which one please? Thanks!

**Comment by pascalheraud** [comment]
@brunolajoie translations of country names and labels

**Comment by pascalheraud** [comment]
A question about country name translation : sometime, name in english and french is the same one. Do we put it anyway into the french file or not ?

**Comment by corradio** [comment]
Yep! It's better to be sure.
