### ISSUE TITLE
IN-GJ should log unknown units

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#1079]
The date doesn't have a timezone, so it falls back to UTC, and therefore doesn't get shown in the UI
Also, it would be nice to print out to the console all the units that do not match your list of units (so we can add them later on)

**Comment by anirudh-ramesh** [comment]
@corradio and @sahitya-pavurala 
I've made a prototype of the GJ parser, but I haven't submitted a PR yet, and I've already addressed this issue. Shall shoot a PR this weekend.

**Comment by anirudh-ramesh** [comment]
@sahitya-pavurala, I didn't know that you've been working on this parser as well - I'd written one last week, but didn't get a chance to finish and push. Since we don't want double effort for this, let me know which part you're building right now, and I'll share what I've made.

**Comment by anirudh-ramesh** [comment]
@corradio, I've just shot a PR, since the timezone bug was a minor correction. I shall evaluate the fuel sources since I'm having a feeling there's something off charts.

**Comment by corradio** [comment]
Thanks!

**Comment by systemcatch** [comment]
Do we want to leave this open until the unknown types are printed to the console? At the moment I think the unknown ones will be dropped silently.

**Comment by corradio** [comment]
I think that's better. We can also rename the issue (sorry my laptop is
being repaired so my interactions with github are limited)

**Comment by systemcatch** [comment]
@anirudh-ramesh fancy having a go at this? All that needs to happen if the unit is not in the station_map is to set it's energy type to 'unknown' and print a warning that will get captured by the EM logger.

**Comment by lorrieq** [comment]
I've submitted a pull request for this. 

Not all HTML rows contained unit data, some contained column names. I've hardcoded it to skip the offenders, which for now is just a first cell of "Station Name", and treat remaining rows as unit data.

For "valid" units, their generation is added to the unknown production sum in value_map and the logger logs a warning that the unit's fuel type is unknown.
