### ISSUE TITLE
Dragging blocks

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#1083]
To reproduce:
- click to drag
- don't release but stop moving cursor for a few seconds
- try moving the mouse: the map doesn't drag

Seen on Chrome on Windows

**Comment by systemcatch** [comment]
I see this in Firefox on Ubuntu as well.

**Comment by maxbellec** [comment]
Having the same. I believe dragging breaks easiest for me (Firefox on Ubuntu), when I drag "fast"

**Comment by corradio** [comment]
I think this is related to https://github.com/mapbox/mapbox-gl-js/issues/6063
