### ISSUE TITLE
Map does not center on location. 

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#1089]
Seen on the Android app

**Comment by systemcatch** [comment]
Going off on a slight tangent but should the map still center on the users location? With more countries now added outside of Europe there's more places to look at. As it stands some people might not realize there is more to the map than their local area.

There could be a default world view from which users can drill down to the areas that interest them.

**Comment by corradio** [comment]
That is true but I don't see exactly how the ux would be. Are you proposing
a view where the whole world is visible at once?


On Feb 12, 2018 15:30, "Chris" <notifications@github.com> wrote:

Going off on a slight tangent but should the map still center on the users
location? With more countries now added outside of Europe there's more
places to look at. As it stands some people might not realize there is more
to the map than their local area.

There could be a default world view from which users can drill down to the
areas that interest them.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tmrowco/electricitymap/issues/1089#issuecomment-364938928>,
or mute the thread

**Comment by systemcatch** [comment]
Yes, something like this as the starting position (avoiding duplicated edges though).

![world](https://user-images.githubusercontent.com/30196510/36102527-7ce7e99a-1004-11e8-8a21-16994ee813fe.png)

**Comment by corradio** [comment]
The question is how many people visit the map to explore around vs how many
visit to click on countries near their location.
I think recurring visitors do the latter, but I'm not sure. Maybe we should
ask?

**Comment by systemcatch** [comment]
I'm also unsure on that. Asking people will give better answers, twitter/slack combo should cover a range of users.

**Comment by brunolajoie** [comment]
I kinda like the idea of starting with he whole world, now that zooming in
in much smoother with MapBox and that we start to have enough countries to
show ;)
But i'll ask around too!

**Comment by corradio** [comment]
This issue is now fixed. I'll send a tweet around to get some more feedback. Let's open a new issue if we believe we need to change the behaviour!
