### ISSUE TITLE
hover not working on touchscreen laptops

### ISSUE THREAD

**Issue by maxbellec** [tmrowco/electricitymap#1090]
On my laptop (Linux Mint), hover does not work on the map. Bug occurs whether I use Chrome, Firefox or Opera.

When hovering on a country

- it does not change color
- the cursor does not change to pointer
- the tooltip is not shown

However, when hovering on exchange arrows
- the cursor does change to a pointer
- the exchange tooltip is shown

**Comment by jarek** [comment]
Weird, hover on countries works for me same as on other OSes in Firefox 39 (admittedly ancient) and Vivaldi 1.9.818.50 (WebKit/537.36). I have an old install of franken-Ubuntu with XFCE 4.10.

**Comment by maxbellec** [comment]
Alright, I got why. Though I often forget (since I never use it), my screen has touch enabled.

In `map.js`, in this portion

```javascript
this.map.on('mouseenter', 'clickable-zones-fill', (e) => {
      // Disable for touch devices
      if ('ontouchstart' in document.documentElement) { return; }
      this.map.getCanvas().style.cursor = 'pointer';
      if (this.countryMouseOverHandler) {
        const i = e.features[0].properties.zoneId;
        this.countryMouseOverHandler.call(this, this.data[i], i);
      }
    });
```

my laptop is detected as a touch device, so hover is not triggered

**Comment by maxbellec** [comment]
I believe on way to fix this would be to have a `userIsUsingTouch` attribute on the class Map. By default, it would be set to `false`. Then add a function

```javascript
this.map.on('touchstart', (e) => {
  // the user actually touched the screen!
  // he has a touch feature AND is using it
  this.userIsUsingTouch = true;
});
```

Now, when deciding whether to show the tooltip to a client, instead of deciding based on whether he is a touch-enabled device, we base the decision on the value of `this.userIsUsingTouch`, i.e. if he has a touch-enabled device AND is using touch.

What do you guys think?

**Comment by corradio** [comment]
Could work. We should be aware of race conditions though,where touchstart
might be called after some other events that would check if the user is
using touch.
Not sure it could happen but we should make sure.
