### ISSUE TITLE
Start the map fully zoomed out

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#1107]
Polls:
- https://twitter.com/tmrowco/status/963745829411540993
- https://www.facebook.com/tmrowco/posts/424032668032493

**Comment by jpierz** [comment]
I'll cast my vote here for starting the map fully zoomed out :)

**Comment by corradio** [comment]
- No sense to have the map zoomed in when no data
- Twitter 50/50
- Facebook 65% favour zoomed out
- Suggestion: cookies should remember last zoom level

**Comment by brunolajoie** [comment]
What's our choice for default view if you visit it for the first time then? polls suggest zoomed out

**Comment by corradio** [comment]
Yes that's how it's implemented now. Zoomed out in all cases (even second time you visit).
