### ISSUE TITLE
History of energy flows in interconnectors?

### ISSUE THREAD

**Issue by qwjhvbxi** [tmrowco/electricitymap#1110]
I think it would be interesting to have the interconnectors (cross-border export) clickable to display the energy flows and carbon intensity in the last 24 hours, as for regions. This would allow to understand when energy flows from one country to the other during the day (may depend on relative share of wind/solar etc.)

**Comment by corradio** [comment]
What's the user case of clicking on the interconnector rather than on the country?
What are your thoughts?

**Comment by qwjhvbxi** [comment]
Right now, it's difficult to follow flows because clicking on a country only displays the imports, not the exports. By showing the interconnector history it would be possible to show both directions at the same time, and I think it would be interesting to see patterns during the day and in carbon intensity depending on the flow direction.

**Comment by corradio** [comment]
ok so this would be fixed by #1147
