### ISSUE TITLE
ASUS Eee no map shown

### ISSUE THREAD

**Issue by strassburger** [tmrowco/electricitymap#1111]
Asus Eee no map shown
Ranking shown.
Monitor:1024x600 16:9
Is there a limit  of resolution in EM?
I know it is really old  hardware.
Only want to report if the problem is not known.

**Comment by corradio** [comment]
It's probably because webgl isn't supported?
Check http://webglreport.com/

**Comment by strassburger** [comment]
Thanks to the rapid respond.
http://webglreport.com/ shows:


× This browser supports WebGL 1, but it is disabled or unavailable.

Sometimes this is the result of older video drivers being rejected by the browser. Try updating your video drivers if possible.

Also check out Get WebGL, or try installing the latest version of Chrome, or Firefox.

Platform: | Linux i686
-- | --
Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:58.0) Gecko/20100101 Firefox/58.0
Same for Web GL 2
Really looks like pure local problem.
Will check later if i can get it fixed.
Thanks again
