### ISSUE TITLE
Refactor: rename countries into zones

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#1128]

**Comment by gaggle** [comment]
Hi @corradio,

Excuse me if I misunderstand you as I'm only **just** getting aquatinted with the project, but [is this](https://github.com/gaggle/electricitymap/commit/188d4e286a81913d475149869038ff219746b081) the direction you're thinking?

**Comment by corradio** [comment]
Hi Jon,

This is one aspect. The other aspect is in the code itself, where we use
countries instead of zones because we started out with countries :)
What you've done is already helpful and could be merged if you submit a PR!

Olivier

**Comment by gaggle** [comment]
Hej Olivier,

Didn't anticipate you'd be working on a weekend :)

I've made PR available @ https://github.com/tmrowco/electricitymap/pull/1143

Thanks, your project and mission-statement is really interesting.
