### ISSUE TITLE
Rank zones based on renewable energy %

### ISSUE THREAD

**Issue by FirePowi** [tmrowco/electricitymap#1135]
Well… I'm french, we, France, have 60% of our electricity from nuclear sources, 27% renewable, 82g CO₂/KWh, compared to Brasil (central) that have 84gCO₂/KWh but 90% renewable energy, we look better.

I hoped their would be a rank for renewable energy (while we can keep the CO₂ ranking), so that's my idea. And maybe, instead of colouring states based on lower CO₂ == Greener, higher renewable energy == Greener. That way, the France (for exemple) would not be « Green » as « It's ok, your energy is clean, but more something like « Orange » as « Could be really really much better ».

**Comment by corradio** [comment]
The map is really focussed on CO2, so we won't be doing that unfortunately.
