### ISSUE TITLE
Wind stream lines crossover

### ISSUE THREAD

**Issue by nvbargen** [tmrowco/electricitymap#1138]
The wind potential map seams to "replicate", when going through a few zoom-outs and drags, so that the screen ends up with two superposed wind fields, with nicely crossing stream lines. Unfortunately, I cannot specifically reproduce the effect. However, once it occurs, the animated crossing-over stream lines appear to be quite persistent and can only be turned off, by turning the wind display off and on again.

I noticed that the wind field did not zoom along with the map, but at times it looks on zooming out, as  if the wind field from the zoomed-in view is suddenly simply enlarged and superimposed on the map again, rather than the wind field map being re-loaded for the larger view area.  As a consequence of some judicious zoom-in, zoom-out and drag, I managed to replicate the big cyclone between Greenland and Iceland and move it across Labrador, Hudson Bay, and eventually over Kamchatka Peninsula :-)
Prior to reload, the wind-field should stay constrained to the original area, even if it is now smaller on the screen.

![windcrossover](https://user-images.githubusercontent.com/36658179/36597288-91dd78fc-18a0-11e8-983a-86ab407156b1.JPG)
![windcrossover2](https://user-images.githubusercontent.com/36658179/36597294-94b7d860-18a0-11e8-92a1-91ffebf26ee8.JPG)

**Comment by alixunderplatz** [comment]
also IE11 related
