### ISSUE TITLE
Add AR missing plants

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#1141]
feeder_electricity_1       | VMA2TG01 is missing from the AR plant mapping!
feeder_electricity_1       | NESPDI02 is missing from the AR plant mapping!

**Comment by alixunderplatz** [comment]
VMA2**TG**01 most likely belongs to a new [**natural gas** power plant in Villa Maria with three units](http://www.enernews.com/nota/309857/albanesi-y-msu-quieren-generar-mas-electricidad-en-cordoba). So TG02 and TG03 will also follow soon. TG04 could already be included, it's coming online in 2019, as far as I understand the table.

![image](https://user-images.githubusercontent.com/25743609/36630413-4234c758-1966-11e8-9343-36a5f88825ff.png)

For NESPDI, there is a [NESP**DI**01 generator](https://datos.melendez.com.ar/csvTable/min-modernizacion/Generaci%C3%B3n-El%C3%A9ctrica-Centrales-de-Generaci%C3%B3n1a23566b-99d2-4728-848d-c55576c363cd-7.html) running on **di**esel. Searching for NESPDI02 doesn't lead anywhere at the moment, but the ending "DI" suggests it is diesel as well. So we can map it to **oil**.

![image](https://user-images.githubusercontent.com/25743609/36630511-91ccb3c4-1967-11e8-8df1-74146dd14761.png)
