### ISSUE TITLE
Exception BO

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#1145]
feeder_electricity_1  | Exception while fetching production of BO
feeder_electricity_1  | Traceback (most recent call last):
feeder_electricity_1  |   File "feeder_electricity.py", line 111, in fetch_production
feeder_electricity_1  |     objs = parser(country_code, session)
feeder_electricity_1  |   File "/home/feeder/lib_electricitymap/parsers/BO.py", line 149, in fetch_production
feeder_electricity_1  |     sum(datapoint['production'].values()) != 0.0]):
feeder_electricity_1  | AttributeError: 'NoneType' object has no attribute 'values'

**Comment by systemcatch** [comment]
Regular occurrence or one off? I think I understand why this is happening.

**Comment by corradio** [comment]
![image](https://user-images.githubusercontent.com/1655848/36641315-01c73110-1a2e-11e8-86f3-d4ab36c10810.png)

We should really try to set up a parser dashboard when we have some time.

**Comment by systemcatch** [comment]
Yup #1003 would help a lot here.  All that needs to happen first (at high level) is to pipe the EM logger/error handler to another page on the electricity map domain, we can make it look nice later.

**Comment by corradio** [comment]
Maybe a simple first step would be to set up an ELK stack (ElasticSearch + Kibana) on which we can see logs of parsers on two levels (warnings + errors).

**Comment by systemcatch** [comment]
I don't have any experience with that sort of thing so whatever you think is easiest/quickest is fine by me.
