### ISSUE TITLE
CO2 emissions of coal

### ISSUE THREAD

**Issue by pbalistr** [tmrowco/electricitymap#1146]
I love this website, but I have noticed a slight issue with the data. It estimates the CO_2 emissions of coal power stations as 820g/kWh. The reference quoted is IPCC 2014. However, IPCC 2014 estimates the emissions of the average coal power station as about 1000g/kWh. Only the (almost non-existent) IPCC power stations have emissions as low as 820g/kWh. This does not seem an appropriate figure to be using for existing coal power stations.

**Comment by brunolajoie** [comment]
Thanks a lot for your input. Would you have some more details on this so we can investigate?

**Comment by pbalistr** [comment]
Dear Bruno,

On closer inspection, the 820 g/kWh  figure seems to be from “Coal - PC” entry in Table A.III.2 of https://www.ipcc.ch/pdf/assessment-report/ar5/wg3/ipcc_wg3_ar5_annex-iii.pdf. However this appears to be for new efficient coal power stations, not the typical coal power stations used today. Thus my comments still apply.

For example, in figure 7.6 (p. 539) of https://www.ipcc.ch/pdf/assessment-report/ar5/wg3/ipcc_wg3_ar5_chapter7.pdf there is a graphic showing “world average” coal at slightly over 1000 g/kWh. Table A.II.13 (p. 1307) of https://www.ipcc.ch/pdf/assessment-report/ar5/wg3/ipcc_wg3_ar5_annex-ii.pdf gives direct emissions of 961 g/kWh, but this does not include indirect emissions and other GHGs (such as methane).

Perhaps the most informative source I found is https://www.ecoinvent.org/files/2013_-_treyer_bauer_____ijlca_-_electricity_markets_in_ecoinvent_3_part_i.pdf , particularly tables 1 and 2, showing country by country variability in emissions from hard coal and lignite power stations. Most of the data here seems to be from ecoinvent. Unfortunately this also seems to be just direct emissions, but even so they are almost all significantly higher than 820 g/kWh.

This last website also gives some data for gas power stations, which show even greater variability between countries, mainly due to the differences between closed cycle and open cycle gas power stations.

I haven’t checked, but one should probably also investigate the situation in Estonia. They use a lot of oil that is given an astoundingly high figure of 1515 g/kWh. Usually oil fired power stations are better than coal fired powers stations, although I accept that there might be some factors specific to Estonia.

Best wishes,
Paul

**Comment by brunolajoie** [comment]
Thanks a lot Paul. You are right, we should refine the carbon intensities value per region. (This is linked with issue #738 ).
