### ISSUE TITLE
Suggestion: Export/Import Balance in Country Listing

### ISSUE THREAD

**Issue by nvbargen** [tmrowco/electricitymap#1147]
Besides the import/export details (i.e. how many GW to/from which interconnector), in the country details panel on the left, a summary line showing the balance of all imports and exports might be useful so that one can see, if a country is at the moment a net importer or exporter of electricity.

**Comment by corradio** [comment]
Unfortunately we believe this would add clutter to the graphs, and won't be implementing it.
