### ISSUE TITLE
Taiwan TW is offline

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap#1148]
Currently, Taiwan is grey and 24-hours-history is empty as well.

- [The link ](http://data.taipower.com.tw/opendata01/apply/file/d006001/001.txt) in the [TW.py parser](https://github.com/tmrowco/electricitymap/blob/master/parsers/TW.py) seems to show data, though. 
Maybe there have been some crucial changes?

Some other TW related things that should be fixed:
- The source link on the electricitymap website for Taiwan is not shown / shown as "?".
![image](https://user-images.githubusercontent.com/25743609/36668983-6d5ee628-1af3-11e8-91a0-db8cff5b6a64.png)

- In general, the link in README.md will show 404 error and is leading nowhere. Seems like they updated/revised their website a bit?
Here is the website with the 10-min-generation mix that should be linked in README.md:
http://www.taipower.com.tw/tc/page.aspx?mid=206&cid=404&cchk=8ccc1918-8cae-4f40-a2d0-b43454f4f218

![image](https://user-images.githubusercontent.com/25743609/36669034-afe4857a-1af3-11e8-8be7-b15da8a1b58d.png)

**Comment by systemcatch** [comment]
```
When I run it directly I get this output.
chris@ThinkPad:~/electricitymap/parsers$ python TW.py 
TW.py:29: FutureWarning: convert_objects is deprecated.  To re-infer data dtypes for object columns, use DataFrame.infer_objects()
For all other conversions use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  objData = objData.convert_objects(convert_numeric=True)
{'capacity': {'oil': 2573.2, 'coal': 12297.2, 'solar': 1410.5, 'nuclear': 5144.0, 'wind': 690.3, 'unknown': 623.2, 'hydro': 2089.2999999999997, 'gas': 14481.199999999997}, 'source': 'taipower.com.tw', 'countryCode': 'TW', 'storage': {'hydro': -518.5}, 'production': {'oil': 960.7, 'coal': 8332.2, 'solar': 0.0, 'nuclear': 2879.7, 'wind': 317.2, 'unknown': 531.9, 'hydro': 830.9999999999998, 'gas': 12065.7}, 'datetime': datetime.datetime(2018, 2, 26, 20, 20, tzinfo=tzfile('/usr/share/zoneinfo/Asia/Taipei'))}
```

**Comment by systemcatch** [comment]
There was a change to TW.py in https://github.com/tmrowco/electricitymap/commit/8861f5b5d6a62aefcd662df61c82bc6cc38262aa#diff-3b793c91da9ce1810545c0784c81a185 which resulted in the session variable being removed. This could be what is causing the issue. I don't think quality.py is invalidating the datapoints.

**Comment by alixunderplatz** [comment]
I addition, capacities for TW can be added to [zones.json](https://github.com/tmrowco/electricitymap/blob/master/config/zones.json) from here:
http://www.taipower.com.tw/d006/loadGraph/loadGraph/genshx.html#lng
This should also be linked in the README.md then.

"capacity": {
"coal": 12297,
"gas": 14481,
"hydro": 2089,
"hydro storage": 2602,
"nuclear": 5144,
"oil": 2573,
"solar": 1411,
"wind": 690,
"unknown": 1246
},

**By the way**: recent generation by type (even by unit) also seems to be given under that link, in case something in the TW.py parser isn't working anymore.

**Comment by alixunderplatz** [comment]
@systemcatch Ah, I just saw that capacities are included in your first comment here. So these are fetched by TW.py as well, right?
Anyway, the capacity source is not yet in the README ^^

**Comment by systemcatch** [comment]
Yes the parser fetches capacities which look very similar to the ones you posted (missing hydro storage only). @maxbellec any thoughts here?
