### ISSUE TITLE
Lien France - Angleterre inversion Import/Exports ?

### ISSUE THREAD

**Issue by FlorentVTT** [tmrowco/electricitymap#1159]
ce 27/02 19h : sur RTEECO2mix France importatrice, et l'inverse sur electricitymap ?

![image](https://user-images.githubusercontent.com/1282537/36746934-dd1e0484-1bf3-11e8-8970-3717bc56df36.png)

![image](https://user-images.githubusercontent.com/1282537/36746872-b1f5ff50-1bf3-11e8-8dc6-31d3fb779c53.png)

**Comment by FlorentVTT** [comment]
![image](https://user-images.githubusercontent.com/1282537/36746994-07ea7c38-1bf4-11e8-93b6-f7f51d1d0ee6.png)

**Comment by jarek** [comment]
https://www.bmreports.com/bmrs/?q=generation/avghalfhourIC says 2018-02-27 settlement period 37 (around 19:00) was -484 MW where positive means flow to GB. So 484 MW exported GB to FR, so confirming that we're showing it wrong.

It also says that FR->GB flow was 378 MW during settlement period 33 (around 16:00). Maybe our data is stuck on the old value?

What is the data in ENTSOE?

**Comment by alixunderplatz** [comment]
![image](https://user-images.githubusercontent.com/25743609/36747881-82ef59e2-1bf6-11e8-8c65-9cf339a57176.png)

**Comment by alixunderplatz** [comment]
It is due to the delay of the published data I think. Everything is fine I think

**Comment by jarek** [comment]
Ah yeah Electricity Map is now showing France as importing as well.

**Comment by FlorentVTT** [comment]
Oh yes !
Good !

Sorry
