### ISSUE TITLE
idea - another statistic

### ISSUE THREAD

**Issue by gitkoyot** [tmrowco/electricitymap#1163]
It would be good to see which country produces most CO2/year to CO2/citizen.

**Comment by jarek** [comment]
Hi @gitkoyot , thanks for the suggestion. I understand the appeal of the per-capita statistic. The downside of it is that electricity generation is only a part of a nation's overall climate impact. A per-capita statistic would effectively reward offshoring factories (even if they go to countries powered by coal) and switching from trams to diesel buses. See https://github.com/tmrowco/electricitymap#frequently-asked-questions under "Why don't you show emissions per capita?" for a bit more information. Thanks again for commenting!

**Comment by gitkoyot** [comment]
Still I think that the graph is missing something. For example Germany has the most "green" electricity, yet it is no1 in CO2 production in Europe.  Estonia is the  worst - but overall it has little effect on total co2 emission

**Comment by brunolajoie** [comment]
What would be the pertinence of comparing absolute emission values in countries that have different population size?

**Comment by jarek** [comment]
The Electricity Map website is a visualization of data for https://www.co2signal.com. CO2 Signal tries to help consumers to use electricity when, or where, it's cheapest, for loads that can be time-shifted. As an approximation for domestic life, it can inform a decision on when to use the laundry machine (it's best on the day that is sunny and/or windy). Anything else is more or less incidental.

Deciding who is greener is a long long question and will not be answered with electricity data alone. To give another example: is it better to heat with electricity, like France and Ontario do, or with gas, as England does? The gas consumption doesn't show in EM at all.

**Comment by gitkoyot** [comment]
>What would be the pertinence of comparing absolute emission values in countries that have different population size?

Ow.. I would not stop only at total CO2 emissions.

I would see this as another dimension(s) to look at.

How much given countrys citizens consume electricity? How much given country exports/imports electricity? How much factories use ?

**Comment by brunolajoie** [comment]
Sure, lots of things could be shown indeed. Our priority today is to increase the geographical scope of the electricity map. We will then be able to compute all indicators from our database if someone needs it later
