### ISSUE TITLE
Output Occurrence for Electricity Generation by Source

### ISSUE THREAD

**Issue by Hyric89** [tmrowco/electricitymap#1164]
Looking at the capacity factor of an electricity source is one way of judging said source in a country. Some countries utilize fuel sources to near full capacity most of the time while at other times, capacity seems constantly under-utilized. Sometimes, capacity factors for a given source varies greatly such as coal power in the UK. Wind power everywhere tends to fluctuate quite a lot. Sometimes I look at capacity factors of different sources and wonder how often does the presented output occur. Same goes for imports and exports.

As for what I mean by "occurrence" in concrete terms, 50% would denote the median, 10% the first decile, etc.

Occurrence could be an interesting statistic to come along with an electricity source's share of generation, capacity factor and carbon intensity. Denmark is currently producing 3.73 GW of wind power. How often does Denmark get 3.73 GW or less from wind power according to data from one year ago? Another interesting feature would be to add a median dividing line within capacity bars of electricity sources.

I don't know if this might be asking too much. If there is anything left unexplained, do bring it up and I'll add to this to the best of my ability.

**Comment by brunolajoie** [comment]
Hello Hyric. These are all great ideas for analytics indeed, but they require querying the historical database to be computed. While www.electricitymap.org is meant to show real-time data freely to everyone, the database is accessible at data.electricitymap.org, where such analysis are commercialized to sustain the electricitymap as a free project
