### ISSUE TITLE
SG parser: Tesseract dependency is missing

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#1166]
FileNotFoundError: [Errno 2] No such file or directory: 'tesseract': 'tesseract'

**Comment by systemcatch** [comment]
I don't know what server setup EM uses but pytesseract needs the tesseract command accessible from the commandline for the parser to work.

**Comment by corradio** [comment]
We'll fix it on our side then

**Comment by systemcatch** [comment]
If it's a problem pytesseract can be given a different path to the tesseract engine.
