### ISSUE TITLE
CL-SIC parser returns wrong datetime

### ISSUE THREAD

**Issue by brunolajoie** [tmrowco/electricitymap#1168]
CL-SIC parser returns datetime of 0018 instead of 2018, as illustrated below:

`datetime: 0018-02-18 (06:43:00.000) CET`
`production: {"unknown":0,"coal":2206.6,"hydro":2416.39660,"wind":309.314,....}`
`updatedAt: 2018-02-20 (23:40:06.979) CET`

@systemcatch any idea?

**Comment by corradio** [comment]
This reminds me we should also update the validation functions to make sure we don't insert something that's < year 2000

**Comment by systemcatch** [comment]
I'm fairly sure it's https://github.com/tmrowco/electricitymap/blob/master/parsers/CL_SIC.py#L334 that is causing the problem. But I already see a better way to get the datetime that won't be so convoluted.

**Comment by systemcatch** [comment]
Something else I've noticed is that the site returns status code 200 on it's 404 page which messes up the logic to get the right file. Another thing to fix.

**Comment by corradio** [comment]
Happened again.

**Comment by systemcatch** [comment]
It returned year < 2000 again?

@corradio it's working now when I run it manually. That error indicates the file was there with it's usual name, but the structure must have been totally different for https://github.com/tmrowco/electricitymap/blob/master/parsers/CL_SIC.py#L262 to fail. Let's keep and eye on it and see if it happens again, they might change the file type near the end of the month or something.

**Comment by maxbellec** [comment]
adding the check yes
