### ISSUE TITLE
Selecting zones without data shows history of previously selected zone

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap#1188]
While accessing electricitymap from a browser (Chrome, Firefox, Edge, IE), this tiny bug occured:

1. Select a zone **with** data
2. Select a zone **without any** data (no exchanges with another zone) 
3. You will see, the generation bars will disappear, but the history for CO2 intensity and history of generation remain unchanged. You can even observe the "loading" circle, but afterwards, the history is the one of the previously selected zone with data

**Comment by systemcatch** [comment]
I can see this happening as well.
