### ISSUE TITLE
Weird axis positions in Edge and IE

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap#1189]
For some reason, in Edge and Internet Explorer, x- and y-axes are placed on the opposite sites in the history charts
🤔 ❗️❓  

![image](https://user-images.githubusercontent.com/25743609/37241292-610bbd5c-2457-11e8-92fc-60fe76de4d9a.png)

**Comment by corradio** [comment]
@jbuverud can you help here as you're on WIN?

**Comment by jbuverud** [comment]
Yup - can reproduce and will have a look.
