### ISSUE TITLE
Brazil solar data out of range

### ISSUE THREAD

**Issue by systemcatch** [tmrowco/electricitymap#1199]
```
Traceback (most recent call last):
  File "feeder_electricity.py", line 148, in fetch_production
    objs = parser(country_code, session, logger=public_logger)
  File "/home/electricitymap/parsers/BR.py", line 131, in fetch_production
    generation = production_processor(gd, zone_key)
  File "/home/electricitymap/parsers/BR.py", line 81, in production_processor
    raise ValueError('the solar value is out of range')
ValueError: the solar value is out of range
```

**Comment by jarek** [comment]
I see `'solar': -1.1016345` being given for BR-CS right now. It looks like the parser is coded to raise ValueError on solar values `< -1`.

I guess a bigger question is how we want to handle this? -1.1 MW is a pretty obvious marginal reading that should be safe to overwrite to 0. Do we want to set limits of what's acceptable in each parser separately? That'll be a lot of edge cases to chase.

**Comment by jarek** [comment]
If we decide that -1 MW we can tolerate but more than that is an error, then this isn't a bug at all.

**Comment by systemcatch** [comment]
There is a function in https://github.com/tmrowco/electricitymap/blob/master/parsers/lib/validation.py#L74 that would work for handling this (anything smaller than -5 is set to None). Maybe we should move it into quality.py and apply that to all small negative numbers returned.
