### ISSUE TITLE
Colorblind mode not working

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap#1202]
I just hit the colorblind button, but nothing changed.
The bar in the lower left corner of the map disappeared/was empty. 

![image](https://user-images.githubusercontent.com/25743609/37297072-110885ac-261d-11e8-82f7-132d8bf9c54f.png)

Refreshing the page led to seeing the "loading" circle only (colorblind box still active). 

![image](https://user-images.githubusercontent.com/25743609/37297108-2d93602a-261d-11e8-90e7-0f737e6ce9a6.png)

Had to close and re-open Chrome & Edge to see the map in usual mode again.

**Comment by jarek** [comment]
I can duplicate in Vivaldi/Webkit `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.114 Safari/537.36 Vivaldi/1.9.818.50` and my ancient Firefox 39 `Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:39.0) Gecko/20100101 Firefox/39.0`

Possibly related thing from console?

```
" action    " Object { key: "colorBlindModeEnabled", value: true, type: "APPLICATION_STATE_UPDATE" }
 error      TypeError: t is not a function
    at r.i [as originalColorScale] (https://www.electricitymap.org/dist/vendor.a76b52e011ae574a5cf9.js:1:180496)
    at https://www.electricitymap.org/dist/bundle.f06a01fe8089ff9cb1fc.js:1:676653
    at Array.map (native)
    at r._setDomainAndRange (https://www.electricitymap.org/dist/bundle.f06a01fe8089ff9cb1fc.js:1:676602)
    at new r (https://www.electricitymap.org/dist/bundle.f06a01fe8089ff9cb1fc.js:1:672917)
    at be (https://www.electricitymap.org/dist/bundle.f06a01fe8089ff9cb1fc.js:1:36080)
    at https://www.electricitymap.org/dist/bundle.f06a01fe8089ff9cb1fc.js:1:51735
    at n (https://www.electricitymap.org/dist/bundle.f06a01fe8089ff9cb1fc.js:1:1404)
    at f (https://www.electricitymap.org/dist/vendor.a76b52e011ae574a5cf9.js:1:629451)
    at https://www.electricitymap.org/dist/vendor.a76b52e011ae574a5cf9.js:1:1329730
```

**Comment by alixunderplatz** [comment]
It also doesn't work in the Android app - it becomes unusable after activating colorblind mode, closing the app, opening the app. I had to go to the application settings and delete the electricitymap app data on my phone to make it work again

**Comment by nvbargen** [comment]
Needless to say, it doesn't work under IE11 either. However in contrast to @alixunderplatz I didn't end up in an indefinite "load".  Where I do get the "eternally loading" is, when I try to turn on the solar layer with the new button at the top right. Wind does work - currently slow, but definitely there.
