### ISSUE TITLE
Add fullscreen option to the map

### ISSUE THREAD

**Issue by systemcatch** [tmrowco/electricitymap#1204]
I don't know if this is possible given the architecture, close if it's not. It would be great to have a way to make the map fullscreen. For demos/shows/videos it would focus attention on the core concepts and reduce visual clutter. Also the left panel could be made collapsible until needed to display charts etc.

Iterating on that idea further maybe the left panel could be made fully expandable so that if someone wants to to view only the graphs it's possible in a big format. The origin of electricity chart is very interesting but also cramped with everything else in that panel.

**Comment by corradio** [comment]
Are you thinking mostly of hiding the left panel? @jbuverud and me thought of adding that option.

**Comment by systemcatch** [comment]
Any of those options I listed would be an improvement. But yes that one would be good imo, don't know how much work it is to code though?

**Comment by corradio** [comment]
I've added #1243. Is there anything else we could do?

**Comment by systemcatch** [comment]
I think that is a very good plan.

**Comment by jbuverud** [comment]
We could also consider something like this for a full-screen alternative: https://www.mapbox.com/mapbox-gl-js/example/fullscreen/

**Comment by corradio** [comment]
Can we close this one now that a PR for the collapsable left panel is submitted?

**Comment by systemcatch** [comment]
It depends on if you still want full screen as an option. I watched a small part of the COP23 talk and thought removing the browser panel would be a plus when doing a demo.

**Comment by systemcatch** [comment]
Alright we'll leave it for now. :hammer:
