### ISSUE TITLE
wind power potential gone after selecting a country

### ISSUE THREAD

**Issue by maxbellec** [tmrowco/electricitymap#1207]
To reproduce : 
- load the map, the wind power potential bar works
- select a country (zone), the wind power potential bar is broken (show bar showing the potential)

![screenshot at 2018-03-13 12-10-18](https://user-images.githubusercontent.com/7253902/37338386-9a76c2fa-26b7-11e8-9fdc-4f2243b95ee2.png)
![screenshot at 2018-03-13 12-10-02](https://user-images.githubusercontent.com/7253902/37338387-9a9f7830-26b7-11e8-9833-b0487890a525.png)

**Comment by nvbargen** [comment]
The wind potential indicator (little black line on the scale bar) does work again, when the country display in the left panel is turned off again.
The wind potential indicator also moves way off scale when moving over a very windy area south of Iceland.

**Comment by jbuverud** [comment]
@corradio, this is a result of your commit https://github.com/tmrowco/electricitymap/commit/89b6ddbc4384b717d44d4cf44573153df2f79f46

```javscript
function mapMouseOver(lonlat) {
  if (getState().application.windEnabled && wind && lonlat && typeof windLayer !== 'undefined') {
...
    if (!windLayer.isExpired(now, wind.forecasts[0], wind.forecasts[1])) {
...
      if (!getState().application.selectedZoneName) {
        windColorbar.currentMarker(Math.sqrt(u * u + v * v));
      }
    }
  } else {
    windColorbar.currentMarker(undefined);
  }
```

Is there any reason for this, or can we remove the check for selectedZoneName?

**Comment by corradio** [comment]
Did a git blame to go back in time. I see no reason to keep that check.
Good job spotting this!
