### ISSUE TITLE
Faroe Islands, solar

### ISSUE THREAD

**Issue by Bjarkigd** [tmrowco/electricitymap#1210]
Not the ideal solar location I'd say, however a business here has added a large'ish roof setup of 12kW, which sends power to the grid. Nothing huge or anything but it's as start, and word on the street is that interest for similar stuff in the near future is on the rise. 

Live generation can be found here http://www.evishine.com/tonn if anyone would like to add it to the mix, then that would be great (no idea if it will even be visible on the map, but oh well)

**Comment by jarek** [comment]
Hi, thanks for the heads-up, and congratulations on the installation!

Generation in past 24 hours has been around 35 to 50 MW. Unfortunately even taking 35 MW, 12 kW is such a small fraction that it'll not display in any meaningful way. A guideline for display would be probably around half a percent, or 175 kW.

Do you know of any other installations with online data?

**Comment by Bjarkigd** [comment]
The first test installation, an 4kW installation from 2007, is also supplying to the grid, the only online data I know of for it can be found here, (not particularly  up to date data, last being from 2010) http://www.vh.fo/default.asp?menu=314 (also I'd say it's not the best location, specially for winter, near constant shade due to mountain)

But since tech and prices have become somewhat more realistic, the utility hopes to get around 30MW of solar on the grid by around 2030, so we'll hopefully see some more datapoints at some point.

There are several lighthouses which have run entirely on solar for decades, so it's proven that it can work here. Some few private tests have been done over the years, no idea about how well they've worked.

But more online live data, alas not yet.

**Comment by systemcatch** [comment]
At what point does the map round down to zero?

**Comment by corradio** [comment]
It never does - the bottleneck is rather how it looks visually. It starts becoming "invisible" around 1% of total production.

**Comment by systemcatch** [comment]
I suppose even if it's not visible it might be worth logging.

**Comment by corradio** [comment]
What is the status here? If no-one is working on adding it I believe we can close this issue, as it has relatively little impact.

**Comment by corradio** [comment]
I'll close this issue as I believe Electricity Map should tell about the grid intensity (for consistency with other countries). Feel free to re-open if you disagree. cc @brunolajoie
