### ISSUE TITLE
Ranking: do not update allways after change country

### ISSUE THREAD

**Issue by strassburger** [tmrowco/electricitymap#1219]
In Ranking:
After changing country data is not updated allways.

![grafik](https://user-images.githubusercontent.com/28303688/37489915-0f2d6664-2891-11e8-8d7c-00cfd6be1840.png)

After update  browser window data is  shown correct.
![after-browswer-update2018-03-15 20 47 07](https://user-images.githubusercontent.com/28303688/37490379-5f0d8ece-2892-11e8-9788-dc66be256f54.png)

**Comment by jbuverud** [comment]
I'm having trouble reproducing this. Do you have any more information? Browser version, OS, steps to reproduce?

**Comment by strassburger** [comment]
@jbuverud,
Thanks for checking the problem.
My equipment, sorry do not have other machine to crosscheck:
Hardware: Lenovo G560E 2 GB Ram
OS: Unbuntu 14.04 32 bit
Browser:
Firefox 59.0 (32-Bit)
or
Chromium Version 64.0.3282.167

To reproduce:
Try to doc:
1. https://www.electricitymap.org
2. Show Ranking
3. select Spain (El Hierro)
4. close it
5. select Estonia
6. Close it
7. select Spain (El Hierro)
8.Close it
9. select Estonia
10. select Spain (El Hierro)
11. got change the Zoom to cach a picture, after zooming problem disapeared
12.. close it
13. select Estonia
14. close it
15. select Spain (El Hierro)here we are:....

here we are:
![bildschirmfoto vom 2018-03-16 11 37 14](https://user-images.githubusercontent.com/28303688/37518769-7d7cb3fe-290e-11e8-9390-857cb63fda25.png)

16. Update Browser Window (F5): all fine:
![bildschirmfoto vom 2018-03-16 11 40 14](https://user-images.githubusercontent.com/28303688/37518860-dfdf2824-290e-11e8-9c6b-caa89093c621.png
If it do not work with first try,just play around a while
It happens also with other countries.

Hope helps

**Comment by corradio** [comment]
Hi @strassburger,
I've pushed a small fix. Let me know if it still happens.

Olivier

**Comment by strassburger** [comment]
Hi @corradio,
sorry  stll happens, even all data, not only 
Carbon intensity in the last 24 hours
Origin of electricity in the last 24 hours
do not change.

In other words:
in Ranking:
1. select New Zealand (South Island)
2. close
3 Select Costa Rica
4. Close
5.select New Zealand (South Island): Still data off Costa Rica complete shown

but solved is:
graphs disappearing after ca 10 Minutes
Carbon intensity in the last 24 hours
Origin of electricity in the last 24 hours

**Comment by corradio** [comment]
I've been able to reproduce. Pushing a fix.

**Comment by strassburger** [comment]
@corradio 
Thanks.
cross checked
Works fine
