### ISSUE TITLE
Add Feature/Cyprus

### ISSUE THREAD

**Issue by Pantkowsky** [tmrowco/electricitymap#122]
Cyprus is a member of EU and ENTSOE provides information about their energy production. It should be included on the map.

**Comment by corradio** [comment]
Also, data for Cyprus can be found on the TSO's main website on the two graphs on the right side: http://www.dsm.org.cy/nqcontent.cfm?a_id=1&lang=l2

**Comment by ultibo** [comment]
Hello, I'm looking into adding Cyprus.

**Comment by ultibo** [comment]
Hello, I got a quick question before doing the Cyprus parser.

The entsoe website says cyprus produced last year
158 MW wind,
115 MW solar,
1478 MW fossil fuel,
10 MW biomass
![image](https://user-images.githubusercontent.com/5710280/29179651-6da08be6-7df5-11e7-9828-8721c9c1c862.png)

I also found on their on the link you gave (TSO website) : 
[Here](http://www.dsm.org.cy/en/daily-system-generation-on-the-transmission-system-mw
) The total realtime generation in a chart + excel format

Time | Generation Forecast | Actual Generation (MW) | Total Available Generation Capacity | Wind Farms Generation
-- | -- | -- | -- | --
-- | -- | -- | -- | --
17:30 | 848 | 819 | 1180 | 28
-- | -- | -- | -- | --

[Here](http://www.dsm.org.cy/en/wind-and-solar-farm-generation) the wind generation
they say the solar is estimated, and it doesn't appear on the excel.

Time | Wind Farms Generation
-- | --
-- | --
17:30 | 28
-- | --

And Nothing on the biomass.

Questions : 
1. Are you ok to leave biomass out ? Or should I compute an estimate based on last year total production
2. Is it ok to read the data directly from the js in the page charts ? It's a bit nasty but the solar doesn't appear in the excel.

Thanks for your advice.

**Comment by systemcatch** [comment]
@ultibo I was looking at doing this one but if you want to take a crack at it please go ahead.  You'll find this link https://en.wikipedia.org/wiki/Electricity_Authority_of_Cyprus useful since it contains quite a bit of detail about Cyprus's main 3 powerplants.  They are all burning fuel oil which makes the breakdown of generation easier.

**Comment by ultibo** [comment]
@systemcatch Ok yeah if you don't mind i'll give it a try, seems doable for a first contribution :)

@corradio i'll do the following : 
1. read current total generation in the graph [here](http://www.dsm.org.cy/en/daily-system-generation-on-the-transmission-system-mw)
2. read current solar and wind generation in the graph here [here](http://www.dsm.org.cy/en/wind-and-solar-farm-generation)
3. ignore biomass generation

and return appropriate values.

**Comment by systemcatch** [comment]
Breakdown of generation for past years which should be useful.
http://www.dsm.org.cy/en/cyprus-electrical-system/electrical-energy-generation/energy-generation-records/yearly/res-penetration
1) I would set the biomass key to none since it is unknown rather than zero.
2) Not sure if @corradio  wants estimated solar data on the map.  It might be good enough since it's from the source.  Reading from the js looks quite messy, you'll probably need to do a regex on the request/soup for the data row then parse it.  Using the excel data is probably easier and likely to be more future proof if they alter the site.

**Comment by ultibo** [comment]
ok thanks for the info, let's see what @corradio thinks about the solar estimation. 
If we don't want it, then i'll just parse the main excel and that's it.

**Comment by corradio** [comment]
Let's keep as none all the keys for which we don't have any data.
Estimated solar is fine, as long as it comes from the source. Hopefully they will change it in the future and be able to monitor it.
I suggest the put all the non wind/solar as unknown. It will be assigned a "fossil fuel" co2 emission intensity.
Thanks guys

**Comment by ultibo** [comment]
Issue should be closed once PR #677 is merged

**Comment by corradio** [comment]
If you are able to document that the other capacities are 0, then we can:
- redirect unknown to oil
- set production values of the other types to 0
- set capacity values of the other types to 0

**Comment by corradio** [comment]
If we're sure than conventional = oil (i.e. that the ENTSOE page did not
miss any other type of conventional), then go for it!

Oli

**Comment by ultibo** [comment]
ok, on this page : 
http://www.dsm.org.cy/en/cyprus-electrical-system/electrical-energy-generation, they list the 3 conventional units, and according to wikipedia 

https://en.wikipedia.org/wiki/Moni_Power_Station
-> Primary = Heavy Fuel Oil
https://en.wikipedia.org/wiki/Vasilikos_Power_Station
-> Primary fuel : heavy fuel oil / natural gas, Secondary fuel :  coal / diesel oil
but according to the description it seems that coal is not used, and they also don't mention natural gas in the description. 
https://en.wikipedia.org/wiki/Dhekelia_Power_Station
-> Primary fuel : Heavy fuel oil

so in total yeah i'm 99% sure

**Comment by corradio** [comment]
let's do it!

**Comment by corradio** [comment]
Is there any interconnector that we might need to incorporate? Else we can close this issue.

**Comment by ultibo** [comment]
PR done

What's an interconnector used for ? 
I've tryed to google around and cyprus imports 94% of it's energy but that's in form or raw oil
(according to this) https://tradingeconomics.com/cyprus/energy-imports-net-percent-of-energy-use-wb-data.html 

They apparently do not import/export electricity (as of 2013)
https://www.indexmundi.com/energy/?country=cy&product=electricity&graph=exports
https://www.indexmundi.com/energy/?country=cy&product=electricity&graph=imports

**Comment by corradio** [comment]
ok! If they don't import/export then it means there's no interconnector (i.e. a cable allowing import/export of electricity)
