### ISSUE TITLE
AR: Plant mappings missing

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#1222]
March 16th 2018, 12:14:50.317 | WARNING | AR | ALUATG08 is missing from the AR plant mapping!
March 16th 2018, 12:14:50.317 | WARNING | AR | ALUATG07 is missing from the AR plant mapping!
March 16th 2018, 12:14:50.316 | WARNING | AR | ALUATV01 is missing from the AR plant mapping!

**Comment by alixunderplatz** [comment]
Aluar gas power plant. Will add these four to AR.py mapping

![image](https://user-images.githubusercontent.com/25743609/37518555-e31bae16-2915-11e8-8cea-fbc3565cb44b.png)


https://www.industryabout.com/country-territories-3/1230-argentina/fossil-fuels-energy/17340-puerto-madryn-aluar-gas-power-plant
