### ISSUE TITLE
Power plants availability feed for France

### ISSUE THREAD

**Issue by gustavecha** [tmrowco/electricitymap#1229]
As you may know, there is this twitter feed which ives live messages regarding French power plant and western Europe transmission network
https://twitter.com/AlertesHTB

It would be great to display its message when looking at France area.
Main advantage is AlertesHTB backend processes plants and generators availability from TSO and aggregates them, as to give the next available capacity after an event which is not necessarily the full capacity. This isn't done by TSO currently.
If twitter feed isn't the most valuable display, it may be possible to get the aggregated data directly from the team.

I don't know if it exists elsewhere.

**Comment by brunolajoie** [comment]
Hello Gustav,
Thanks for this interesting data stream, we'll keep it in mind.
It's a bit too early in the Electricity Map Project to start integrating such granular data but we might get back to it later (priorities today are 1. getting more countries / bidding-zones on the map, 2. improve data reliability)
