### ISSUE TITLE
Denmark 

### ISSUE THREAD

**Issue by Jababinet** [tmrowco/electricitymap#1231]
Hello,
Congratulations for your beautiful work. Clear and easy to understand display. 
But why split Denmark in two units?
One country, one electrical energy policy, one environmental result, no?
Displaying this way would allow to isolate specific results in a part of a country, and make an example of partial things. 
Thanks
Jean Babinet

**Comment by systemcatch** [comment]
Hi the map is focused on zones rather than countries/states (though often zones will line up with country borders), see #1069 for more info and a better explanation of why.

**Comment by brunolajoie** [comment]
I would add that we are of course able to reconstruct country-wide data based on its bidding-zone parts. Let us know if you are interested in such data.

**Comment by Jababinet** [comment]
Bonjour
Mais pourquoi pas diviser le pays en tout petits morceaux, pour que le
monde ne puisse surtout pas voir l'échec patent de la transition
énergétique danoise ?
En voilà une belle façon d'informer !

Quelle est, en population et en puissance, la taille de ces parcelles ?
3 GW pour DK2 ! Ridiculement petit !
Mais pourquoi pas diviser le monde en parcelles de 1GW ?
Là, vous allez en perdre, des clients potentiels.
Et offrir une belle brèche à la concurrence à l'affût.
Bien cordialement,
Jean Babinet

**Comment by corradio** [comment]
Hi Jean,

Let's keep in English so other people can join the discussion.
The long-term goal is to cover the world at the smallest granularity possible.
I know the map has been used as a political instrument - however, in certain areas, the country granularity is not always the one that makes politically sense (some countries have very strong federal governments, and some countries even have very strong regional governments).

I am however not sure to understand why dividing up countries is not a good thing?
If you look at the case of Denmark, it highlights even more the fact that most wind turbines are at the west, and not the east. It leads to better understanding of how the electricity system works.

We've been experimenting quite significantly with the US for example, before breaking it up into states. Denmark is a second experiment now. Let us know if you have any other ideas as to what we could do better, but as a starting point I think the political objectives still come very clearly through - even with a country subdivision.

If what you're looking for is to take screenshots of countries to show how good/bad they are, and if that's a general use case, then maybe we should have the ability to show aggregate view (Europe/Country...) in the ranking?

Thank you for your understanding. Let me know your thoughts.

**Comment by corradio** [comment]
I'm closing here due to inactivity.
@Jababinet feel free to re-open, or reach out on Slack if you have any comments.

Olivier
