### ISSUE TITLE
Use unified interval for arrow rotation // Reduce arrows' coordinates precision

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap#1235]
I suggest using a unified interval like 45° (± 0°, 45°, 90°, 135°, 180°) for the steps of rotation of the exchange arrows. That could be included as comment (or "guideline") in exchanges.json or in the README.md.
It may tidy up the look of the map a bit, especially in dense areas like Europe.

In addition, many of the arrows' coordinates have 3 or more decimal digits. 
Precision could be reduced to 2 or 3 digits without any noticeable influence.

Here is an overview of the recent rotation of all 134 exchanges:

![image](https://user-images.githubusercontent.com/25743609/37568518-476ac16a-2ad6-11e8-8773-95f7bdf1cb1f.png)

**Comment by alixunderplatz** [comment]
Couldn't the rotation values even be reduced to be within a 0° to 135° range (0°, 45°, 90°, 135°), if the direction of the flow in exchanges.json is adjustable to be pointing in the direction of one certain semicircle? Or is this dependent on the exchanges direction in the parsers?

_ _ _ _
btw: Is that -180° rotation for the RU-KGD <-> LT arrow a gimmick in the code? ^^ 

> In Soviet Russia, angle rotates you!

-🙃

**Comment by corradio** [comment]
Hi @alixunderplatz . Sorry I'm only looking at this now.
We won't have time to work on this, and I believe it doesn't change that much visually.
You're very welcome to update it if you find some time!
I'm closing in order to reduce the number of issues we have, but feel free to re-open if you think it's important.
