### ISSUE TITLE
Costa Rica

### ISSUE THREAD

**Issue by MinnieBannister** [tmrowco/electricitymap#1266]
Costa Rica is showing as N/A on your map.  They are 99% renewable.  https://www.independent.co.uk/news/world/americas/costa-rica-electricity-renewable-energy-300-days-2017-record-wind-hydro-solar-water-a8069111.html

**Comment by jarek** [comment]
Hi, thanks for noticing. We have Costa Rica implemented but they've changed something on their website so the parser must be updated.

```
Traceback (most recent call last):
  File "/home/feeder/lib/fetch_data.py", line 125, in launch_parsers
    **parser_kwargs)
  File "/home/electricitymap/parsers/CR.py", line 166, in fetch_production
    yesterday_date = soup.select('#formPosdespacho:pickFechaInputDate')[0]['value']
IndexError: list index out of range
```

**Comment by jarek** [comment]
Hi Minnie,

Costa Rica should be back on the map in a few days :+1: Thanks for looking!
