### ISSUE TITLE
El Hierro /REE parser should return 0 when oil production is 0

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#1271]
This looks suspicious:

![image](https://user-images.githubusercontent.com/1655848/37960741-ae07308e-31b6-11e8-8663-207e29aca241.png)

especially given:
http://euanmearns.com/el-hierro-end-2017-performance-update/

**Comment by jarek** [comment]
Please see history https://demanda.ree.es/movil/canarias/el_hierro/total

Around 6-10 MW load is normal, and they have enough turbines to cover this when it's windy.

See e.g. 17 March when they were 61% oil, vs 20 March when all was covered by wind and hydro

**Comment by alixunderplatz** [comment]
it's been like this before in periods with strong wind. The wind turbines take over frequency control and pumped storage is used to dump excess energy

**Comment by systemcatch** [comment]
I see 100% of electricity supplied by wind for at least the last 18 hours. Not impossible as average demand is roughly 6-7MW.

**Comment by jarek** [comment]
If anything, the parser needs to be modified to return 0 when oil is not being used, rather than "?"

**Comment by corradio** [comment]
Ok but was is weird is that we have load curves between 7 and 9 MW
![image](https://user-images.githubusercontent.com/1655848/37961140-c914e4ec-31b7-11e8-9032-c82e889c92f2.png)

whereas REE shows curves between 3 and 6 MW:

![image](https://user-images.githubusercontent.com/1655848/37961180-e45d8e84-31b7-11e8-8fb5-dd2646d4bb18.png)

Could it be a bug in the frontend panel that doesn't subtract storage (although it should)?

Also agree with @jarek that the parser should return 0 instead of ?

**Comment by systemcatch** [comment]
Frontend panel does not subtract storage.

**Comment by jarek** [comment]
If storage is extracted, should exports be extracted as well? Both impact electricity used in a zone

**Comment by alixunderplatz** [comment]
Storage (and exports) shouldn't be subtracted from generation, because it is part of consumption that relies on the same mix in the grid as us end-users.
This is only required for things like #1030 and #1147

**Comment by corradio** [comment]
Sorry for not being clear. What I imagined as correct behaviour would be to subtract storage and exports such that the curve sums up to the load curve.
Subtracting storage and exports should be done such that the mix doesn't change. That means that if the mix (imports + production) is 30% wind and 70% oil, and storage is 5% of those, we should subtract 5% of 30% wind and 5% of 70% oil -> the mix stays unchanged but we rescaled the curve to be the load curve.

Does that make sense?

**Comment by alixunderplatz** [comment]
Isn't the goal is to show consumption mix, which is based on everything that is available in a zone, and not necessarily the load?
That means, everything that has a positive flow in the direction of the grid of a zone - be it imports or generation - is included in that mix. As you wrote, it doesn't matter if you subtract the types by their percentage or not, the low-CO2 and renewable shares will stay the same. I'd leave it as it is in the "origin of electricity" graph. 

But ideally, there'd be a seperate load graph with imports, exports etc. as proposed in #1030 to see where the stuff in "origin of electricity" is actually going (load, charging storage, export) and coming from (import, total gen, discharging storage).

**Comment by corradio** [comment]
Let's talk about the graph issue in https://github.com/tmrowco/electricitymap/issues/1030, and let's keep that issue about setting oil to 0 (instead of None) when production indeed is 0

**Comment by corradio** [comment]
Thanks @blackleg. I'm closing this one for now. Let's re-open if we see the bug again.
