### ISSUE TITLE
Validation: DK coal should be required

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#1283]
It's currently not, and show too green.
This is probably true for a number of other countries.

![image](https://user-images.githubusercontent.com/1655848/38172536-2e3c4640-35ae-11e8-88f2-6507eb40285f.png)

**Comment by jarek** [comment]
Yeah, half an hour later the data shows 1.5 GW of coal :/

Would it be sufficient to filter for coal being `None` (question mark shown here) rather than 0? In cases of missing data, is it always None, or sometimes wrongly 0 as well?

**Comment by corradio** [comment]
It seems like filtering for None might be enough.
Should do that filtering inside the parser or in https://github.com/tmrowco/electricitymap/blob/master/parsers/lib/quality.py#L36 ?
Also, @maxbellec, what happens if only one datapoint does not pass the validation in quality.py? Do we invalidate the whole series or just that datapoint?

**Comment by corradio** [comment]
..and IE

**Comment by systemcatch** [comment]
@corradio you could use validation.py here if you just need to check for None, https://github.com/tmrowco/electricitymap/blob/master/parsers/lib/validation.py#L81.

**Comment by maxbellec** [comment]
@corradio good question. Currently, it invalidates the whole series, which does not really make sense. If you agree, I'll change so that it only removes invalid points, and that in warns (in the public logger) about them.

**Comment by corradio** [comment]
I think that's good idea! It should probably log an exception for each data point invalid, but not invalidate the series.
Furthermore, we should decide on where to put the code that calls validation.py to check for relevant data. Should it be in the parser, or in quality.py?
I think we should put it in the parser to keep decentralised.
