### ISSUE TITLE
Namibia parser should read out data timestamp

### ISSUE THREAD

**Issue by jarek** [tmrowco/electricitymap#1285]
Current time in Namibia is 2 April 14:41 but the [Nampower dashboard](http://www.nampower.com.na/Scada.aspx) is stuck on 1 April 11:45:40.

Timestamp of the data is available in http://www.nampower.com.na/gis/images/File_Info.png

We could OCR that file. A quick attempt using the current tesseract methods and upscaling from 600x20 to 1200x40 seems to have worked alright, I got `SCADA File Dene: 01/04/2018 11:45:40` (it should have been "File Date" but otherwise correct). There is always the danger of OCR misreading, so maybe only ignore the datapoint if the timestamp can be read and is too far in the past.

Screenshot from our page:
![na](https://user-images.githubusercontent.com/47415/38196680-b4fa6000-3684-11e8-95a4-9c03b6a19576.png)

**Comment by systemcatch** [comment]
That's annoying, similar issue with the SG solar ocr stalling but still returning data that was accepted. I think I tried to do something with the timestamp but never got it to read properly.
