### ISSUE TITLE
IN-GJ (Gujarat) parser needs improvement

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap#1298]
I was about to add capacity data to **IN-GJ** and looked up the data source from the parser for conventional generation.
https://www.sldcguj.com/RealTimeData/RealTimeDemand.php
It also has capacity data for the units of the power plants.

1. While cross checking with the map, I found it highly confusing that "Gujarat Total Conventional Generation" on that site (about 8500 MW) was above the total value for all combined types in the origin graph.

![image](https://user-images.githubusercontent.com/25743609/38413298-8d85219a-398b-11e8-9d29-188c72442993.png)

2. GMR is mapped to wind, but should be something thermal PP as well (I suggest to "unknown" - the wind numbers are in a seperate figure).

3. CGPL is mapped to coal, with a current generation of 2530 MW, which is totally missing on the map.
I assume the two spaces "  " behind "CGPL  " may cause this trouble.
This is a huge amount that is missing in the "coal" category and would fill up a large part of the gap.

4. The "unknown" category could be filled with what is mapped as "thermal" in the parser. That figure is definitely missing on the map. (~2800 MW)

5. Here is a screenshot of the recent mapping. I colored the fields according to their recent mapping. I also edited the fields with "123 + 456" to be the sum of both (generating units)

![image](https://user-images.githubusercontent.com/25743609/38414879-0ac87d1a-3990-11e8-9521-d519b4ef59cd.png)

**Comment by alixunderplatz** [comment]
I had confused something in the previous comment and fixed it ;-)
Now the issue is described correctly

**Comment by alixunderplatz** [comment]
Some more infos on the grey "unknown" thermal types in the image above.
This site was very in helpful: https://en.wikipedia.org/wiki/Category:Coal-fired_power_stations_in_Gujarat

[Ukai](https://en.wikipedia.org/wiki/Ukai_Thermal_Power_Station): coal
[Wanakabori](https://en.wikipedia.org/wiki/Wanakbori_Thermal_Power_Station): coal
[Ghandiagar](https://en.wikipedia.org/wiki/Gandhinagar_Thermal_Power_Station): coal
[Sikka](https://en.wikipedia.org/wiki/Sikka_Thermal_Power_Station): coal
[KLTPS (= Kutch LTPS)](https://en.wikipedia.org/wiki/Kutch_Thermal_Power_Station): coal (for future reference: lignite)
[SLPP (=Surat LPP)](https://en.wikipedia.org/wiki/Surat_Thermal_Power_Station): coal (lignite)
[Akrimota](https://en.wikipedia.org/wiki/Akrimota_Thermal_Power_Station): coal (lignite)

[JHANOR](https://en.wikipedia.org/wiki/Jhanor-Gandhar_Thermal_Power_Station): gas

I assume this strange "GMR" with 685 MW installed power is contracted and located outside of gujarat in the state Chhattisgarh. There is[ a coal power plant with 2x 685 MW](http://gmrgroup.in/energy-gmr-chhattisgarh-power-project.aspx), which might have sold a part of its output to Gujarat, according to [this news article: "State electricity department officials told FE that GMR Chattisgarh offered to sell power to the state under the ‘flexible utilisation of coal’ scheme. "](http://www.financialexpress.com/industry/gujarats-tender-gets-dismal-response/893920/)
So GMR can be dismissed, as it is most likely not located in GJ, and removed from "wind".

Everything is clear now, so the [parser](https://github.com/tmrowco/electricitymap/blob/master/parsers/IN_GJ.py) can be updated / improved.

**Comment by alixunderplatz** [comment]
I can't test locally, so can someone try and see if the updated mapping below for [IN_GJ.py](https://github.com/tmrowco/electricitymap/blob/master/parsers/IN_GJ.py) still works? 😸
Would be nice to check if every single value is really grabbed, because sometimes one or even two " " spaces are behind the names of the power plants. Plenty of coal should be returned now.
I deleted "wind" and "thermal" from that mapping, so probably "thermal_value" must be deleted as well from the rest of the parser?! You'll figure it out 😆 

```
station_map = {
     "coal": ["Ukai(3-5)+Ukai6",
             "Wanakbori",
             "Gandhinagar",
             "Sikka(3-4)",
             "KLTPS(1-3)+KLTPS4",
             "SLPP(I+II)",
             "Akrimota",
             "TPAECo  ",
             "EPGL(I+II)",
             "Adani(I+II+III)",
             "BECL(I+II)",
             "CGPL "],
    "hydro": ["Ukai  (Hydro)",
              "Kadana (Hydro)",
              "SSP(RBPH)"],
    "gas": ["Utran(Gas)(II)",
            "Dhuvaran (Gas)(I)+(II)",
            "GIPCL(I)",
            "GIPCL(II)",
            "GSEG(I+II)",
            "GPPC",
            "CLPI",
            "KAWAS",
            "Sugen+ Unosgn",
            "JHANOR"],
    "nuclear": ["KAPP"]   
}
```

**Comment by systemcatch** [comment]
When running with the new station map I get the following;
```
(EM-env) chris@ThinkPad:~/electricitymap$ python -m parsers.IN_GJ
Unknown fuel for station name: Ukai  (Hydro)
Unknown fuel for station name: TPAECo
solar returned -1.00, setting to None
{'zoneKey': 'IN-GJ', 'production': {'biomass': None, 'solar': None, 'nuclear': None, 'hydro': 52.0, 'unknown': 438.0, 'coal': 3746.0, 'oil': None, 'gas': 1575.0, 'geothermal': None, 'wind': 1625.0}, 'source': 'sldcguj.com', 'storage': {'hydro': None}, 'datetime': datetime.datetime(2018, 4, 11, 21, 39, 50, tzinfo=tzfile('/usr/share/zoneinfo/Asia/Kolkata'))}
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/chris/electricitymap/parsers/IN_GJ.py", line 172, in <module>
    print(fetch_consumption('IN-GJ', session))
  File "/home/chris/electricitymap/parsers/IN_GJ.py", line 157, in fetch_consumption
    value_map = fetch_data(zone_key, session)
  File "/home/chris/electricitymap/parsers/IN_GJ.py", line 99, in fetch_data
    logger.warning('Unknown fuel for station name: {}'.format(v1),
AttributeError: 'NoneType' object has no attribute 'warning'
```

However that error is nothing to do with the station mapping, on L157 fetch_data is called without a logger argument which results in logger=None. Fixing that I get the following;
```
(EM-env) chris@ThinkPad:~/electricitymap$ python -m parsers.IN_GJ
Unknown fuel for station name: Ukai  (Hydro)
Unknown fuel for station name: TPAECo
solar returned -1.00, setting to None
{'source': 'sldcguj.com', 'production': {'biomass': None, 'wind': 1582.0, 'hydro': 52.0, 'unknown': 436.0, 'gas': 1567.0, 'geothermal': None, 'coal': 3738.0, 'oil': None, 'nuclear': None, 'solar': None}, 'zoneKey': 'IN-GJ', 'storage': {'hydro': None}, 'datetime': datetime.datetime(2018, 4, 11, 21, 48, 50, tzinfo=tzfile('/usr/share/zoneinfo/Asia/Kolkata'))}
Unknown fuel for station name: Ukai  (Hydro)
Unknown fuel for station name: TPAECo
{'consumption': 14112.0, 'zoneKey': 'IN-GJ', 'datetime': datetime.datetime(2018, 4, 11, 21, 48, 50, tzinfo=tzfile('/usr/share/zoneinfo/Asia/Kolkata')), 'source': 'sldcguj.com'}
```

Some of the plants aren't matching due to whitespace issues as you said before, we'll need string manipulation or regex to fix that.

**Comment by alixunderplatz** [comment]
@systemcatch thank you for checking! 😃👍
Looks like around 2 GW of generation go missing in the total sum.
Your values are 7.3 GW in total. When I take a recent snapshot (~1 hour later), I get 9.5 GW total generation.
