### ISSUE TITLE
Extract left panel text into onboarding modal

### ISSUE THREAD

**Issue by jbuverud** [tmrowco/electricitymap#1301]
The top part of the current left panel should be extracted into its own separate onboarding modal, shown to users on first page load. 

![image](https://user-images.githubusercontent.com/7040743/38422005-77b68098-39a9-11e8-8f73-4b53539fd270.png)

We should also find space for an icon somewhere allowing the users to re-open the modal if they want to see it again.

**Comment by brunolajoie** [comment]
This will require to refine table subtitle to
> Ranked by carbon intensity of electricity consumed (gCO2eq/kWh)
