### ISSUE TITLE
Use country specific emission factors for coal power in Turkey

### ISSUE THREAD

**Issue by jzlcdh** [tmrowco/electricitymap#1309]
Given that https://ytbs.teias.gov.tr/ytbs/frm_login.jsf shows that lignite is a big source in Turkey and table 6 in https://ac.els-cdn.com/S095965261400763X/1-s2.0-S095965261400763X-main.pdf?_tid=f66ddfbd-ec54-4e6a-af7e-a7c850cdf4ee&acdnat=1523111824_0d6a96800cdb45e017b65e23fa5e7eb0 shows different emission factors would it be a good idea to show it separately?

If so is it reasonably easy to do?

And if so should I use the emissions factors in the link above or "However, hard coal is significantly worse than any other option,
with an estimate of 1126 g CO2-eq./kWh, followed by lignite with
1062 g CO2-eq./kWh and gas with less than half of that (499 g CO2-
eq./kWh)." as stated in https://ac.els-cdn.com/S030142151630091X/1-s2.0-S030142151630091X-main.pdf?_tid=9a4c8df0-0187-459f-9eff-83bf1f4fc6f3&acdnat=1523116248_98bbdc6d0a6e4931b4274f05b8ed5fd7

In case some people do not know what lignite is perhaps it should be labelled as "lignite coal" as opposed to "hard coal". By the way "ithal kömür" is also "hard coal" like "taş kömür".

**Comment by jzlcdh** [comment]
Hi @systemcatch, thanks for your quick reply. Thinking about this more I am somewhat confused why my above quote says that our hard coal power stations emit more CO2 than our lignite ones. Perhaps there are a lot of country specific factors. So as we are not splitting lignite out for now do you think all Turkish coal power should be rated at 1060? My programming is very rusty but I could probably figure out how to make that change.

**Comment by systemcatch** [comment]
That's not something I can really comment on. We have used specific factors for country generation before (e.g. Estonian Shale Oil) but I don't know if this would mess up the backend coal calculations. @brunolajoie what do you think?

I tried accessing your links but something is wrong with them, they return a github 404. The emission factors are set in https://github.com/tmrowco/electricitymap/blob/master/config/co2eq_parameters.js

**Comment by jzlcdh** [comment]
Hi @systemcatch. Thanks for fixing the link. I just realised why the hard coal burnt here emits more than lignite: the hard coal is almost all imported so the paper linked to must be taking the emissions from the ships into account. As far as I can see the paper does not include error bars but even so I think we must be well above the default 820 in the parameter file.

Unless anyone can see any backend complications please could you assign this to me to do as that parameters file looks straightforward - although I may not have time for a few weeks. If I have any problems making the change I will ask your advice.

**Comment by systemcatch** [comment]
Right side of page under "Assignees", click "assign yourself" or select from the list of people.

**Comment by jzlcdh** [comment]
@systemcatch  Although I am signed in and can see the word "Assignees" there is no list of people and nothing to click. Perhaps I don't have the power to do that.

**Comment by corradio** [comment]
@brunolajoie any idea whether or not this is a good idea to do? I might be worried that if we start doing country specific intensities it becomes hard to compare between countries.

**Comment by jzlcdh** [comment]
As I understand it Estonian oil already has a country specific intensity. So perhaps you could either remove that or remove the question label from this issue?

**Comment by corradio** [comment]
@jzlcdh this is a very relevant question, so I think the label should be kept :)
I'm merely thinking of whether or not this is included in #162, and whether or not we have a more general solution.

**Comment by jzlcdh** [comment]
@corradio Ah sorry I didn't mean to denigrate your question. I think this should remain separate from  #162 as in practice with the uncertainties it seems that hard coal burnt in Turkey emits at similar intensity to Turkish lignite. This is because of the transport costs of hard coal.

**Comment by corradio** [comment]
ok makes sense. Don't worry no offense was taken :)

**Comment by brunolajoie** [comment]
I'll give you my 2cents point of view
- The less we enter into country-specific emission factor the better, except if all these factors are derived from the same scientific study/database, in order to be comparable. I'm in touch with someone that could help us do that but it takes time #738 
- Estonia is different, in that the fuel they burn is not "oil" at all. it's a solid fuel, called oil shale, that has nothing to do with the American shale oil being produced with hydro fracking for instance. (To be strict, we should revert back Norway specific hydro to the IPCC hydro because...it's really hydro "fuel")
- For Turkey, this issue should not be solved by changing the emission factor of TK coal, but by splitting hard coal from lignite in the EMap system #162 

Therefore, it feel it is not a priority to update TK coal specific emission factor unfortunately.

**Comment by jzlcdh** [comment]
OK thanks I was not aware of #738. I think I should either close this in favour of that or if that is going to take a long time make this change as a stopgap. Because also this raises the general question of whether fuel transport related emissions are included or not. Of which question I don't have an answer.

**Comment by corradio** [comment]
I am going to close this as #738 will take over.
To answer your question, the factors we use are LCA from the IPCC, so they should take into accounting fuel transport related emissions. Of course, as those are global averages, the precision is limited, hence why #738 might help there.
Thanks for raising this @jzlcdh .
