### ISSUE TITLE
relax restrictions on Austria

### ISSUE THREAD

**Issue by jarek** [tmrowco/electricitymap#1313]
from Kibana: `invalid point: {'zoneKey': 'AT', 'datetime': datetime.datetime(2018, 4, 8, 17, 45, tzinfo=tzutc()), 'production': {'biomass': None, 'coal': None, 'gas': None, 'hydro': None, 'nuclear': None, 'oil': None, 'solar': 55.0, 'wind': 2255.0, 'geothermal': None, 'unknown': None}, 'storage': {'hydro': None}, 'source': 'entsoe.eu', 'schemaVersion': 1}, reason:Coal or oil or unknown production value is required for AT`

We should probably add gas and maybe biomass to the list of "one of required" sources.

Current data:
![at](https://user-images.githubusercontent.com/47415/38471268-f9980f2a-3b6e-11e8-8c51-dc2fae38c1e6.png)

Note that the current data is _only_ accepted by the validator because of tiny 22 MW worth of "unknown" production. If that drops off, we'll be dropping the entire datapoint. However, considering the last 24 hours of history, it seems likely that coal and oil being 0 MW right now is valid:
![at_history](https://user-images.githubusercontent.com/47415/38471355-46e7f2f8-3b70-11e8-8add-d1709b7c5e77.png)

**Comment by corradio** [comment]
@systemcatch @jarek anything we should change here? Feel free to update validation conditions on the ENTSOE parser or in quality.py. Else, let's close the issue

**Comment by systemcatch** [comment]
@corradio yes can you update https://github.com/tmrowco/electricitymap/blob/master/parsers/lib/quality.py#L66 to the following so the error message is correct.

```"Coal, oil, gas or unknown production value is required for"```
