### ISSUE TITLE
Improve developer documentation

### ISSUE THREAD

**Issue by systemcatch** [tmrowco/electricitymap#1322]
Few points to start with, feel free to add more.

- Getting nodejs installed and working correctly. :sob: 
- Installing python 3, Windows does not ship with it by default I think.
- Can topogen.sh be run on powershell or does it require bash for Windows?

**Comment by corradio** [comment]
In principle that's why all of this should be done inside Docker. It simplifies things quite significantly! Although Docker can be a bit annoying to install..

**Comment by jbuverud** [comment]
We could add something about docker's system requirements. It only runs on certain versions of windows 10 (does not run on Home editions, for instance). I had to resort to running it through a VM install on my laptop.

**Comment by systemcatch** [comment]
@corradio That was my idea initially but afaik docker only works when building the map. To add new geometries you have to have a working node install.

Yes it would be nice to add something about using docker on windows. I know @alixunderplatz is currently trying to get the map built on his Windows machine but is having difficulties.

**Comment by corradio** [comment]
Actually I think we made the changes required to be able to do all the
mapping inside the container.
It's not really documented though.

**Comment by systemcatch** [comment]
@corradio if you can give me a rough guide to mapping in the container I will add a more polished version to the docs.

**Comment by corradio** [comment]
I think it's as simple as `docker-compose run --rm web ./topogen.sh` but haven't tried it

**Comment by corradio** [comment]
@systemcatch did it work?

**Comment by systemcatch** [comment]
Running it on my machine worked. To be sure we'd need to run this on a fresh VM but it's a good sign. @jbuverud fancy having a go?
```
(EM-env) chris@ThinkPad:~/electricitymap$ docker-compose run --rm web ./topogen.sh
Starting electricitymap_mockserver_1 ... 
Starting electricitymap_mockserver_1 ... done
Downloading ne_10m_admin_0_map_subunits.zip
Warning: Illegal date format for -z, --timecond (and not a file name). 
Warning: Disabling time condition. See curl_getdate(3) for valid date syntax.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5324k  100 5324k    0     0   157k      0  0:00:33  0:00:33 --:--:--    92
Archive:  build/ne_10m_admin_0_map_subunits.zip
  inflating: build/ne_10m_admin_0_map_subunits.README.html  
 extracting: build/ne_10m_admin_0_map_subunits.VERSION.txt  
 extracting: build/ne_10m_admin_0_map_subunits.cpg  
  inflating: build/ne_10m_admin_0_map_subunits.dbf  
  inflating: build/ne_10m_admin_0_map_subunits.prj  
  inflating: build/ne_10m_admin_0_map_subunits.shp  
  inflating: build/ne_10m_admin_0_map_subunits.shx  
Downloading ne_10m_admin_1_states_provinces_lakes.zip
Warning: Illegal date format for -z, --timecond (and not a file name). 
Warning: Disabling time condition. See curl_getdate(3) for valid date syntax.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13.6M  100 13.6M    0     0   241k      0  0:00:58  0:00:58 --:--:--  245k
Archive:  build/ne_10m_admin_1_states_provinces_lakes.zip
  inflating: build/ne_10m_admin_1_states_provinces_lakes.README.html  
 extracting: build/ne_10m_admin_1_states_provinces_lakes.VERSION.txt  
 extracting: build/ne_10m_admin_1_states_provinces_lakes.cpg  
  inflating: build/ne_10m_admin_1_states_provinces_lakes.dbf  
  inflating: build/ne_10m_admin_1_states_provinces_lakes.prj  
  inflating: build/ne_10m_admin_1_states_provinces_lakes.shp  
  inflating: build/ne_10m_admin_1_states_provinces_lakes.shx  
Extract metadata
Parsing countries..
Parsing states..
Parsing 3rd party..
Done

```

**Comment by corradio** [comment]
@systemcatch seems clean. Fancy doing a PR to update the doc and close this issue?
