### ISSUE TITLE
Chile SING - solar PV generation at night

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap#1327]
Chile SING has been showing around 77 MW of solar generation at night.

![image](https://user-images.githubusercontent.com/25743609/38661949-f15ee1b4-3e32-11e8-9bd6-3bc903b60510.png)

This is due to faulty values of "Maria Elena FV" and "Solar Jama 2".
https://sger.coordinador.cl/Charts/GenCentral

Not sure how long this problem exists / will exist, but maybe they could be excluded from the mapping.
Would it make sense to raise a warning when the output remains constant over longer periods?

![image](https://user-images.githubusercontent.com/25743609/38662034-3d56f250-3e33-11e8-8688-d47c7fbd3c8f.png)

![image](https://user-images.githubusercontent.com/25743609/38662046-4b965f2c-3e33-11e8-8ea7-6d963e5fa837.png)

**Comment by systemcatch** [comment]
Maria Elena FV is a concentrating solar plant (see https://en.wikipedia.org/wiki/Mar%C3%ADa_Elena_Solar_Power_Plant), could this "solar at night" be due to stored energy feeding into the grid?

**Comment by alixunderplatz** [comment]
@systemcatch good point. I was assuming it is PV because of the "FV" behind the plant. I think the red lines in the graphs above are a forecast of the generation, so I'd assume no energy is released at night. In addition, the generation value is totally constant and seems stuck.

In the map it says "Fotovoltaica" for Maria Elena, too, with 68 MW installed cap. Same for Solar Jama.  https://sger.coordinador.cl/Plants/Map

**Comment by alixunderplatz** [comment]
Seems like the CSP plant in that area is coming online in June 2018 ;)
https://www.nrel.gov/csp/solarpaces/project_detail.cfm/projectID=3275

**Comment by systemcatch** [comment]
I think the generation value is stuck and we should either disable those plants or make a function that checks the local time in Chile and drops any solar generation between 10pm-6am.

**Comment by alixunderplatz** [comment]
The extent of this issue has been reduced to only one solar PV plant stuck at reporting 18 MW.
Hope they'll fix that one soon, too.

![image](https://user-images.githubusercontent.com/25743609/38981312-5bdc4d4c-43bf-11e8-89d9-f56037dfd489.png)

**Comment by systemcatch** [comment]
I don't see the other plant reporting solar at night anymore, @alixunderplatz feel free to close this if you agree.
