### ISSUE TITLE
Descriptive zone names

### ISSUE THREAD

**Issue by jarek** [tmrowco/electricitymap#1341]
I really like how subregions with definite names are rendered in the new list:

![image](https://user-images.githubusercontent.com/47415/38952126-e1f85170-434a-11e8-996e-3e360fcbbdf3.png)

but I'm not so keen on those with descriptive names:

![image](https://user-images.githubusercontent.com/47415/38951824-104f5c04-434a-11e8-8e8e-d86a5c40c11b.png)

It's a bit hard to explain what seems wrong about those, but I think my main complaint is that these names don't stand on their own. For cases like Yukon and El Hierro the small-text is mostly only used to inform users who might not know where Yukon is, or which La Palma is meant. However "West" doesn't mean anything on its own, and one _needs_ either the smaller text or the flag (which people might not know).

Suggested guideline: if it wouldn't be the title of the region's Wikipedia article (as is the case with for example [North Island](https://en.wikipedia.org/wiki/North_Island)), don't use it as the main name of the zone.

Currently affected are:
- Denmark East/West
- Brazil zones
- Malaysia

Suggested solution: rename to "West Denmark", "Brazil North-East", "Peninsular Malaysia", or similar. Better yet if we could have their proper local names - though admittedly electrical subdivisions might not have names that ordinary people know.

While we're at it I would also flip the order in the "full name" displayed in the detail view, so that it's "California (United States)" and not "United States (California)".

I'm writing because this has been bugging me a bit, but this is only my opinion. Does anyone else have thoughts about this?

**Comment by jbuverud** [comment]
I agree both with the issue and with your proposed solution 👍  It makes sense for the area names to be unique and self-descriptive for people with the local knowledge. 

I also agree that the area details view header needs to be updated with similar styling to that in the list. Both with regards to the main title/subtitle division, but also with regards to the size of the flag. But this redesign should definitely be a separate issue.

**Comment by brunolajoie** [comment]
It's a good idea to have self-descriptive area names indeed, but i'd keep the same ordering btw subzone and zone. Like, for instance:
- California (Unitest States of America)
- West Denmark (Denmark)
- North-East Brazil (Brazil)
- Peninsular Malaysia (Malaysia)

What dyou think?

**Comment by jbuverud** [comment]
I think that was exactly what @jarek was proposing :smile:

**Comment by corradio** [comment]
@jbuverud do you have an ideas as to how to fix? Currently you do some pattern matching based on parenthesis right?
As I see it we need to add new fields in translations (country name in addition to zone name). That would enable us to have:
- Country name: Denmark, Zone name: West Denmark
- Country name: USA, Zone name: SPP
- ...
and if no country name is used we just display the full zone name.

**Comment by systemcatch** [comment]
I fully agree with the proposed solution. One other small thing, some of the subzone & zone names are quite long which is fine for the list but makes the hover boxes look a bit skewed. We might want to split the longer names onto separate lines to make it more readable. 

![long_box](https://user-images.githubusercontent.com/30196510/38982722-7eaec0a2-43ba-11e8-992f-e3c77866b920.png)

**Comment by jarek** [comment]
With the following renames we could do this without changes to rendering code:

* "Denmark (West)" renamed to "West Denmark"
* "Denmark (East)" renamed to "East Denmark"
* "Malaysia (Peninsula)" renamed to "Peninsular Malaysia"
* "Brazil (North-East)" renamed to "North-East Brazil"
* other Brazil zones renamed the same way

Developer console mock-ups:

![image](https://user-images.githubusercontent.com/47415/38992483-2e01b55c-43e1-11e8-9eca-9bf5c8ec71a5.png)

![image](https://user-images.githubusercontent.com/47415/38992528-50276ece-43e1-11e8-9b42-79b8b568f615.png)

![image](https://user-images.githubusercontent.com/47415/38992670-bf4f80f2-43e1-11e8-8437-871dfadb0417.png)

![image](https://user-images.githubusercontent.com/47415/38992755-fce8c540-43e1-11e8-8ed6-1427f55cdfba.png)

![image](https://user-images.githubusercontent.com/47415/38992695-cb671a4e-43e1-11e8-8ce9-e440a69bbb84.png)

**Comment by jarek** [comment]
Or, following Bruno's suggestion:

![image](https://user-images.githubusercontent.com/47415/38993024-ba51bcd6-43e2-11e8-8691-7f5b71b5384a.png)

Also I would just replace "United States of America" with "United States" or "USA", at least in the English version.
