### ISSUE TITLE
Map Uruguay's "unknown" to "oil"

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap#1342]
For Uruguay, everything that is reported as "thermal" is currently assigned to "unknown" category.

![image](https://user-images.githubusercontent.com/25743609/38982325-daec3ee2-43c1-11e8-96e9-16fb636deb55.png)

**There are some hints this is entirely based on "oil" as fuel.**

1. the IEA yearly reports show oil as only possible source for "thermal" https://www.iea.org/statistics/statisticssearch/report/?country=Russia&product=electricityandheat

2. Based on the "list of power stations" https://en.wikipedia.org/wiki/List_of_power_stations_in_Uruguay,
I found info in 3.

3. going through the list, I always ended up on http://globalenergyobservatory.org/, reporting "fuel oil" or "distillate oil" as primary fuel:
3.1 http://globalenergyobservatory.org/geoid/42286
3.2 http://globalenergyobservatory.org/geoid/42287
3.3 http://globalenergyobservatory.org/geoid/42290
3.4 http://globalenergyobservatory.org/geoid/42291

If that's enough evidence, let's change it in the parser! 😃

**Comment by brunolajoie** [comment]
You're right, that's more than enough :)
