### ISSUE TITLE
add PJM load forecast

### ISSUE THREAD

**Issue by maxbellec** [tmrowco/electricitymap#1345]
Data available here : http://www.pjm.com/markets-and-operations/energy/real-time/7-day-load-forecast.aspx

**Comment by lorrieq** [comment]
Can you assign me to this if nobody else has started?

**Comment by corradio** [comment]
I don't think I can assign to people that are not members of the project.
But I think it's enough if you say you'll be working on it!
Thank you so much @lorrieq !
