### ISSUE TITLE
Spain IB Menorca is not conected to mallorca

### ISSUE THREAD

**Issue by kikebie** [tmrowco/electricitymap#1346]
Menorca Island has been lost the connection with mallorca last year.

**Comment by alixunderplatz** [comment]
@kikebie Thanks for the info! 

Seems like something broke and has to be replaced, which could take some time:
https://www.energynews.es/en/government-to-accelerate-processing-of-new-electric-cable-between-mallorca-and-menorca/

https://menorca.info/menorca/local/2017/619221/red-electrica-descarta-reparar-cable-aboca-menorca-aislamiento-electrico.html

**Comment by corradio** [comment]
I'm not sure I understand what is to be done here?

**Comment by alixunderplatz** [comment]
@corradio this will be solved by splitting Balearic islands #1347. 
The cable between Mallorca and Menorca was damaged and has to be replaced. Menorca's grid is an *electrical island* at the moment.

**Comment by jarek** [comment]
I will close this in favour of #1347
