### ISSUE TITLE
Mobile layout on info screen

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#1348]
![image](https://user-images.githubusercontent.com/1655848/39150082-77619dc6-4741-11e8-9b8a-d5b74b147d33.png)

The layout of the bottom icons seems a bit messy.

**Comment by jbuverud** [comment]
Do you have any thoughts for improving it? It's not a bug - it's just my best compromise of fitting all the icons. Maybe the tomorrow logo could be be left aligned, but then it would have to be spaced a bit further down from the other elements to separate it, I think. Suggestions are very welcome :slightly_smiling_face:

**Comment by corradio** [comment]
I think simply adding a bit of vertical space and centering the block could suffice.

**Comment by corradio** [comment]
FYI:

![image](https://user-images.githubusercontent.com/1655848/39227624-ee32817c-4859-11e8-8c75-0b2e30a12a0e.png)

A goal is share, tweet, like or follow

**Comment by jbuverud** [comment]
> I think simply adding a bit of vertical space and centering the block could suffice.

Will do!

> Also, I noticed the share/slack/tweet block was removed from the left panel and the list view. Can we bring it back? 

I'm not sure why you're saying it's removed from the left panel - I didn't remove it, and both on production and locally I still see it there. 😕 

>  I'm fine removing it on the list view on mobile, but for the others (including country view on mobile) it's quite important.

I'll add it for the country view on mobile. I definitely see the importance, given the stats you posted 🙂 

Also, don't those stats kind of argue for us keeping the tomorrow logo overlaid onto the map on mobile (even though it increases clutter)? Can we see in the stats whether those goal completions are from mobile or web?

**Comment by jbuverud** [comment]
> Also, I noticed the share/slack/tweet block was removed from the left panel and the list view. Can we bring it back?

Ah, just a thought - when you say "left panel", perhaps you mean the country details view?  Then it makes more sense. Do you want me to add it to the country details view on desktop as well as on mobile?
