### ISSUE TITLE
Add Feature / Croatia

### ISSUE THREAD

**Issue by ThierryOllivero** [tmrowco/electricitymap#135]
ENTSO or HOPS (when they will have fixed their website) https://www.hops.hr

**Comment by ivanszekeres** [comment]
What is an issue with Croatia? Maybe I can help with data?

**Comment by corradio** [comment]
We are lacking data with Croatia. @ivanszekeres can you help?

**Comment by ivanszekeres** [comment]
I joined your channel on Slack with the same question, can you PM me on Slack which data you need so I can research it?

**Comment by corradio** [comment]
Let's re-open this issue as soon as we have a lead for Croatia
