### ISSUE TITLE
Costa Rica has a new generation type and gives too many warnings

### ISSUE THREAD

**Issue by systemcatch** [tmrowco/electricitymap#1354]
There seems to be a new generation type for Costa Rica that is causing a warning.

https://kibana.electricitymap.org/app/kibana#/doc/93e631f0-245f-11e8-a779-9d01de8d7a71/logstash-2018.04.28/doc?id=N-7nDGMBoL7AEh1EXs9P&_g=()

```unknown is not mapped to generation type```

However looking at the logs for the past week [here](https://kibana.electricitymap.org/app/kibana#/discover/1710fdd0-2460-11e8-a779-9d01de8d7a71?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now%2Fw,mode:quick,to:now%2Fw))&_a=(columns:!(level,extra.key,message),filters:!(('$state':(store:appState),exists:(field:level),meta:(alias:!n,disabled:!f,index:'93e631f0-245f-11e8-a779-9d01de8d7a71',key:level,negate:!f,type:exists,value:exists)),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'93e631f0-245f-11e8-a779-9d01de8d7a71',key:level,negate:!t,params:(query:INFO,type:phrase),type:phrase,value:INFO),query:(match:(level:(query:INFO,type:phrase))))),index:'93e631f0-245f-11e8-a779-9d01de8d7a71',interval:auto,query:(language:lucene,query:CR),sort:!('@timestamp',desc))) the warning happens multiple times on one run. If I remember rightly the parser gets data for each hour available, we should alter it to only warn once per run to reduce clutter.

**Comment by alixunderplatz** [comment]
Comparing the plant mapping in the parser to the table on the website, "Los Negros II" is the only missing unit I could find. It's "[a hydro power plant](http://www.carboncr.com/proyectos/costa-rica/negros-ii)" and was added to the table on 23rd and started reporting generation on 25th April.
