### ISSUE TITLE
New way of navigating time in mobile zone details view 

### ISSUE THREAD

**Issue by jbuverud** [tmrowco/electricitymap#1374]
Going "back in time" in the zone details view on mobile does currently not work very well. We should think of some alternative solutions.

One idea is to have a touch-friendly slider which controls the time, shown together with the zone name and back button in a fixed header. Something like this (but prettier of course): 

![image](https://user-images.githubusercontent.com/7040743/39518956-24a8f9ba-4e05-11e8-8219-4ccf25f498de.png)

I think this slider might require some kind of explanatory header, though, and I don't really see any room for it. Maybe the timestamp text (including the date) could be the header, and we could remove the time 'ticks', but I'm not sure how to make it intuitive that changing the slider also changes the time.

Thoughts? @corradio ? @ovbm ? Should I continue working on a slider like this, or should we explore other solutions?

**Comment by corradio** [comment]
I like it! Maybe the header should encompass the gauges? The the swipe up/down can focus on the graph.

**Comment by corradio** [comment]
- Margin on tooltips
- Close button on tooltips
- Tapping graphs shouldn't change time (only slider does that)

**Comment by brunolajoie** [comment]
@jbuverud don't foreget to close the issue (it will move to "Done" automatically on the boards)
