### ISSUE TITLE
Change data source for UK-GB (5-min data)

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap#1376]
I've seen this happen frequently in the last weeks: the wind energy production on ENTSO-E for the UK would drop and leave a very spiky and obviously wrong graph for the UK-GB zone.

![image](https://user-images.githubusercontent.com/25743609/39520683-e3e0788e-4e0b-11e8-8a36-370ec84be0a7.png)

This issue got much worse in the last three days. Here is what it looked like for 1st of May [on ENTSO-E](https://transparency.entsoe.eu/generation/r2/actualGenerationPerProductionType/show?name=&defaultValue=false&viewType=GRAPH&areaType=BZN&atch=false&datepicker-day-offset-select-dv-date-from_input=D&dateTime.dateTime=01.05.2018+00:00|CET|DAYTIMERANGE&dateTime.endDateTime=01.05.2018+00:00|CET|DAYTIMERANGE&area.values=CTY|GB!BZN|10YGB----------A&productionType.values=B17&productionType.values=B18&productionType.values=B19&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)):

![image](https://user-images.githubusercontent.com/25743609/39520636-bbc15ea4-4e0b-11e8-8670-fbe0f6450a43.png)

Offshore generation would almost completely disappear and onshore wind would drop by 30-40%.

Other sources, like these dashboards don't seem to be affected by that data quality issue.: 
http://electricinsights.co.uk/#/dashboard?&_k=dxtgvl 
http://gridwatch.co.uk/
http://grid.iamkate.com/

So maybe it's time to switch to data from ELEXON, which have a super short reporting interval of 5 minutes for both generation and all exchanges. Seems like there is a delay of 1 hour:

https://www.bmreports.com/bmrs/?q=generation/fueltype

![image](https://user-images.githubusercontent.com/25743609/39522025-3fa9305c-4e11-11e8-994b-e66d7465e0fe.png)

Check out the XML and CSV links on the site that'll lead you to the data.
Historical data available, too!

**Comment by lorrieq** [comment]
ELEXON is great! I have dealt with this source in my day job. Let me know where I can help out.

**Comment by brunolajoie** [comment]
Yeah, true, the closer to the source is always the best...! and GB is soon going to able to be broken down by DSO's regions in National Grid / Elexon systems apparently. Is there also a 1h delay is their API?

**Comment by systemcatch** [comment]
We should collect this source in addition to entsoe, there may be some interesting differences. The xml looks like a better choice as the csv data doesn't have column headers?

**Comment by corradio** [comment]
CSV will be easier to parse though, so I'd suggest going the CSV way.

**Comment by lorrieq** [comment]
I'm going to code this up this evening, if nobody else has started.
I far prefer parsing CSVs. The only thing to note is you are relying on the fuel column order outlined in the documentation being and staying correct as well as applying small edits when new fuels are added. Not sure if this will happen again but I recall Biomass was split out of one of the other fuel types around November '17.

**Comment by systemcatch** [comment]
@lorrieq we could check the number of columns in the csv and log a warning if it's changed from the current number.

**Comment by lorrieq** [comment]
Hey all, I'm almost ready to submit an initial PR for this but wanted to check a few things.

1) To confirm, the datetimes in the parsers output should be in UTC right?

2) The datetime for each observation. Should this be the published time minus 5 minutes? In the example, the first observation for SP 28 which is 12:30GMT has a published time of 12:35GMT. My interpretation is the parser give this observation a datetime of 12:30GMT, the observation with 12:40GMT publish time should have a datetime of 12:35GMT and so on.

3) The exchanges. I don't think there is any way to tell the netFlow, there is no reference to the direction of flow, just a total MW value which probably is an aggregation of import/export?

4) How are we dealing with multiple parsers per zone? I don't see any examples of this to date. Maybe allow the parsers dictionary values map to a list (as shown in image) rather than single string at the moment? I presume this would need some change to the backend code.
<img width="508" alt="screen shot 2018-05-06 at 15 02 15" src="https://user-images.githubusercontent.com/6525086/39674074-7fffd57c-513e-11e8-997e-6fe7d73c159c.png">

**Comment by systemcatch** [comment]
1. datetime object with a timezone is fine.

2. How exactly is the settlement period used?

3. The exchanges on the generation by fuel page seem to ignore negative values, but on https://www.bmreports.com/bmrs/?q=generation/avghalfhourIC they don't.

4. I think that's the way to go but @corradio is the one who will make the changes to the backend.

**Comment by corradio** [comment]
2. The `datetime` should be the time of the data point. If the measured
average production between H and H+1 is measured at time H+1, the timestamp
should be set at H (i.e. the datapoint is valid from H until a new
datapoint arrives).
3. During an interval, and for a pair of zones, the parser should return
the average flow during that interval (`netFlow`). Positive between a and b
means from a -> b, negative means from b to a.
4. We can't have multiple parsers atm. We will need to switch from ENTSOE
to ELEXON. The switch happens in config/zones.json where we simply replace
ENTSOE by ELEXON in the parsers dictionary values.

**Comment by alixunderplatz** [comment]
@lorrieq @systemcatch @corradio Hey guys, I am sorry I just noticed this now, but there seems to be no solar data on the table on the page that I linked above, is that correct?

The wind and biomass data seems to be too low as well, compared with recent data on the map.

The fossil and hydro stuff looks good and precise, though. Seems like the 5-min-data is just usable for these categories plus the interconnectors. Not for solar, wind and bio :(

This page below has solar, wind and biomass figures which look complete and valid, but just for the "old" 30-min-intervals :( 
https://www.bmreports.com/bmrs/?q=actgenration/actualaggregated

I don't understand why they would publish it in such a strange way.

ref PR #1390

**Comment by lorrieq** [comment]
Oh no, the best laid plans! I can't understand how I didn't realise there was no solar there either.

Well, if it's worth investigating I can contact them about their seemingly low reporting of wind and biomass data and if they have any plans to include solar generation there in the near future.

**Comment by brunolajoie** [comment]
Don't they have an API at Elexon/BMRS that could have potentially cleaner data?

**Comment by systemcatch** [comment]
Posting here what I said in the PR.

Most websites use https://www.solar.sheffield.ac.uk/pvlive/ for solar data. It's a fairly reliable estimate provided by the University of Sheffield at 30min intervals.

**Comment by lorrieq** [comment]
**5 minute data:**
Valid for fossil fuels and hydro [here](https://www.bmreports.com/bmrs/?q=generation/fueltype).

**30 minute data:**
Valid wind and biomass [here](https://www.bmreports.com/bmrs/?q=actgenration/actualaggregated) as @alixunderplatz pointed out.
It seems solar generation can be found [here](https://www.bmreports.com/bmrs/?q=actgenration/actualorestimated) which we didn't spot yet, but I haven't looked much into the accuracy of the data.

So acceptable data seems to be there for all, however in differing granularities.
The 5 minute wind generation values seem to be more representative of onshore wind than total wind? Maybe this is the reason for the under reporting? But then again, the values don't completely line up either.

**Comment by systemcatch** [comment]
Currently (9am) Sheffield Solar shows 5.24GW of generation while https://www.bmreports.com/bmrs/?q=actgenration/actualorestimated shows 3.67GW.

**Comment by corradio** [comment]
http://electricinsights.co.uk/ actually uses both, so I don't see why we
shouldn't.
