### ISSUE TITLE
Split NO by bidding zone

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#1381]
map data found by @tmslaine :
 
> For Norway one way to get price zones is through the NVE map service:
> For example https://temakart.nve.no/link/?link=vannkraft
> Click "Kartlag", uncheck "NVE vannkraft utbygd og ikke utbygd" and select "NVE Elspot områder" in the dropbox. Then one can draw the polygons manually on the map using the red and yellow lines as a reference and download them as ESRI shapefiles. Conversion to geojson should be simple using for example geopandas.

> English version of the NVE map services (https://www.nve.no/map-services/) notes:"NVE's geospatial data are open to the public."
> Norwegian version https://www.nve.no/karttjenester/ references the Norwegian license on open data(NLOD).
> License: https://data.norge.no/nlod/en/2.0

**Comment by kikebie** [comment]
Hello, Some Import export arrows of the new NO split are on the oposite side and one between SW NO - W NO is between other border.

**Comment by brunolajoie** [comment]
cc @maxbellec

**Comment by jarek** [comment]
Wrong exchange arrows should have been resolved in #1399 which was deployed 13 hours ago, so very shortly after @kikebie 's message. @kikebie can you see if it's all right now?

**Comment by kikebie** [comment]
Great, Now everything looks fine. Thank you,

**Comment by jarek** [comment]
OK I'll close this ticket as this has now been done! :tada:
