### ISSUE TITLE
No data country tooltip shows renewable and low-carbon percentages as "NaN %"

### ISSUE THREAD

**Issue by jarek** [tmrowco/electricitymap#1387]
[As reported on Slack](https://tmrow-team.slack.com/archives/C2DQPTHA6/p1525536723000059):

![image](https://user-images.githubusercontent.com/47415/39665378-6e1b5288-5093-11e8-9f2d-978a2befb584.png)

**Comment by corradio** [comment]
As discussed on Slack we probably should
- fix this bug
- showcase a different message/colour when the zone has a parser associated but currently has no data

**Comment by corradio** [comment]
Idea: Use stripes to indicated temporarily missing data.
