### ISSUE TITLE
Georgia GE showing solar output at nighttimes

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap#1393]
![image](https://user-images.githubusercontent.com/25743609/39708678-195f1938-5218-11e8-8e37-206c68320117.png)

I feel like this is the first time solar is displayed/reported for Georgia?! Solar generation (except CSP) like this should not appear during nighttimes. Right now, it's showing 0 although it's still day in Georgia.

Maybe it was some testing or some other genegating type was put to "solar" accidentally by [the data provider](http://www.gse.com.ge/for-customers/data-from-the-power-system/power-balance).

Let's observe this over the next couple of days. Maybe it will be fixed by them or it won't happen again.

**Comment by jarek** [comment]
Isn't that import from Azerbaijan? Solar would be near the bottom, below hydro.

Checking https://api.electricitymap.org/v3/history?countryCode=GE just now, solar production has been 0 since 2018-05-06T17:59:00.000Z. Unless they've fixed it since?

**Comment by alixunderplatz** [comment]
@jarek Hahaha totally -.-" 😅😅😅
