### ISSUE TITLE
Clicking on countries does not display anything

### ISSUE THREAD

**Issue by qwjhvbxi** [tmrowco/electricitymap#1411]
As per title. Also after clicking there is a sudden CPU peak (to ~20%) that than decreases with time.
I already tried deleting cookies and restarting the browser but the problem persists. 
Nothing new appears on the console when clicking on a country.
The console errors appear to be related to data rather than code errors.
The problem is on Chrome 66 on Windows 10. It appears to work fine on Edge.

**Comment by corradio** [comment]
@jbuverud are you able to reproduce?

**Comment by jbuverud** [comment]
@qwjhvbxi, I'm not able to reproduce your issue on my machine running chrome 66 and windows 10. Have you tried disabling all your browser extensions?

**Comment by qwjhvbxi** [comment]
After two days of this problem, the map now works fine. I don't know why. Sorry for the inconvenience.
