### ISSUE TITLE
Norway bidding zones often delayed by ~1h30

### ISSUE THREAD

**Issue by brunolajoie** [tmrowco/electricitymap#1413]
Resulting in it being greyed out on the eMap. It's been the case for the last 2/3 day, it seems.
To keep an eye on it

![image](https://user-images.githubusercontent.com/22095643/40000194-7db9063c-578b-11e8-84e0-3c67ee8542ad.png)

**Comment by corradio** [comment]
Is there anything we can do about this? Else I suggest closing this issue as we already have a lot of them.
For what it's worth I haven't seen it grayed a lot (~20% of the time I'd say, and only for the southernmost part)
