### ISSUE TITLE
PEI can have 0 own production

### ISSUE THREAD

**Issue by jarek** [tmrowco/electricitymap#1421]
Currently we show Bornholm's carbon intensity as unknown when all the electricity is imported.

It should probably be added to the fully-import whitelist like Aland Islands were.

Same is true for Prince Edward Island, I saw it a couple of days back, but I don't have a screenshot.

![image](https://user-images.githubusercontent.com/47415/40277164-0c1f7738-5c1b-11e8-8873-597b51bdf10c.png)

**Comment by corradio** [comment]
I just did. Closing this issue. Feel free to re-open if it keeps happening!

**Comment by jarek** [comment]
Happens for PEI 
![image](https://user-images.githubusercontent.com/47415/41775246-7b5e6196-7623-11e8-9abc-e911fb557d12.png)

**Comment by corradio** [comment]
Fixed!
