### ISSUE TITLE
Bypass onboarding when map is embedded

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#1425]

**Comment by corradio** [comment]
@jbuverud can you take this one?
The problem is when people embed our map and put a direct link to a specific country: we shouldn't show the onboarding in that case.

**Comment by jbuverud** [comment]
As far as I can see, we already check if the map is embedded before creating the onboarding:

`if (!getState().application.onboardingSeen && !getState().isEmbedded) {
  onboardingModal = new OnboardingModal('#main');
  thirdPartyServices.trackWithCurrentApplicationState('onboardingModalShown');
}`

In our reducer we have

`  isEmbedded: window.top !== window.self,
`

Could it be that the window.top !== window.self trick is not working? It's a bit hard for me to debug when I can't recreate the embedded page..
