### ISSUE TITLE
Data for Iraq

### ISSUE THREAD

**Issue by tmslaine** [tmrowco/electricitymap#1434]
http://109.224.53.139:8080/IPS.php has real-time data for Iraq, an example from today:
![iraq_gen](https://user-images.githubusercontent.com/25774514/40884963-480e7026-6726-11e8-8034-334a6ec622ad.png)
"TIE LINES" seem to be imports from other areas. The only one I was able link to Iran is "MERSAD" for Mersad-Diyala, but many of the other ones could be Iran->Iraq as well.
Edit: 
I think the dashboard shows data for Iraq excluding Kurdistan. As a quick check the "Loads of Governorates" dashboard is indeed missing the governorates Dohuk, Erbil and Sulaymaniyah and the load on that dashboard is roughly the same as the field "TOTAL" on "Iraqi Power System".
Perhaps Iraq should be split to Iraq and Iraq (Kurdistan) with Iraq (Kurdistan) shown on eMap similarly to Crimea?

Sources:

- MERSAD - Iran: http://ninanews.com/News_Details.aspx?3yN4%252bMn38qQxw8wdRO%252fpbw%253d%253d&AspxAutoDetectCookieSupport=1
- KRMS, KRKH, SBZB -Iran; if machine translation is to be trusted this recent article mentions the transmission lines Karkh (KRKH?), Serbil Zehab(SBZB?), Kermanshah(KRMS?): https://www.alsumaria.tv/news/231154/%D8%A7%D9%84%D8%B9%D8%B1%D8%A7%D9%82-%D9%8A%D8%AA%D9%81%D9%82-%D9%85%D8%B9-%D8%A7%D9%8A%D8%B1%D8%A7%D9%86-%D8%B9%D9%84%D9%89-%D8%AA%D8%AC%D8%AF%D9%8A%D8%AF-%D8%A7%D8%B3%D8%AA%D9%8A%D8%B1%D8%A7%D8%AF-%D8%A7%D9%84%D8%B7%D8%A7%D9%82%D8%A9-%D9%84%D8%B9%D8%A7%D9%85/ar

- KURDISTAN : This article mentions that Iraqi Kurdistan is separated from the national grid: http://www.iq.undp.org/content/iraq/ar/home/operations/projects/poverty_reduction/kr-electricity-reconstruction.html
I am inclined to think this refers to Iraq (Kurdistan) as the Iranian province Kurdistan is only connected to the the Iraqi national grid via Iraq (Kurdistan)

Edit2:
There indeed seems to exist an electricity import agreement from Kurdistan region in Iraq to areas managed by Iraqi Ministry of Electricity: http://www.kurdistan24.net/en/news/7a035100-bd0e-45e8-a1c2-471f9ff419d5/Iraq-to-import-electricity-from-Kurdistan-Region-

**Comment by jarek** [comment]
IEA data says most of generation 2015 was from oil and gas: http://www.iea.org/statistics/statisticssearch/report/?country=IRAQ&product=electricityandheat&year=2015

Gas is there separately, so probably we can map all of "thermal" to oil?

**Comment by systemcatch** [comment]
Wow I never imagined something like this would exist at the moment in Iraq.

Watching the page, data is being requested from http://109.224.53.139:8080/api.php approximately every minute. The data being returned is json which looks like https://gist.github.com/systemcatch/0e0d556855ecee80fd12983f52986e4c.  Studying the html I think those identifiers (e.g. d_1020) can be mapped to each plant.

**Comment by jarek** [comment]
Also it seems the `title` attributes on the numbers (that show when hovering on the numbers) are the key numbers in the api.php response. Super easy to extract data. `lastmodified` field seems to match recent time in UTC+3 Arabia Standard Time used in Iraq.

**Comment by tmslaine** [comment]
All of the exchange lines on the SCADA are shown on a Iraqi Ministry of Electricity daily generation report from last year:
http://www.oco.moelc.gov.iq/upload/upfile/ar/1001.pdf

Iran line MERSAD = MERSAD 
Iran line KHRH = Kharkh = KRKH
Iran line KHRM = K(h)ermanshah = KRMS 
Iran line SRPL = Sarp(b)ol Zahab = SBZB

KUR-MSL = Kurdistan -> Mosul
KUR-KRK = Kurdistan -> Kirkuk

**Comment by alixunderplatz** [comment]
@tmslaine Cool that you found the daily generation report and the other valuable info!

I'd also assume that the autonomous region of Kurdistan is not included in that data, so we should seperate it from the rest of Iraq and show exchange data with this region. Your mapping of the tie lines looks totally legit!

For geometries, these are the adm_1 codes of the geographical regions that officially belong to Kurdistan entirely:
'IRQ-3046',
'IRQ-3050',
'IRQ-3242'

Some more areas are claimed, but remain oficially unrecognized. So I'd exclude only these three from the coverage.

See wikipedia for more details:
https://en.wikipedia.org/wiki/Iraqi_Kurdistan

I agree with @jarek that "thermal" is most likely for generation from oil.

I think we are ready to get this one working now?

If we had more national/inter-regional tie line info and knew more about the borders of the areas "North", "Middle" and "South", we could even split Iraq to cover three seperate zones. 
I suggest collecting the regional generation data in addition to the summarized data.

**Comment by systemcatch** [comment]
All the code has been merged in so Iraq should appear on the next deployment!
