### ISSUE TITLE
DK 5min data is now available from Energinet

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#1438]
See https://www.energidataservice.dk/da_DK/news/282a9317-0876-4e26-9737-2a0df8367694

**Comment by lorrieq** [comment]
Nice. I can have a look at this one.

It seems to be just wind and solar production data? Looks like the rest of production is lumped into two categories, depending on whether it came from generator with less than or greater than 100MW.

**Comment by corradio** [comment]
Really? that's a bummer.. I thought it would be the same categories as ENTSOE.

**Comment by lorrieq** [comment]
You can see on this [API sample](https://api.energidataservice.dk/datastore_search?resource_id=06380963-b7c6-46b7-aec5-173d15e4648b) the fields:

- ProductionLt100MW
- ProductionGt100MW
- OnshoreWindPower
- OffshoreWindPower
- SolarPower
- ExchangeNetherlands
- ExchangeNorway
- ExchangeSweden
- ExchangeGermany
- ExchangeGreatBelt
- BornholmSE4

Yes, a bummer on the production side. However, perhaps it would still be useful for the exchanges. If so I am happy to implement, if not should we close the issue?

**Comment by corradio** [comment]
We already have all interconnectors, so indeed this is a bummer :/
I'm closing this.
