### ISSUE TITLE
Data error for Aruba

### ISSUE THREAD

**Issue by Hyric89** [tmrowco/electricitymap#1439]
For a few days in a row now (possibly longer), data for the island country of Aruba has been offline. I went to check back on the source: https://www.webaruba.com/ and saw that the figures for electricity generation under the "Aruba's renewable energy monitor" block giving 0 MW for everything.

![image](https://user-images.githubusercontent.com/35940453/41054228-c6c87788-698b-11e8-88a6-cd5363a78d12.png)

When I click on [View ->], it takes me to [this page](https://webaruba.com/renewable-energy-dashboard/aruba)

![image](https://user-images.githubusercontent.com/35940453/41054238-d2db199a-698b-11e8-9909-a0a50829ad0a.png)

Real-time data for Aruba's electricity generation is present there but not on the front page.

**Comment by alixunderplatz** [comment]
Looks like they cut out biogas by now from the first page, it was supposed to be "coming soon" for a very long time :(
Fun fact: Aruba's is (or was?) aiming to reach 100% renewable share by 2020, if I recall correctly... not gonna happen!

![image](https://user-images.githubusercontent.com/25743609/41068447-c65e9aee-69e9-11e8-9342-5207f7110e24.png)

![image](https://user-images.githubusercontent.com/25743609/41068456-ced1c91c-69e9-11e8-8d9a-6e3a0d32006e.png)

**Comment by alixunderplatz** [comment]
I forgot to mention the obvious: Numbers on the website seem to be back now and the AW.py is returning valid values running it locally.

`{'zoneKey': 'AW', 'datetime': datetime.datetime(2018, 6, 6, 18, 30, 21, 802000, tzinfo=tzfile('America/Kralendijk')), 'production': {'oil': '89.36526489257812', 'wind': '26.8143253326416', 'solar': '0.12813511490821838'}, 'storage': {}, 'source': 'webaruba.com'}`

**Comment by Hyric89** [comment]
> Looks like they cut out biogas by now from the first page, it was supposed to be "coming soon" for a very long time :(

Rest assured that I'll bring up any updates on this matter that hold value to Electricitymap. I've done some reading on the Biogas topic as a citizen. If there are any questions about it, please ask away and I'll answer them to the best of my knowledge.

**Comment by alixunderplatz** [comment]
@Hyric89 thank you, that's very good to know! :)

Then I'll ask you some specific and some general questions right away :) 
* I've read in the past that some smaller biogas units were planned to be added to the system, probably for organic waste treatment or sewage gas. I've briefly searched the web, construction for a biogas unit started in December 2013 already according to this article: http://www.freezonearuba.com/mebers/free-zone-company-arubas-first-waste-to-energy-project/
Do you happen to know, whether it is operating already? I'd guess it is.

* I remember, another wind farm was planned - are there any local news in terms of wind energy?

* Are there any recent debates/news on the renewable-target? A [news article](https://www.edie.net/news/10/Aruba-turns-to-microgrids-on-quest-to-become-a-fossil-fuel-free/) from last year says Aruba is aiming for 50% by 2020 (which seems feasible and more realistic).

**Comment by Hyric89** [comment]
> I've read in the past that some smaller biogas units were planned to be added to the system, probably for organic waste treatment or sewage gas. I've briefly searched the web, construction for a biogas unit started in December 2013 already according to this article: http://www.freezonearuba.com/mebers/free-zone-company-arubas-first-waste-to-energy-project/
> Do you happen to know, whether it is operating already? I'd guess it is.

If by "operating" you mean produce gas, then probably not. In what press they are getting, it has more to do with collecting waste, compacting it and disposing of it elsewhere. Lately, though, they consistently refuse to give details as to the status or plans about their gasification plant or the production of gas.

> I remember, another wind farm was planned - are there any local news in terms of wind energy?

That was the proposed Urirama Wind Farm. It's been officially cancelled. The proposed project always had severe pushback due to the site being located near high-value land. This includes residences of people with wealth and influence and the fact that the wind farm would have been clearly visible from a vista held dear by tourists and locals alike. Alternative locations are now being sought. Sadly, that's the latest news regarding wind energy here.

> Are there any recent debates/news on the renewable-target? A news article from last year says Aruba is aiming for 50% by 2020 (which seems feasible and more realistic).

The date on that article is June 2017. Our previous election was in the following September and there's been a change in government. 

I've seen sources push the year to 2021, probably because it's an election year. There's also the 5.9 MW Sunrise Solar Park on the radar. As for the debate, there is wide consensus that the country should lower its imports on heavy fuel oil but wind power has NIMBY issues. Another factor to consider is rising real estate prices.

**Comment by Hyric89** [comment]
So, the data for Aruba has been available on the website for some time now but no data is displayed on the map. I would have thought that there would be data on Electricitymap as soon as data was available on WEB Aruba's website again. Is it something in the parser?

**Comment by systemcatch** [comment]
I get the following when running the parser manually, it doesn't appear on the map but there's no problem I can see?
```shell
(EM-env) chris@ThinkPad:~/electricitymap/parsers$ python AW.py 
{'production': {'oil': '65.53693389892578', 'wind': '27.87179183959961', 'solar': 0}, 'zoneKey': 'AW', 'source': 'webaruba.com', 'datetime': datetime.datetime(2018, 6, 18, 6, 0, 2, 396000, tzinfo=tzfile('/usr/share/zoneinfo/America/Aruba')), 'storage': {}}
```

**Comment by lorrieq** [comment]
Could it be as simple as the parser returning strings instead of floats?

**Comment by lorrieq** [comment]
<img width="624" alt="screen shot 2018-06-20 at 00 09 01" src="https://user-images.githubusercontent.com/6525086/41626983-b0f02b84-741e-11e8-90e8-7147b8a52b93.png">

The value of good logging! Looks like it was failing in `quality.validate_production`, see snippet above. I've cast the production values to floats and the parser now passes the quality check.
