### ISSUE TITLE
NO-NO3->SE and NO-NO1->SE exchange forecasts are invalid

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#1480]
```
query_exchange_forecast failed in ENTSOE.py. Reason: <text>
 Invalid business dimension parameters provided. Please check you request against dependency tables. One of the following parameters is not valid for Day-ahead Commercial Schedules [12.1.F]: 10YNO-3--------J, 10YSE-1--------K
</text>
```

**Comment by maxbellec** [comment]
[see https://kibana.electricitymap.org/app/kibana#/discover/1710fdd0-2460-11e8-a779-9d01de8d7a71?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-12h,mode:quick,to:now))&_a=(columns:!(level,extra.key,message),filters:!(('$state':(store:appState),exists:(field:level),meta:(alias:!n,disabled:!f,index:'93e631f0-245f-11e8-a779-9d01de8d7a71',key:level,negate:!f,type:exists,value:exists)),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'93e631f0-245f-11e8-a779-9d01de8d7a71',key:level,negate:!t,params:(query:INFO,type:phrase),type:phrase,value:INFO),query:(match:(level:(query:INFO,type:phrase))))),index:'93e631f0-245f-11e8-a779-9d01de8d7a71',interval:auto,query:(language:lucene,query:''),sort:!('@timestamp',desc)) for latest errors]

**Comment by maxbellec** [comment]
```bash
$ python test_parser.py NO-NO3-\>SE exchange
parser result:
{'netFlow': 93.2333, 'datetime': datetime.datetime(2018, 7, 3, 15, 39, tzinfo=tzutc()), 'source': 'driftsdata.stattnet.no', 'sortedZoneKeys': 'NO-NO3->SE'}
---------------------
took 0.73s
min returned datetime: 2018-07-03 15:39:00+00:00
max returned datetime: 2018-07-03T15:39:00+00:00 UTC  -- OK, <2h from now :) (now=2018-07-03T15:39:49.558835+00:00 UTC)
```

**Comment by corradio** [comment]
@maxbellec you need to check the forecast (not the actual exchange)
