### ISSUE TITLE
German translation hides top buttons

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#1491]
It seems like part of the emission toggle is not visible, probably because the element is positioned absolute. This doesn't play well when the header is higher than expected (due to an extra line break in German)

cc @ovbm 

![image](https://user-images.githubusercontent.com/1655848/42212376-36c0cf2e-7eb6-11e8-838d-4d819b13f210.png)

**Comment by ovbm** [comment]
nice catch
