### ISSUE TITLE
Map on mobile devices

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#193]
- [x] Simplify polygons
- [x] Make map draggable and zoomable within bounds
- [x] Faster arrows
- [x] Proper UI to navigate back and forth between map and ranking table
- [ ] Proper UI to activate wind/solar
- [ ] ~Enable progressive web app on Android~

Experimental branch: https://github.com/corradio/electricitymap/tree/mobile-map

**Comment by corradio** [comment]
![image](https://cloud.githubusercontent.com/assets/1655848/23741941/29a70726-04ab-11e7-9397-31e8fab916fa.png)

I'm playing around with the mobile map. It's actually quite nice to be able to press on countries and have the tooltips. Maybe we could build a UX where the user presses on the tooltip to go to the full country panel? What do you think @scarlac ?

**Comment by scarlac** [comment]
That would work. We'll need to move the tooltips so they are not placed relative to the country but in a static location.
