### ISSUE TITLE
Sub-country CO2 calculations

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#196]
I'm compiling a list of resources we will be able to use if we want to do sub-country co2 calculations:

- https://wiki.openstreetmap.org/wiki/Power
- http://www.50hertz.com/Netzlast/Karte/index.html
- http://www.rte-france.com/en/eco2mix/eco2mix-donnees-regionales-en
- Power stations, including wind: http://url.ie/11nts - about 95% complete
- High-voltage network (over 100 kV): http://url.ie/11ntu (may take a moment to load) - more than 99% complete.

**Comment by corradio** [comment]
https://github.com/corradio/electricitymap/commit/1c8ae48ee600360549fb5cc37908577a65f199fe added support for rendering country subdivisions on the map.

**Comment by corradio** [comment]
We might instead be interested on doing Market Balance Areas - we just need the polygons to get started.

**Comment by fedders** [comment]
For Denmark it is easy. DK1 is west of "Storebælt", DK2 is east. I believe that Sprogø is DK2. Anholt & Læsø are DK1.
For Norway and Sweden, the best I've got is the following simplistic map:
http://driftsdata.statnett.no/Web/Map/ But then again, I don't think we need to show the zones at a resolution where you can determine at house level where it belongs.

In Germany, there are Control Blocks for each TSO, for which production is reported in the transparency portal, which might make it possible to add segmentation there as well.

ENTSO-E has a zoomable map of the transmission European grid here: https://www.entsoe.eu/map/Pages/default.aspx

**Comment by corradio** [comment]
Thanks! We'll take a look at soon as we have time.

**Comment by FlorentVTT** [comment]
For France there is a problem  the production by area, is not detailed for "Thermical" (includes coal, gas, fioul). 
Other electricity sources are detailed.

How to calculate CO2 ? How to display ? 
Example : http://eco2mix.rte-france.com/download/eco2mix/eCO2mix_RTE_PACA_En-cours-TR.zip

**Comment by fedders** [comment]
You could / should use the data from the transparency platform instead. "Actual aggregated generation per type", there production is split by:

  *   B19 - Wind Onshore
  *   B10 - Hydro Pumped Storage
  *   B01 - Biomass
  *   B17 - Waste
  *   B14 - Nuclear
  *   B12 - Hydro Water Reservoir
  *   B04 - Fossil Gas
  *   B11 - Hydro Run-of-river and poundage
  *   B16 - Solar
  *   B06 - Fossil Oil
  *   B05 - Fossil Hard coal


https://transparency.entsoe.eu/api?securityToken=<security token>&documentType=A75&processType=A16&in_Domain=10YFR-RTE------C&periodStart=2016-12-31 23:00&periodEnd=2017-02-21 23:00

Kind regards,
Fedder
________________________________
Fra: Florent Coste <notifications@github.com>
Sendt: 22. februar 2017 10:23
Til: corradio/electricitymap
Cc: fedders; Comment
Emne: Re: [corradio/electricitymap] Sub-country CO2 calculations (#196)


For France there is a problem the production by area, is not detailed for "Thermical" (includes coal, gas, fioul).
Other electricity sources are detailed.

How to calculate CO2 ? How to display ?
Example : http://eco2mix.rte-france.com/download/eco2mix/eCO2mix_RTE_PACA_En-cours-TR.zip

**Comment by FlorentVTT** [comment]
Are you sure ENTSOE API give you details per (French) "region" ? 
For sure it would be great.

RTE API does, exemple for "Provence Alpes Cote d'Azur".
http://eco2mix.rte-france.com/download/eco2mix/eCO2mix_RTE_PACA_En-cours-TR.zip with the limitation i gave.

**Comment by fedders** [comment]
No. The lowest granularity of the Transparency portal is "Bidding Zone" or "Market Balance Area". As there is only one of those in France, you are right.


________________________________
Fra: Florent Coste <notifications@github.com>
Sendt: 22. februar 2017 11:44
Til: corradio/electricitymap
Cc: fedders; Comment
Emne: Re: [corradio/electricitymap] Sub-country CO2 calculations (#196)


Are you sure ENTSOE API give you details per (French) "region" ?
For sure it would be great.

RTE API does, exemple for "Provence Alpes Cote d'Azur".
http://eco2mix.rte-france.com/download/eco2mix/eCO2mix_RTE_PACA_En-cours-TR.zip with the limitation i gave.
