### ISSUE TITLE
Add Luxembourg from ENTSOE

### ISSUE THREAD

**Issue by grischard** [tmrowco/electricitymap#212]
Luxembourg is currently not shown on the map, would it please be possible to add it? The data is [apparently available from ENTSOE](https://transparency.entsoe.eu/generation/r2/actualGenerationPerProductionType/show?viewType=GRAPH&dateTime.dateTime=28.12.2016+00:00|UTC|DAYTIMERANGE&dateTime.endDateTime=28.12.2016+00:00|UTC|DAYTIMERANGE&area.values=CTY|10YLU-CEGEDEL-NQ!BZN|10Y1001A1001A63L&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19) with the identifier 10YLU-CEGEDEL-NQ.

**Comment by corradio** [comment]
Makes sense. We'll look into it asap.
The biggest issue for LUX is actually a UI one: it's hard to show the import/export arrows.

**Comment by corradio** [comment]
@Pantkowsky / @ThierryOllivero do you have time to take a look at the data quality and add the parser? I think it's acceptable to add the country without the arrows for now.

**Comment by grischard** [comment]
Or maybe just a single arrow? A lot of our energy is imported.

**Comment by grischard** [comment]
Ah, sorry @Pantkowsky, didn't mean to unassign you!

**Comment by corradio** [comment]
That's the bidding zone AT-LU-DE. I am not sure this is LUX only? Can
anyone confirm?
The country data for LUX is indeed referenced by 10YLU-CEGEDEL-NQ, and is
already added to `ENTSOE.py` actually. We're just waiting for data.

Olivier

On Mon, Feb 6, 2017 at 6:10 PM, Guillaume Rischard <notifications@github.com

**Comment by systemcatch** [comment]
@corradio looks like data is available now.

**Comment by corradio** [comment]
Hmm where do yo see that? I see only n/a at https://transparency.entsoe.eu/generation/r2/actualGenerationPerProductionType/show?name=&defaultValue=false&viewType=TABLE&areaType=CTY&atch=false&datepicker-day-offset-select-dv-date-from_input=D&dateTime.dateTime=22.11.2017+00:00|CET|DAYTIMERANGE&dateTime.endDateTime=22.11.2017+00:00|CET|DAYTIMERANGE&area.values=CTY|10YLU-CEGEDEL-NQ!CTY|10YLU-CEGEDEL-NQ&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)

**Comment by systemcatch** [comment]
I see it here https://transparency.entsoe.eu/generation/r2/actualGenerationPerProductionType/show?name=&defaultValue=false&viewType=GRAPH&areaType=BZN&atch=false&datepicker-day-offset-select-dv-date-from_input=D&dateTime.dateTime=22.11.2017+00:00|CET|DAYTIMERANGE&dateTime.endDateTime=22.11.2017+00:00|CET|DAYTIMERANGE&area.values=CTY|10YLU-CEGEDEL-NQ!BZN|10Y1001A1001A63L&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2) , maybe that's not the exact thing we need though?

**Comment by corradio** [comment]
That's the bidding zone AT-DE-LU (which contains part of Austria and
Germany unfortunately)

**Comment by systemcatch** [comment]
Ah lame I was looking at the wrong tab.

**Comment by corradio** [comment]
Luxembourg is part of the AT-DE-LU bidding zone, so unfortunately I think this will be impossible.
Closing for now

**Comment by fconrotte** [comment]
Now that Austria is split from Germany in ENTSOE data, it seems the values are populated in the Luxembourg electricity generation grid

Could it be used to support Luxembourg on ElectricityMap ?

https://transparency.entsoe.eu/generation/r2/actualGenerationPerProductionType/show?name=&defaultValue=true&viewType=TABLE&areaType=BZN&atch=false&datepicker-day-offset-select-dv-date-from_input=D&dateTime.dateTime=16.01.2019+00:00|CET|DAYTIMERANGE&dateTime.endDateTime=16.01.2019+00:00|CET|DAYTIMERANGE&area.values=CTY|10YLU-CEGEDEL-NQ!BZN|10Y1001A1001A82H&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)
