### ISSUE TITLE
Add Faroe Islands

### ISSUE THREAD

**Issue by Pantkowsky** [tmrowco/electricitymap#234]
Faroe Islands are missing on the map. We can get the data on Faroe Islands from here:

https://w3.sev.fo/framleidsla/

**Comment by corradio** [comment]
There's something quite interesting, as they are negative numbers for some units:
```xml
<Lomundaroyri>-1,59</Lomundaroyri>
<Heygadalur>-0,94</Heygadalur>
<Eidisvatn>-2,84</Eidisvatn>
<Strandadalur>-1,25</Strandadalur>
<Ryskisvatn>-0,59</Ryskisvatn>
<Vatnsnesvatn>-0,59</Vatnsnesvatn>
```
They correspond to the gauges on the picture:
![image](https://cloud.githubusercontent.com/assets/1655848/26097700/bc6faeaa-3a25-11e7-8b1e-fb86dc65ca1a.png)

They must represent the storage level somehow. Does anyone have some insights?

**Comment by jarek** [comment]
Water levels are found in the XML. I haven't found the storage flows yet though. I don't know if there actually are any - maybe they're only replenished naturally.

```
<Vatnid>-5,43</Vatnid> - water level in Vatnið, range from 0 (full) to -11 (empty)
<Lomundaroyri>-1,62</Lomundaroyri> - water level in Lomundaroyri, range from 0 (full) to -5 (empty)
<Heygadalur>-0,72</Heygadalur> - water level in Heygadalur, range from 0 to -5
<Eidisvatn>-2,77</Eidisvatn> - water level in Eiðisvatn, range from 0 to -20
<Strandadalur>-1,19</Strandadalur> - water level in Strandadalur, range from 0 to -2.5
<Ryskisvatn>-0,43</Ryskisvatn> - water level in Ryskisvatn, range from 0 to -3.5
<Vatnsnesvatn>-0,43</Vatnsnesvatn> - water level in Vatnsnesvatn, range from 0 to -5
```

Exploration in progress of the JS used to draw the gauges: https://gist.github.com/jarek/47034b6fd5a5aba20755b610120a90ed

**Comment by corradio** [comment]
Thanks for the help. Do we have an idea of the unit of the storage level?

**Comment by jarek** [comment]
Per http://www.sev.fo/Default.aspx?ID=193&Action=1&NewsId=2921&PID=392 , pumped storage is not currently used.

I haven't found the units officially yet. https://en.wikipedia.org/wiki/Ei%C3%B0i_power_plant says the dammed reservoir behind the station is "elevation 129 to 149 meters", which is 20 meters, which matches `Eidisvatn` values in XML/JS, so it could just be meters. I couldn't find depths for any of the other reservoirs yet, though.

**Comment by corradio** [comment]
Ah that's interesting. Well if there's no storage, then we don't need to
include it on the Electricity Map. What do you think? If you agree, let's
close this.

Thanks for investigating.

**Comment by jarek** [comment]
Yeah it looks fine.

The parser sometimes has problems (sees no generation, or only wind generation) but I haven't caught it live yet so don't know if it's a parser or underlying data problem. Can probably close this issue, and if there's any improvements they can go in a separate issue or pull request.

**Comment by corradio** [comment]
👍
