### ISSUE TITLE
Wrong screen in Win10 Mobile [bug]

### ISSUE THREAD

**Issue by GergelyMindler** [tmrowco/electricitymap#256]
Hi Team, I emulated Win10 mobile in Internet Explorer Edge and see this screen below. It seems that indetifying of browser is working wrong. Could someone check it in a real Win10 Mobile?

![image](https://cloud.githubusercontent.com/assets/24973489/21780850/5ebee31a-d6ad-11e6-91e8-177e7e011449.png)

**Comment by corradio** [comment]
It seems the user agent is not properly detected.
Maybe this function needs to be updated to include "edge": https://github.com/corradio/electricitymap/blob/master/web/app/main.js#L30

**Comment by corradio** [comment]
The design is now fully responsive so this shouldn't be an issue anymore
