### ISSUE TITLE
Natural gas capacity and biomass capacities too low

### ISSUE THREAD

**Issue by johnsmithb3ta** [tmrowco/electricitymap#261]
ENTSO-E is known to have many problems with its stated capacities. This is because it relies on individual countries to send it updated numbers every year. In reality, the TSOs don't take this task very seriously and often just send last year's numbers. After a few years of doing this, the figures can be quite wrong. I have compared the figures in countryconfig.js with the Platts database (http://www.platts.com/products/world-electric-power-plants-database), which is the commercial database that professionals rely on for power plant details.

Unfortunately, Platts also contains errors, especially some decommissioning details, and it does not always have the very latest renewable capacities right, because wind and solar is being installed very quickly these days.

The attached file shows the difference (see the last table) for the countries I work with. There are two key issues that I would consider updating:
1. Germany is missing about 39GW natural gas
2. The biomas figures are generally too low - in Denmark, for example, half of coal power plants have been converted to wood chips. This is happening across Europe, and is not reflected in the ENTSO-E capacities.

It would appear that there is a lot more coal capacity in the UK than ENTSO-E has listed. I will double check this, as coal is rapidly being decommissioned in the UK, so the Platts figure may be incorrect.
[electricitymap_capacities.txt](https://github.com/corradio/electricitymap/files/698817/electricitymap_capacities.txt)

**Comment by corradio** [comment]
@brunolajoie can you take a look?

**Comment by emillarsen** [comment]
I made a mistake in my data extraction. The 20GW-mismatch for natural gas in Germany is due to planned power plants that got cancelled.

**Comment by corradio** [comment]
@emillarsen @johnsmithb3ta @brunolajoie do you have any specific updates on this issue? Else I will close due to inactivity

**Comment by brunolajoie** [comment]
No specific update on my side, you can close it. We should rather open these types of issues in a case by case basis

**Comment by corradio** [comment]
ok. @brunolajoie , next time, feel free to close it
