### ISSUE TITLE
Add Turkey

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#271]
Check ENTSOE. Also, data seems to be available here: https://ytbs.teias.gov.tr/ytbs/frm_login.jsf
What needs to be done:
Copy this file (https://github.com/tmrowco/electricitymap/blob/master/parsers/example.py) and adapt it to the Turkish API.

**Comment by ThierryOllivero** [comment]
Nothing on ENTSOE, but good data on the other site.

**Comment by mrchrisadams** [comment]
I've had a quick look at this, and I'm happy to have a go this Sunday, or next week.

From what I can see the data is in the page itself, and this array here, in an array 24 objects long, one for each hour of the given date.

```json
{
    "biyokutle": "290.21",
    "asfaltitkomur": "264.95",
    "lng": "0",
    "barajli": "7018.11",
    "ithalkomur": "3136.01",
    "akarsu": "4831.78",
    "dogalgaz": "7117.30",
    "uluslarasi": "-258.00",
    "ruzgar": "1835.39",
    "saat": "1",
    "linyit": "3864.86",
    "fueloil": "162.30",
    "taskomur": "355.50",
    "nafta": "4.70",
    "jeotermal": "556.66"
  }, {
    "biyokutle": "276.88",
    "asfaltitkomur": "258.32",
    "lng": "0",
    "barajli": "6449.46",
    "ithalkomur": "2808.95",
    "akarsu": "4823.02",
    "dogalgaz": "6749.02",
    "uluslarasi": "-386.00",
    "ruzgar": "1714.24",
    "saat": "2",
    "linyit": "3847.23",
    "fueloil": "164.40",
    "taskomur": "361.50",
    "nafta": "4.70",
    "jeotermal": "559.12"
  }

```

The date for this info also appears to be here as well:

```html
<input id="formdash:bitisTarihi2_input"
name="formdash:bitisTarihi2_input"
type="text"
value="2017-04-21"
class="ui-inputfield ui-widget ui-state-default ui-corner-all"
placeholder="yil-ay-gun" />
```

I'm not sure what the keys mean yet, as I haven't had a go at trying to translate them - assuming they refer to the keys in the example, is there anything else I'd need to add to get this into the map?

**Comment by corradio** [comment]
Sounds cool. You need to write a script that can fetch those and map them into our datastructure.
Check out the example here: https://github.com/tmrowco/electricitymap/blob/master/parsers/example.py (just use the `fetch_production` method)
