### ISSUE TITLE
Wind drawing bug at 0deg meridian

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#277]
Some particles are "stopping" at the greenwich meridian

![image](https://cloud.githubusercontent.com/assets/1655848/21909641/11d11442-d919-11e6-9bf7-da1949cb1d1a.png)

**Comment by ThierryOllivero** [comment]
I can't reproduce the bug, even in going at this time. Is it still happening for you?

**Comment by corradio** [comment]
Yes.. It's hard to see though, but there's a suspicously high number of particles that "end" one the meridian

![image](https://cloud.githubusercontent.com/assets/1655848/21924013/6ff1dc9c-d977-11e6-99f2-f72d8683b0a4.png)

**Comment by ThierryOllivero** [comment]
![image](https://cloud.githubusercontent.com/assets/22315693/21925529/30dbe4f6-d97e-11e6-8fc7-393021ff7ad8.png)

On mine it works :/

**Comment by corradio** [comment]
ok I'll come back with more info when I debug my version.

On Fri, Jan 13, 2017 at 10:51 AM, Thierry Ollivero <notifications@github.com

**Comment by corradio** [comment]
Further info: it doesn't seem to be a projection problem, because when the window is big enough, particles are properly getting through. It seems to be an issue when the window because so small that the resolution becomes insufficient.

**Comment by maxbellec** [comment]
@corradio should this still be open? I don't see any particle stopping.

**Comment by corradio** [comment]
If you can't reproduce, then we can close!
