### ISSUE TITLE
Country panel tooltip should show emissions when "emissions" are selected

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#283]
When "emissions" are selected, country panel tooltip should show emissions instead of power.

![image](https://cloud.githubusercontent.com/assets/1655848/21932383/a3c6c4e6-d9a0-11e6-8bd7-32616a7e9eaa.png)

**Comment by ThierryOllivero** [comment]
So, no Capacity Factor and "Proportion of total emissions" instead of "Proportion of total production?"

**Comment by corradio** [comment]
yep. It would kind of a joke to show CO2 capacity factor 😆

**Comment by ThierryOllivero** [comment]
Why not though. We could show something like:

- Worst reachable : 850 gCO2/kWh
- Best reachable : 240 gCO2/kWh
- Actual reached : 432 gCO2/kWh

**Comment by corradio** [comment]
Emissions are in tCo2/h (not /kWh). Capacity would mean something along the lines of "maximum amount of CO2 emissible by production mode X"

**Comment by ThierryOllivero** [comment]
Then replace gCO2/kWh by tCO2/h :)

Given the current demand (let's say 10 GW), you can "allocate" this 10 GW by ascending order of clean technologies capacities. Once each of the 10 GW is allocated, you calculate the "best possible".

To calculate the worst possible, you do the opposite: you allocate by ascending order of not clean technologies. 

Then you compare.

**Comment by corradio** [comment]
Feedback received by the survey: "I think you should add "Proportion of total emissions" below "Proportion of total production" in the description each energy source."
We could also do that (instead of having to switch to emissions before)

**Comment by ThierryOllivero** [comment]
I prefer to switch. UI wise that would be too much information on one screen. It make more sense to have a tooltip for production and one for emissions. Saint Exupéry like.
