### ISSUE TITLE
ENTSOE: Unable to get LT->RU exchange

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#321]
Error returned by API:

Failed to get exchange. Reason: Invalid business dimension parameters provided. Please check you request against dependency tables. One of the following parameters is not valid for Physical Flows [12.1.G]: 10YLT-1001A0008Q, 10Y1001A1001A49F

The data is here so it should work!

![image](https://cloud.githubusercontent.com/assets/1655848/22327429/6f065b60-e3b7-11e6-9415-c4482329f502.png)

Pretty weird. @rustyb are you able to help?

**Comment by greennuts** [comment]
If you manage to get data and make separate tie-line data for RUS (Kaliningrad) to LT, then CO2/kWh can be used gas, as there only electricity source for now is gas

**Comment by rustyb** [comment]
@corradio Thanks for letting us know, will forward onto my colleagues to investigate.

**Comment by rustyb** [comment]
Howdy @corradio you are correct in that one of the parameters above is incorrect. 

For the exchange between Kaliningrad and Lithuania the following EIC area codes are used:

- Kaliningrad `10Y1001A1001A50U`
- Lithuania `10YLT-1001A0008Q`

I guess it's just a case of adding Kaliningrad to https://github.com/corradio/electricitymap/blob/master/parsers/ENTSOE.py

**Comment by Dalius-ENTSO-E** [comment]
Correct, if you want to query LT<>RU-KGB border, you have to use Kaliningrad area code 10Y1001A1001A50U . 10Y1001A1001A49F is a EIC code of mainland of Russia.

**Comment by corradio** [comment]
Thanks. We should probably split RU in two zones in the Electricity Map.
