### ISSUE TITLE
Redraw wind/solar on resize

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#357]
..possibly with a debounce

**Comment by systemcatch** [comment]
Were you able to fix this in the Mapbox PR?

**Comment by corradio** [comment]
nope. I think this is easy to fix though.

**Comment by maxbellec** [comment]
should this still be opened? Wind and solar get updated when I resize.

**Comment by corradio** [comment]
Indeed I can't reproduce. I love it when issues close themselves
