### ISSUE TITLE
Add Australia

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#378]
Some links:
- http://www.nem-watch.info/widgets/RenewEconomy/
- http://nemweb.com.au/REPORTS/CURRENT/
- http://reneweconomy.com.au/nem-watch/
- http://services.aremi.nationalmap.gov.au/aemo/v3/csv/all

**Comment by corradio** [comment]
@snoblenet is taking a look (sorry, can't assign because github only allows project members to be assigned)

**Comment by corradio** [comment]
We should use AREMI's http://services.aremi.nationalmap.gov.au/aemo/v3/csv/all. Will try to write a parser except if @snoblenet is already doing it?

**Comment by snoblenet** [comment]
yep -- will do -- will also update everyone on planned timelines soon -- on here or on slack?

**Comment by corradio** [comment]
Let's do it here - it's easier.

**Comment by snoblenet** [comment]
On Monday 20 (or possible Monday 27) I start a new job that involves a 95 minute commute twice a day. For security reasons I can't do any of my job on my personal laptop out of the office, so that's 3 hours 10 minutes a day I want to largely devote to hacking for the public good. So I'm hoping to start this project then and finish it fairly quickly. Once I start my new job I won't have much time around the house to finish the renovation, so until then I'm hoping to focus on that instead. Does that timetable work for everyone?

**Comment by corradio** [comment]
Hi Steven,

That sounds good. Let me know if there's anything I can do to help! We'll
focus on building the rest of the infrastructure so you can focus on the
parser itself.

Olivier

**Comment by corradio** [comment]
The frontend is ready.
There's a few questions to be answered still:
- What does the "aggregated" column in the csv mean? Is that an aggregation of several plants?
- Can we actually split the data up per state, or are we stuck with the whole country?

**Comment by corradio** [comment]
I've made a small test here:
https://github.com/tmrowco/electricitymap/blob/master/parsers/AU.py

![image](https://cloud.githubusercontent.com/assets/1655848/25246998/cb11f2e0-2609-11e7-8f0c-cab322d565af.png)

@brunolajoie @ThierryOllivero @snoblenet can you guys comment on whether or not this sounds reasonable? We can think about dividing into states in a later iteration.

**Comment by snoblenet** [comment]
Just looking at proportions not numbers, coal and wind seems about right, I would have expected hydro and gas to be higher. Much solar in Australia is domestic rooftop solar PV which may be showing up in the AEMO numbers as energy saving not production. Geothermal and nuclear are both zero in Australia.

**Comment by snoblenet** [comment]
Regarding your state-by-state question:

- The data we are using is for a common market that includes every state and territory other than the Northern Territory, Western Australia and off-shore territories -- Ketan, is data available for those locations too?
- The only inter-state export data I could see in the AEMO data was for the undersea link between Tasmania and the mainland, within the common market
- As each generator is listed individually, we should be able to manually assign each to a state/territory and calculate state-by-date _production_ on that basis
- I'm not aware of any source of real-time _consumption_ data -- Ketan?

**Comment by snoblenet** [comment]
Our top-line figure for the common market (exclude WA etc) is 745g. According to the latest IPCC report, the top-line figure for Australia as a whole is 885g:

https://www.ipcc.ch/pdf/special-reports/sroc/Tables/t0305.pdf

You'd expect the national figure to be higher than the common market figure as our biggest hydro facilities are in the common the market, but maybe not that much higher...

**Comment by snoblenet** [comment]
Electricity price data is here: https://www.aemo.com.au/Electricity/National-Electricity-Market-NEM/Data-dashboard

**Comment by snoblenet** [comment]
State-by-state generation/demand/etc data presented in human readable form here:

https://www.aemo.com.au/Electricity/National-Electricity-Market-NEM/Data-dashboard#nem-dispatch-overview

But we'd have to build a scraper not a parser unless this data is available elsewhere in a machine readable format.

**Comment by snoblenet** [comment]
Comments from Ketan, who doesn't have a Github account:

> I couldn't quite figure out how to respond, but no real-time output from WA as far as I'm aware that's easily accessible like NEM data is. Real time consumption - some limited stuff here: http://energyconsumersaustralia.com.au/connect/electricity-map/ … but only state level and probably not easily extractable for the purposes of the tool

**Comment by corradio** [comment]
Great so we can have access to:
- interstate exchanges + capacities
- price by state

Now we just need to know the production mix per state. We could allocate each generator in the CSV to a state, but how would one do that mapping? Based on location?
Also, how do these guys (http://www.nem-watch.info/widgets/RenewEconomy/) do it?

**Comment by snoblenet** [comment]
We should be able to set up a manual mapping against generator name using Dr Google. Even for location names like 'Bayswater' that are very common in Australia, a search for the actual generator name like 'Bayswater Power Station' is definitive. The widget you identify is provided by a private company called Roam that no doubt did something similar.

**Comment by corradio** [comment]
OK.
Could you or someone else prepare the mapping? Then I can try to figure out to get interstate exchanges.

**Comment by snoblenet** [comment]
yeah no problem — i’ll stick something up in a gist
---
Steven Noble
http://snoble.net
+61 (0) 4 0404 1928

**Comment by snoblenet** [comment]
here you go: https://gist.github.com/snoblenet/5831d19b5103039f98cc9bac6bf847d4

**Comment by corradio** [comment]
@snoblenet I don't have any stations for NT and Western. Is that normal?

**Comment by corradio** [comment]
Also, `Eildon Power Station` seems to be missing from the mapping.

**Comment by snoblenet** [comment]
Yeah, the dictionary lists all the power stations in AREMI, the common market that includes all Australia other than Western Australia, the Northern Territory and offshore territories (e.g. Christmas Island.) I'm not sure how to obtain data about those areas.

Lake Eildon is in Victoria, sorry.

**Comment by corradio** [comment]
👍

**Comment by snoblenet** [comment]
looks like WA data is here:

http://data.wa.aemo.com.au/#facility-scada

Not real time however

**Comment by corradio** [comment]
Closing this as we have a first version working!
