### ISSUE TITLE
Map is too dark

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#391]

**Comment by corradio** [comment]
Here's a test:

![image](https://cloud.githubusercontent.com/assets/1655848/23835022/454b8422-0760-11e7-90b3-df64b718b637.png)

**Comment by brunolajoie** [comment]
Not bad actually!

**Comment by corradio** [comment]
@scarlac FYI, this is a screenshot of the Uber Movement dataset, where they use a similar color scale:

![image](https://cloud.githubusercontent.com/assets/1655848/24054582/ad3666b0-0b34-11e7-872e-f3e21b568604.png)

**Comment by ThierryOllivero** [comment]
Where do we stand on this issue? I like your first screenshot Oli. Spring is coming, we need more light :)

**Comment by corradio** [comment]
Didnt have time to work on it. I think we should investigate the Uber colorscale.

**Comment by corradio** [comment]
What about this?

![image](https://cloud.githubusercontent.com/assets/1655848/25143042/463ce18e-2469-11e7-9c1f-7acbf993c32f.png)

**Comment by ThierryOllivero** [comment]
I liked better the other one. This one makes me sad. Don't know why.

**Comment by brunolajoie** [comment]
I share Thierry's opinion

**Comment by Raffox97** [comment]
I think that we should put an option to switch between the original (That it would be a great dark/night theme) and the one in the screenshot

**Comment by tth4vb** [comment]
I like the first proposal for lighter background colors. Additionally, I've mocked up a single-hue scale for carbon intensity below:
![carbon intensity scale](https://user-images.githubusercontent.com/8129157/27545805-1afad9aa-5a91-11e7-9901-849652e2e438.png)

My reasoning for switching to a single-hue scale:

- Intuitively, it doesn’t make sense to me to represent carbon intensity in non-green colors/multiple colors. I understand the motivation behind using blacks/oranges to represent countries with high carbon intensity, but I think that this could confuse users who might associate these colors more with temperature, solar resources, or another metric. Currently, the transition of greens to orange/black implies a change from positive to negative values in my mind. Yet the actual measures start at an absolute zero and increase from there. What I’m proposing is a scale reflects this absolute zero with a very light color and increases in saturation with an increase in carbon-neutral energy infrastructure. In this scale, a more intense green would mean a less carbon-intensive energy mix. From a psychological standpoint, we would be representing a country with a high carbon intensity as lacking in “green energy” infrastructure as opposed to that country being “bad”. I think that climate change activism already suffers from an overuse of finger-pointing and blaming, so there could be something useful here in terms of positive psychology. Also, green is of course generally the color most-associated with eco-friendly things. That being said, these ideas are largely based off of my assumptions and I think that such a change would best be made after some validated learning is done.

- Eliminating the blacks and oranges from the color scale gives us more flexibility in color schemes on the rest of the map, particularly when viewing the solar/wind resources layers in conjunction with the carbon intensity layer.

And here's what it would look like on the actual map (note: the assigning of colors is not accurate, and several countries are intentionally grey to represent a lack of data):
![world map carbon intensity layer spec](https://user-images.githubusercontent.com/8129157/27545918-739d07ae-5a91-11e7-8b65-7f99d1256e89.png)

**Comment by jarek** [comment]
For colours, we could use something like https://jiffyclub.github.io/palettable/ , e.g. getting colours from ["Greens_9" palette" is possible continuously](https://jiffyclub.github.io/palettable/colorbrewer/sequential/img/Greens_9_continuous.png).

Key term when reading about this is apparently "sequential palette". I was reading http://seaborn.pydata.org/tutorial/color_palettes.html#sequential-color-palettes, though note that sequential palettes usually provide a set amount of colours, which won't work for us. Palettable apparently supports continous, somehow, though I'm not sure how.

**Comment by tth4vb** [comment]
I think the key issue here is whether we should be using a sequential or gradient palette, gradient allowing for more continuous granularity in data representation.

My opinion is that we don't need to use a gradient palette and can instead put each country into a histogram-style bucket for carbon-intensity, as I don't think the users will really be able to distinguish slight changes in the colors if two countries are off in carbon intensity by 10g C02 eq/kWh for example.

I think in terms of visually communicating information in a way that is immediately useful to someone reading this map, it generally would be more useful to use a sequential system and put the two fictional countries in the above example in the same color on the color scale. That being said, I can see an argument for a gradient, but I feel like I need to hear a good concrete use case to sell me on it.

**Comment by corradio** [comment]
I like where this is going. Regarding color, I'd like to suggest going for a single hue, but instead of showing the amount of green infrastructure, I'd show instead the amount of fossil fuel (for example with a white -> brown scale).
The reason is that, for carbon emissions, what matters is turning off the fossil fuel production, not necessarily building more green production modes.

**Comment by jarek** [comment]
A possible issue with featuring fossil fuels is that currently the header is "Live CO2 emissions of electricity consumption", so you'd have to change that and all the translations. I do see your point about rewarding turning off fossil though...

Regarding continuous gradient vs e.g. 9 colours. I agree that 78 vs 87 g co2eq/kWh isn't really an important distinction to make. A downside is that when using distinct categories, you have to draw the boundaries somewhere, so you might be making a colour distinction between 98 and 102 g/kWh. Although, depending on how different visually the 9 colours are, that might not be a big issue in practice if they look fairly similar anyway.

**Comment by corradio** [comment]
@jarek Sorry for not being clear. I didn't mean change from co2 intensity
to fossil fuel %. Instead, I simply meant that instead of using a scale
that shows amount of "greenness", we could use a scale that shows the
amount of "darkness", i.e. from white to brown (from 0 to 800 gCO2/kWh).

**Comment by ThierryOllivero** [comment]
I fully support the idea of a single-hue, changing according to CO2 emissions, with a color that could highlight the fact that  high fossil fuels means high CO2 emissions (correlation and causation).

**Comment by corradio** [comment]
Other examples:
https://www.mapbox.com/gallery/#map-3
http://feltron.com/BikeCycle.html

**Comment by systemcatch** [comment]
I like the idea of having the option to switch between different colour schemes, though I don't know if that's loads of work to implement on the frontend?  The oceans on the map currently look very dark and I think that making them lighter (e.g. 12 Mar screenshot) would improve the focus on countries.

**Comment by corradio** [comment]
On a projector, the issue becomes quite apparent:
![image](https://user-images.githubusercontent.com/1655848/30631425-7698832a-9de4-11e7-83d9-ab4b1297fc1f.png)

**Comment by corradio** [comment]
Basically it seems that the country colors blend with the panel background and with the sea.
The contrast ration should probably be bigger.

**Comment by corradio** [comment]
More inspiration:

![image](https://user-images.githubusercontent.com/1655848/36550780-60c1d9c0-17f6-11e8-9a30-ab76a194e8c7.png)

**Comment by ovbm** [comment]
![screen shot 2018-05-09 at 16 28 30](https://user-images.githubusercontent.com/20746301/39820510-407c128e-53a6-11e8-9351-e255da9b3f4f.JPG)
I really like this color scheme. The greens are friendly, the sea color is unobtrusive. The only thing I'd change is stronger outlines for countires, apart from that Iove it. Will make a test in the near future to try it out.

**Comment by corradio** [comment]
![image](https://user-images.githubusercontent.com/1655848/39925190-f2de296e-552a-11e8-8265-ef46f211e47f.png)

**Comment by brunolajoie** [comment]
That looks damn cool. The're just a bit of lack of contrast between a no-data country and the see.

**Comment by ovbm** [comment]
Proposal for a new bright mode:

![screen shot 2018-06-18 at 12 20 35](https://user-images.githubusercontent.com/20746301/41531391-76ed6ea0-72f3-11e8-8dd0-4fc8955c4284.JPG)

Some UI elements have also changed. Topbar was removed, some ui elements shifted. All in all the intention was to declutter the map-view and make it breath more.

**Comment by ovbm** [comment]
dark mode with the same Co2-coloration, ui changes and darker more blueish ocean color:

![screen shot 2018-06-18 at 12 21 28](https://user-images.githubusercontent.com/20746301/41531522-de7354f4-72f3-11e8-9aa6-d8d449da643b.JPG)

**Comment by brunolajoie** [comment]
imho,
- Color scale is better here
- Bright mode proposed here is a very elegant alternative to the current dark mode
- New dark mode feels darker & geekier. Would fit very well on a poor-quality projector presentation due to contrast between country and sea. But I would maybe miss a bit the old dark mode that was kinda softer.

**Comment by ovbm** [comment]
The color scale is continuous both on the current and the new versions. We've made the new scale a bit "harsher", so that only countries with intensities < ~100g are green.

**Comment by maxbellec** [comment]
love the bright colors, I think it should be the default one.
For the dark mode, I'm not sure which of the new or old one I prefer. I think on the new one, the colors are very bright, the yellow countries look radioactives!
As for the general layout, I also think it's a big improvement, it's super clean.

**Comment by corradio** [comment]
A big day today! We merged!
