### ISSUE TITLE
Favicon and App icon for electricitymap

### ISSUE THREAD

**Issue by bikiniweekend** [tmrowco/electricitymap#397]
Hi all.

We can share in this task different designs for favicon (browser icon when you add the webpage to favourites) and app icon. The final design will require different sizes, but for now it is enough with a small design (64x64 for example). Remeber using photoshop or similar to be able to edit it later and apply different sizes to the icon.

Feel free to discuss and contribute with designs or opinions about other designs.

**Comment by bikiniweekend** [comment]
Here my design:
![electricy_map_icon](https://cloud.githubusercontent.com/assets/25708827/23414302/bc8722aa-fddb-11e6-8e01-96ade6b006d1.png)

**Comment by Falke-Design** [comment]
Nice idea with the icons. 
Take this also as inspiration

![https://cloud.githubusercontent.com/assets/19800037/23762125/5c58e082-04f5-11e7-93ab-d1f950caedd1.gif](https://cloud.githubusercontent.com/assets/19800037/23762125/5c58e082-04f5-11e7-93ab-d1f950caedd1.gif)
![https://cloud.githubusercontent.com/assets/19800037/23762124/5c588e2a-04f5-11e7-963b-0d404eea1e35.gif](https://cloud.githubusercontent.com/assets/19800037/23762124/5c588e2a-04f5-11e7-963b-0d404eea1e35.gif)
![https://cloud.githubusercontent.com/assets/19800037/23762123/5c5804dc-04f5-11e7-952a-6237447fa83b.gif](https://cloud.githubusercontent.com/assets/19800037/23762123/5c5804dc-04f5-11e7-952a-6237447fa83b.gif)
![https://cloud.githubusercontent.com/assets/19800037/23762126/5c617ad0-04f5-11e7-839a-d4adcbccbeba.gif](https://cloud.githubusercontent.com/assets/19800037/23762126/5c617ad0-04f5-11e7-839a-d4adcbccbeba.gif)

**Comment by corradio** [comment]
A combination between this
![image](https://cloud.githubusercontent.com/assets/1655848/23822733/198e38ec-0653-11e7-8cb9-7e3d30ecbcf5.png)
and
![image](https://cloud.githubusercontent.com/assets/1655848/23822735/1ebe3588-0653-11e7-9d74-03ceefb79c3b.png)
could be nice

**Comment by Falke-Design** [comment]
Like this?

![https://cloud.githubusercontent.com/assets/19800037/23831293/9908a3f2-071e-11e7-9d13-fae7246ce086.gif](https://cloud.githubusercontent.com/assets/19800037/23831293/9908a3f2-071e-11e7-9d13-fae7246ce086.gif)
![https://cloud.githubusercontent.com/assets/19800037/23831295/99386a38-071e-11e7-9306-86efec84503e.gif](https://cloud.githubusercontent.com/assets/19800037/23831295/99386a38-071e-11e7-9306-86efec84503e.gif)
![https://cloud.githubusercontent.com/assets/19800037/23831294/99383360-071e-11e7-87b2-b3d54c741fd2.gif](https://cloud.githubusercontent.com/assets/19800037/23831294/99383360-071e-11e7-87b2-b3d54c741fd2.gif)

**Comment by corradio** [comment]
Did some brainstorm here:

![image](https://cloud.githubusercontent.com/assets/1655848/23834201/ba91beb2-0752-11e7-96bf-5cc55503682c.png)

**Comment by bikiniweekend** [comment]
I like the top-right one.
@Falke-Design @corradio lets choose one of them and then each one of us make a final design about it and we choose the winner between they three?

**Comment by corradio** [comment]
I'm quite fond of the top-right too :)

**Comment by Falke-Design** [comment]
May the best win! ;)

**Comment by bikiniweekend** [comment]
Hi mates. I made this one.

![tomorrow fav icon 1](https://cloud.githubusercontent.com/assets/25708827/23904833/8d93cd2e-08c9-11e7-8eee-6d4a99e380eb.png)
![tomorrow fav icon 2](https://cloud.githubusercontent.com/assets/25708827/23904834/8dd36e0c-08c9-11e7-8cb5-b221f3aec788.png)

Here you have the PSD if you wanna play with colors -> https://mega.nz/#!3Zoz0T5Q!G4B4UFMj_tkprdnmUnjOtUqQuakc3cdr2q0dvscc8qE

**Comment by Falke-Design** [comment]
I have made this one.

![lhttps://cloud.githubusercontent.com/assets/19800037/24046290/58619dc4-0b22-11e7-9ce3-04da1b3efd7b.gif](https://cloud.githubusercontent.com/assets/19800037/24046290/58619dc4-0b22-11e7-9ce3-04da1b3efd7b.gif)

First I have created also one with a map where lies but as favicon is this bad. 
We don't see the map then.

I have created a site to test the image as a favicon. There you see what I mean.
[http://voi.livetest.at/favicon/favicontest.html](http://voi.livetest.at/favicon/favicontest.html)

**Comment by ThierryOllivero** [comment]
Thanks for the tool @Falke-Design.

I liked the colorful ones from @bikiniweekend but they're not so great as Favicon. Probably better as "App Icon".
