### ISSUE TITLE
Explain CO2 model in ipython notebook

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#412]

**Comment by corradio** [comment]
I'll make one pass to write the equations.

**Comment by corradio** [comment]
First pass was made from my side.

**Comment by superlopuh** [comment]
Should the matrix at the end read [p_1+i_1 -i_1,2 -i_1,3 ...]? The sum of the imports is positive on the RHS in the previous equation.

**Comment by corradio** [comment]
Yes indeed you are right, all matrix inputs containing on only imports should be multiplied by -1. We should correct that when we get the chance.

**Comment by systemcatch** [comment]
Can this be closed?
