### ISSUE TITLE
Low font quality on Chrome Windows

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#420]
![image](https://cloud.githubusercontent.com/assets/1655848/23952747/ba839520-0992-11e7-9b89-05e3fba46f7f.png)

**Comment by scarlac** [comment]
It may be caused by the alpha-transparent background. Have a look at the mobile-map branch and see if it's any different.

**Comment by corradio** [comment]
I'm not able to reproduce but let's re-test using a PC once we have merged
the mobile-map branch!

**Comment by ThierryOllivero** [comment]
@corradio @scarlac I never had this problem, I used a lot of PCs and always Chrome on Windows 7 or 10. I would suggest to close it now that the mobile-map branch is merged.
