### ISSUE TITLE
New line in country profile

### ISSUE THREAD

**Issue by David-Lenoir** [tmrowco/electricitymap#421]
Hi!  I like your very nice map! An intersting line would be the delta import/export from the country, anabling to know if the country is actually self-suffisant or not! Thanks for your work!

David Lenoir
Conseiller en environnement, 
Suisse

**Comment by corradio** [comment]
Hi David,

Thanks for your message. We've had that suggestion several times. We haven't exactly figured out how to properly integrate it into the UI (see #371), but will keep your suggestion in mind!

Best,

Olivier

**Comment by David-Lenoir** [comment]
OK cool! I would suggest to simply add a "balance line" under the list of country importing/exporting.  
  
You could also add the net global consomption of the country?  
  
Thanks for your wonderfull tool!  
David
