### ISSUE TITLE
Investigate automatic update of capacities.

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#423]
Potential source: http://data.open-power-system-data.org/national_generation_capacity/

**Comment by corradio** [comment]
@brunolajoie will you be able to take a look at the data quality?

**Comment by corradio** [comment]
@brunolajoie shall we close this one or do you believe it can be done (and has value)?

**Comment by brunolajoie** [comment]
Closing it indeed, because many ENTSOE capacities are incorrect

**Comment by corradio** [comment]
@brunolajoie I think you misread. This would be an opportunity to use http://data.open-power-system-data.org/national_generation_capacity/ instead of ENTSOE, and automatically update capacities based on that. Re-opening but feel free to re-close if you believe the source if not good enough.

**Comment by brunolajoie** [comment]
Ah sorry!
Closing anyway due to country specificities that can't be automated (for instance, in some country, we split hydro storage from hydro without storage, but not in other, depending on ENTSOE spliting it or not)
