### ISSUE TITLE
Small upgrade idea

### ISSUE THREAD

**Issue by trsch** [tmrowco/electricitymap#424]
Dear electricity map,

We are a couple of guys following you page closely - great work! 

One thing we would like to see is a "ranking" on the pc-version, similar to that seen on the mobile version. 
Another cool feature on our wish-list, is some function for showing some statistics on production and emission during the last 24 hours/week/month. 

Best
Troels Schönfeldt
Another fan of you page!

**Comment by scarlac** [comment]
@trsch That's a great idea. We're working on re-building the UI so mobile users can also use the map. I think we could incorporate the ranking/highscore in the desktop as well. Thanks!

**Comment by corradio** [comment]
Hi Troels,

Thanks for this. For the ranking, please follow https://github.com/tmrowco/electricitymap/issues/193.
For the week/month history graph, please follow https://github.com/tmrowco/electricitymap/issues/427.

Best,

Olivier
