### ISSUE TITLE
Mobile version on Android freezes/is very slow

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#432]
Tested on my Nexus 5X. No errors in the console.

**Comment by ThierryOllivero** [comment]
No problem on my OnePlusOne (Android 6.0.1) neither on my Samsung Galaxy A52016 (Android 6.0.1).

Could it be related to Android 7.1.1, like for the friend of @brunolajoie ?

**Comment by corradio** [comment]
Maybe.

This block is causing the problem:

```js
// Render country map
    countryMap
        .data(d3.values(countries))
        .onSeaClick(function () { selectCountry(undefined); })
        .onCountryClick(function (d) { selectCountry(d.countryCode); })
        .render();
```

**Comment by corradio** [comment]
When disabling country rendering I get the same bug when I open the country ranking. Also I only see the first three flags.

Any idea @scarlac? At this point I'm suspecting troubles with SVG..

**Comment by ThierryOllivero** [comment]
https://greensock.com/forums/topic/15870-svg-draggable-chrome-android-problems/

The 5 last words of the URL make it look like you could be right...

**Comment by scarlac** [comment]
Unforunately I don't have a test unit. I did however try the map yesterday on an older android-based phone and it worked fine until you zoomed in.

**Comment by Agazoth** [comment]
How about an emulator? https://developer.android.com/studio/run/emulator.html

Should give the same result as the phone. The issue might be on Android 7.1.1

**Comment by Agazoth** [comment]
On Google pixel XL the issue only appears in Chrome. In Firefox the map works just fine and in Dolphin it works.

**Comment by corradio** [comment]
I pushed a fix. Please re-open if this still applies.
