### ISSUE TITLE
Convert prices to single currency

### ISSUE THREAD

**Issue by gregor-shapiro** [tmrowco/electricitymap#444]
For users to be able to compare with greater ease, an alternative to convert all electricity prices to a single currency would be a nice feature.

**Comment by corradio** [comment]
Those are possible solutions:
- http://openexchangerates.github.io/money.js/
- http://fixer.io/

**Comment by corradio** [comment]
Closing this as prices can't be compared, cf. https://github.com/tmrowco/electricitymap/issues/744
