### ISSUE TITLE
Electricity "production areas"

### ISSUE THREAD

**Issue by gregor-shapiro** [tmrowco/electricitymap#445]
Just as there are hydrological catchment areas and watersheds
![image](https://cloud.githubusercontent.com/assets/26760444/24442574/0c9727c4-145f-11e7-8621-7deaa80ef418.png)
Visualization of electrical energy production areas might be a nice feature. Instead of national (political) boundaries the boundaries of energy generation areas would be visible. The major electrical transport network would be a natural part of such a map.
![image](https://cloud.githubusercontent.com/assets/26760444/24443052/574af730-1461-11e7-975c-cb6429ca5585.png)

**Comment by corradio** [comment]
Indeed! We don't believe this is really of interest for the greater public, due to the complexity involved.
However, we would love to build it. We have so many things on our plates that we ideally would like to work with a commercial partner on this. If you can help, please ping me!
