### ISSUE TITLE
Add import/export coloring

### ISSUE THREAD

**Issue by b2000699** [tmrowco/electricitymap#449]
Hi,

It would be great to be able to add a color layer for the import/export ratios so to see if a country is currently importing or exporting more. E.g. exporting = green, importing = red, balanced = grey, or something like that.

Cheers

**Comment by brunolajoie** [comment]
Thanks for the suggestion. There are many things we could show in this map, such as consumption per capita, total emissions etc... but for simplicity purpose we want to keep the colors for GHG intensity of electricity.

**Comment by corradio** [comment]
Check out https://transparency.entsoe.eu/
