### ISSUE TITLE
Feature request: Add deeplinks for options activated

### ISSUE THREAD

**Issue by b2000699** [tmrowco/electricitymap#450]
Hi,

It would be great if the options that someone activates (e.g. wind power potential) would be integrated in the URL so that someone can share it with the recipient having the options on/off as the one that sent the link.

cheers

**Comment by corradio** [comment]
Interesting, that sounds doable.

**Comment by ThierryOllivero** [comment]
Wasn't it the case before? With wind=true or solar=true? Am I missing something?

T.

**Comment by corradio** [comment]
That was a flag to show or hide the checkbox that allowed you to activate it. It's different.
