### ISSUE TITLE
Feature request: Statistics: Add further options

### ISSUE THREAD

**Issue by b2000699** [tmrowco/electricitymap#451]
Hi,

For the moment I can see statistics for the CO2.
It would be great to:

1. Have more statistics, e.g. the % of Green energy / % of fossil fuels or the import/export balance over time or even only of a single source of energy, e.g. solar.
2. Have more scales in the statistics than only "last 24h", e.g. last week, month, year, current year, free date selection, etc.
3. Have the possibility to export these statistics

cheers

**Comment by b2000699** [comment]
p.s. and statistics for the entire EU/ Europe would be great, too!

**Comment by corradio** [comment]
We have those statistics, but they are part of our "premium reports" paid package. If you're interested, drop us a mail at hello@tmrow.co!

Olivier
