### ISSUE TITLE
Feature request: Further layers

### ISSUE THREAD

**Issue by b2000699** [tmrowco/electricitymap#452]
Hi,

It would be great to add further layers of coloring, e.g.:

1. Select one source of energy, e.g. solar power, and then have all countries colored according to their current amount of energy generated with that source. This way someone can quickly understand which sources of energy are dominant in the different countries.

cheers

**Comment by corradio** [comment]
Interesting idea. You're not the first one to come up with it.
Unfortunately we're struggling a bit with resources and we think it would clutter the map too much in terms of UX.
