### ISSUE TITLE
Impact CO2 transfrontalier

### ISSUE THREAD

**Issue by Pimsdidragonflex** [tmrowco/electricitymap#457]
Je me permets de vous soumettre une idée supplémentaire pour votre carte qui, à vrai dire, est déjà très intéressante. En effet, il serait intéressant de pouvoir visualiser l'impact éventuel des émissions carbone d'un pays sur l'autre en fonction des conditions climatiques au-dessus de l'Europe (données "vent" déjà intégrées à votre carte).

**Comment by Pimsdidragonflex** [comment]
Your map is already really attractive but i think that it will be interessant to show the cross-border CO2 impact.

**Comment by ThierryOllivero** [comment]
Bonjour @Pimsdidragonflex : 

Si j'ai bien compris votre point, cela correspond déjà à ce qu'on a lorsque vous cliques sur "Production Electrique par source". Cela ouvre une page avec les émissions par source: 

![image](https://cloud.githubusercontent.com/assets/22315693/24654281/40bea296-1939-11e7-86a8-0ae8ccc2f614.png)

**Comment by Pimsdidragonflex** [comment]
En fait, je ne sais pas si cela est envisageable mais il serait intéressant de pouvoir visualiser les émissions carbone et leur déplacement ou accumulation. Un peu à l'image de la carte ci-dessous: 
![emissionsdeco25](https://cloud.githubusercontent.com/assets/26895163/24664683/94bb6de4-195b-11e7-9085-a498f736cf4a.jpg)

**Comment by Pimsdidragonflex** [comment]
le CO2 n'ayant pas frontière. En effet, malgré les efforts et démarches engagés par un pays pour réduire son empreinte carbone, il peut être impacté par le CO2 généré par son voisin. La politique, la réponse à la problématique CO2 doit être commune.

**Comment by Pimsdidragonflex** [comment]
Après réflexion, cela est impossible car nous ne serions plus uniquement sur les émissions de CO2 liées à la production d'électricité mais nous engloberions toutes les activités génératrices de gaz à effet de serre. Désolé pour le dérangement.

**Comment by ThierryOllivero** [comment]
Pas de problème, la réflexion reste intéressante.

Au plaisir.
