### ISSUE TITLE
Bug? History chart: Time not correct, ie. time gap of 14 hours

### ISSUE THREAD

**Issue by b2000699** [tmrowco/electricitymap#459]
Hi,

I just noticed that there is a bug in the history charts of the countries, concerning the time shown:
When you go to the right, i.e. to "now" and then just go 1 step to the left into the past, already the first step is "14 hours ago". From then on the increments are 1h.

Is that a bug or intended to be like that?

Cheers

**Comment by corradio** [comment]
It's a bug, we'll look at it.
