### ISSUE TITLE
Investigate location-dependant gas CO2 intensity

### ISSUE THREAD

**Issue by brunolajoie** [tmrowco/electricitymap#468]
https://twitter.com/ReImagineGas/status/850647925277511680

**Comment by KetsOne** [comment]
I agree implementing this as a country-specific CO2 factor for natural gas should improve the accuracy.
Example for the Netherlands: https://www.rvo.nl/sites/default/files/2015/12/Nederlandse%20energiedragerlijst%20versie%20april_2015_def_0.pdf

But even then the way the technology used for generating the electricity from gas also plays a big role in the CO2 intensity if no fuel quantities are known.

**Comment by corradio** [comment]
Duplicate of #738
