### ISSUE TITLE
ENTSOE: UK data differed from that supplied by ELEXON. 

### ISSUE THREAD

**Issue by matt303** [tmrowco/electricitymap#474]
On the 12th April Elexon reported between 5 and 7GW of wind generation while entsoe which tmorowco uses as a data source reported around 2.5GW.

https://www.bmreports.com/bmrs/?q=generation/fueltype/current

**Comment by corradio** [comment]
@rustyb can you help?

**Comment by corradio** [comment]
@matt303 FYI I'm having a call with ENTSOE in the next days. I hope we will be able to set up some sort of process to solve data quality problems.

**Comment by corradio** [comment]
We have news: issue is identified and being fixed at National Grid. As soon as it gets fixed, CO2 will be updated (retroactively).

**Comment by corradio** [comment]
Dalius from ENTSOE said:

Regarding issue 474:
I asked data provider (ELEXON) to check and correct data. I have some doubts regarding wind on-shore data and it looks to me, that values on ENTSO-E TP are too low.
 
Feedback from National Grid that I received right now: We currently have a fault in our systems which is causing incorrect onshore wind values to be published.  We are trying to fix this urgently – hopefully it will be corrected very soon.

**Comment by corradio** [comment]
Seems to be fixed according to https://twitter.com/wombat361/status/864423663969464322?cn=cmVwbHk%3D&refsrc=email

**Comment by Dalius-ENTSO-E** [comment]
Just received update that ELEXON fixed issue on Friday. However, I compared data on TP and ELEXON web page and wind generation is significantly higher on TP (by ~600-2000MW). There is still something wrong with ELEXON wind production type data.

**Comment by corradio** [comment]
Thanks for the update @Dalius-ENTSO-E, I'm re-opening this issue then.

**Comment by Dalius-ENTSO-E** [comment]
Explanation about differences on ELEXON and TP is that only metered generation is reported on ELEXON web page (normally >100MW). Data on TP is more complete that includes also metered and estimated small scale wind generation. Historical period should be updated with correct values during next few days.

**Comment by corradio** [comment]
Very interesting. @Dalius-ENTSO-E can you close the issue unless there something else you wish to investigate?

**Comment by Dalius-ENTSO-E** [comment]
I think, we explained the difference. I suggest to close this issue.
