### ISSUE TITLE
Scaling exchange arrows by intensity

### ISSUE THREAD

**Issue by allocater2** [tmrowco/electricitymap#477]
Would be nice, if the exchange arrows would scale by how much is exchanged. Could be a logarithmic scale to get a good overview. Something like:

2000MW = 125% of current scale
1000MW = current scale
500MW = 75% of current scale
100MW = 50% of current scale

**Comment by corradio** [comment]
Hi @allocater2 
I like the idea, but unfortunately this won't play nicely with the different zoom factors.

- Olivier
