### ISSUE TITLE
Update numbers for hydropower CO2

### ISSUE THREAD

**Issue by amaurea** [tmrowco/electricitymap#480]
I contacted the author of the Norwegian study, Ingunn Modahl, and asked her if she had data for other countries. Here is a translation of her answer. But the summary is:

* Norway: 2.4 g CO2-eq/kWh (not 1.9 g as I said before)
* Sweden: 9 g CO2-eq/kWh (weird that the difference is so big)
* Average for Europe in general: 5.8 g CO2-eq/kWh

Anyway, her response:

----------------------

It's not strange that there are large differences in emissions from hydropower in different countries. There are emissions from construction of infrastructure, operation and inundation (plus distribution). Emissions from infrastructure and operation do not vary much, but emissions from inundation can can vary extremely much based on vegetation, temperature and climate zone. It's there not unnatural that the contribution from inundation is different in for example Norway and Sweden.

The inundation-emissions are also rather uncertain because different methods of estimation may have been used. So there is still need for more research. We have based our data on research by Sintef when it comes to Norwegian conditions (performed in Follsjø, part of the Trollheim power plant).

Our report, which you refer to, is based on analysis of 11 Norwegian hydropower plants. 9 of these were done by us here at Østlandsforskning. By using these as the basis for Norwegian production in general (by weighting reservoir and run-of-the-river plants and 1. and 2. lifecycle), we have arrived at the average value of 2.4 g CO2-equivalent per kWh. This consists of 0.95 g CO2-eq/kWh from infrastructure and operation and 1.44 g CO2-eq/kWh from inundation (a pure reservoir power plant would have gotten the value of 1.9 g CO2-eq/kWh from inundation, in addition to infrastructure and operation). http://ostfoldforskning.no/media/1056/734-1.pdf

We have made EPDs (third party investigations) for thee Norwegian plants. Two of these are part of the Norwegian average we estimated above, while one was analyzed after this report was finished. You can find these EPDs here: Norwegian EPs: http://epd-norge.no/energi/category332.html

* Trollheim (Statkraft) from 2013: Infrastructure and operation: 2.71 g COw-eq/kWh (inundation emissions were not available at the time that report was made, and are therefore not included): http://epd.nsp01cp.nhosp.no/getfile.php/EPDer/Energi/NEPD-010_Trollheim_en.pdf
* E4 (Embretsfoss power plants) from 2013: Infrastructure and operation 2.19 g CO2-eq/kWh (inundation again not available for this plant): http://epd.nsp01cp.nhosp.no/getfile.php/EPDer/Energi/NEPD_168E_Hydroelectricity-from-E4-Power-Station.pdf
* Skjerka (Agder Energi) from 2016: Infrastructure and operation: 0.9 g CO2-eq/kWh. Inundation: 1.8 g CO2-eq/kWh. Total: 2.7 g CO2-eq/kWh. http://epd.nsp01cp.nhosp.no/getfile.php/EPDer/Energi/NEPD-449-300-EN_Hydroelectricity-from-Skjerka-power-station.pdf

Vattenfall in Sweden has also done a fair bit of work on LCA of their hydropower plants. Here are some numbers:
* LCA-report: Infrastructure and operation: 9 g CO2-eq/kWh: https://www.vattenfall.com/en/file/Livscykelanalys_-_Vattenfalls_elproduktion_i_Norden_11336961.pdf [Amaurea note: I think this number includes inundation, based on the explanatory note for Hydropower on page 18].
* Vattenfall EPD (average of 14 Nordic plants): Total 10 g COw-eq/kWh, of which 7.1 g CO2-eq/kWh is due to inundation, and 2.9 g CO2-eq/kWh from infrastructure, operation and distribution: http://gryphon.environdec.com/data/files/6/7470/epd88en_2015-02-15.pdf

As background data we also use LCA-data from the Swiss database Ecoinvent, which also contains data for hydropower. These are based on Swiss data, which was then modified for each country and geography. You can see the average emission for European hydropower production here (table 4, page 12): http://www.reliable-disclosure.org/upload/259-D5.2_Best_Practice_Environmental_Data.pdf

-----------------------

The weighted average CO2-eq/kWh for European hydropower from the last link she provided is 5.8 g CO2-eq/kWh. It should be pretty safe to use this for any European country for which no better data is available. Also note that the correct Norwegian number is 2.4 g CO2-eq/kWh, not 1.9 g CO2-eq/kWh. The latter only included inundation, not other sources of emission.

**Comment by corradio** [comment]
@brunolajoie can you take a look?

**Comment by brunolajoie** [comment]
Dear @amaurea,

Thanks a lot for your inputs on Hydro. To move faster, we are desperately looking for a table of carbon intensity factor per type power plant, per EU country, in LCA, CO2eq/kWh. Such meta analysis would avoid us having dozen of (potentially conflicting) sources! See main issue #738 

Related to eco-invent and your mentioned study http://www.reliable-disclosure.org/upload/259-D5.2_Best_Practice_Environmental_Data.pdf, I've come to understand that such table exists. But I haven't been able to find it on their report, nor on eco-invent DB. Would you happen to know if we could by any chance find it, or ask the author to kindly provide it to us?

Best regards,
Bruno

**Comment by corradio** [comment]
@amaurea @brunolajoie are we still investigating this?
It seems like #738 would fix this.

**Comment by brunolajoie** [comment]
Indeed! closing this to focus on the other. thanks!
