### ISSUE TITLE
Localize "Map View" and "List View"

### ISSUE THREAD

**Issue by magol** [tmrowco/electricitymap#481]
The buttons "Map View" and "List View" in the mobile app is not able to localize. 

![image](https://cloud.githubusercontent.com/assets/493140/25103101/82407dfc-23bb-11e7-8696-e3261cd2930f.png)

**Comment by corradio** [comment]
Hi @magol , take a look at https://github.com/tmrowco/electricitymap/commit/c5b312dc6dca2d92654476b73264569fa9909f92 in order to see how to translate!
