### ISSUE TITLE
Emission factors are misleading

### ISSUE THREAD

**Issue by kristianmadsen88** [tmrowco/electricitymap#484]
Hi,

First of all - I love this map and use the app often.

However, I find your use of emission factors wrong and misleading. 

Your source is IPCC's life-cycle emission calculations. These are based on worldwide averages and can vary considerably from place to place for the same energy source. E.g. coal has varying carbon content and are utilized at plants with (highly) varying efficiencies.

Furthermore, it is not standard practice to use life-cycle emissions for calculating emissions related to electricity production (also not by IPCC).

I am sure you are aware of these issues and have chosen this method out of convenience and lack of specific country data. This is just a shame since you have very specific and precise data on energy flows. But keep in mind that your results do not get more accurate than your weakest data - which are your emission factors. This is especially a problem if you want to provide people with knowledge about their carbon footprint from electricity consumption - this method is simply misleading.

A good example of the problem is on coalpower in Denmark. Here all coalpower is produced on combined heat and power plants, which means that the emissions should be allocated between the heat and electricity production respectively. By using the IPCC factors you highly overestimate the emissions allocated to electricity. 

I would suggest to use the emission factors from the 2006 IPCC Guidelines: https://www.ipcc.ch/meetings/session25/doc4a4b/vol2.pdf
And combine them with average plant efficiencies for each country (fossil plants).

This means that all renewables (incl. bioenergy) and nuclear will have zero emissions. 

If you really want to use life cycle emissions - you will need to separate emissions related to the value chain and emissions from direct combustion. This means that you can still use the emission factors from IPCC for renewables and nuclear (however bioenergy is complicated).

Best regards,
Kristian

**Comment by KetsOne** [comment]
Kristian,

I agree with your assessment.
However, i would like to add the following notes and suggestions.

From an ideal perspective we would like to use these LC factors, but i concur that using regular emission factors that only cover the generation part is a preferable option. Important reasons are:
a) Emission factors in general, but Life-Cycle emission factors especially are hugely dependent on the assumptions made and region and thus have the potential to report actual emissions incorrect.  
b) Comparison with other sources of emission data (API, EIA, IEA etc.)

But the most important consideration might be the actual purpose of the website and the data displayed on it. Is it just for information and 'scientific entertainment' or is the intention that companies or governments use this are a basis for their own annual reporting or for developing policy?
In the first case, these LC emission factors might still be the way to go, but in the second case, more detail is needed to increase accuracy to bring a higher level.
I would like to propose using country-specific emission factors per technology.

General reliability of the emission factors in IPCC 2006 dataset is fairly good. All factors are fitted to 95% confidence interval. The input data used is data reported by countries for their formal reporting to UNFCCC. As a side note, current units displayed on website are CO2eq/kWh. This implies that N2O and CH4 (and perhaps more substances) are also included. IPCC emission factors for N2O and CH4 from stationary combustion are notoriously uncertain. How is this dealt with currently? (please refer to section 2.4.1 of the IPCC document you link to)

Depending on the available real-time input data, a more accurate model might be required to present a reliable picture of actual stationary combustion emissions. It would be fun to contribute to this.

**Comment by ovotom** [comment]
Generally there are also a variety of emissions for any fossil  fuel station type within a country. As demand goes up, so does the price, and less efficient plant tends to turn on, as such your estimate of CO2 will tend to be high if anything. (if you use the average efficiency of all constructed plants to calculate the C02, only when all those plants are in use will there be that much C02 out, the rest of the time, more efficient plants will be on, so the C02 output will be less.)

**Comment by corradio** [comment]
@brunolajoie what do you think we should do here?

**Comment by brunolajoie** [comment]
*Relative* values for c-intensity between two countries are more important for our project rather than *absolute* values. 

Therefore, for the question to choose between LCA vs. Direct Emissions, I'd like to arbitrate once we find a proper database of carbon-intensity per type of power plant that distinguishes country one another. Lets follow up this discussion on #738
