### ISSUE TITLE
No way to return to default screen once you click on "Show ranking"

### ISSUE THREAD

**Issue by ipekarik** [tmrowco/electricitymap#492]
After clicking on "Show ranking" (&page=highscore), there's no way to return to the default screen with the colour coding legend and option selectors. (&page=map)

**Comment by corradio** [comment]
On the desktop you can do that by clicking on the sea.
I'll fix that.

**Comment by ipekarik** [comment]
Yes, that works! But it didn't even occur to me to try clicking on the sea until you mentioned it. :D I guess just changing the "show ranking" button to "hide ranking", or something similar, would be more intuitive.
