### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by HansHug** [tmrowco/electricitymap#493]
Very interesting! Thanks. 
would be great to have 
1. total power generated in each country
2. total import (+) / export (-) of each country
3. running integrated powers from Jan 1st to actual date, i.e. energy per source and total for each country
4. integrated powers from Jan 1st to actual date, i.e. energy per source and total for each country
5. 3.&4. per winter and  summer half year.

This may help politicians to better understand the energy (electricity part) problems that society faces, - and possible contribute to better descisions:
 1. solar & wind should  in ADDITION to nuclear but NOT to replace NUCLEAR before the summer/winter storage problem is solved and no fossil fuel ist burned anymore!
2. solar should be in the south (not subsidized in nothern countries)
3. wind should be where it makes sense, i.e. not in Switzerland
4. solar and wind should predominantly be used to generate gas (H2 and possibly Methan). this can be stored (!!!) and transported with (almost existing infrastructure, converted to electricity when needed to solve the summer/winter problem. Gas can also be used for cars. Note that if all cars (if possible - whi it is not) were replaced by electric (battery) cars, the summer/winer problem increases, there is not sufficient electricity/power lines for charging, AND there is not enough Li available for the batteries ... apart from the cost. So power to gas is the (ultimate) solution to solve the summer/winter problem, to replace fossil fuels (look at the desaster in Germany - the biggest source of polution in Europe - in spite of Solar), and finally become truely green and sustainable!

Note: some countries invest in Nuclear AND Solar/Wind! Among them are the USA and China! So why not in  Germany and Switzerland?

**Comment by corradio** [comment]
Hi Hans,

The data you are requesting is actually part of our premium reports. If you're interested in the data, let me know.
We believe showing a realtime view (+ the last 24h) is enough for raising awareness.

Best,

Olivier
