### ISSUE TITLE
Add zoom in / zoom out button

### ISSUE THREAD

**Issue by ThierryOllivero** [tmrowco/electricitymap#504]
Hello,

With the new map, we start with an unzoomed view. By double clicking somewhere, it zooms in. Then, you cannot zoom out. 

We could add a zoom in / zoom out button somewhere, to help with the navigation.

**Comment by kandunoori** [comment]
Zoom out can be done using Shift double click, however this seems d3 (Data-Driven Documents) functionality that need to incorporate in UI.
**Zoom in** - Double Click
**Zoom out** - Shift Double Click
