### ISSUE TITLE
Map issue, Australia ACT needs to be moved into Australia NSW

### ISSUE THREAD

**Issue by superlonglong** [tmrowco/electricitymap#510]
ACT is part of the NSW region according to the National Energy Market. therefore it should be included in the map as such.

**Comment by corradio** [comment]
Do you confirm that ACT and NSW are merge together in the NSW region according to NEM?

**Comment by superlonglong** [comment]
Are you looking for proof? 
https://en.wikipedia.org/wiki/National_Electricity_Market

"The NEM comprises five regions, with the ACT being in the NSW region."

**Comment by corradio** [comment]
That's pretty unequivocal. I'll make sure to merge the regions then!

**Comment by systemcatch** [comment]
I think all ACT plants have been merged to NSW so this can be closed.
