### ISSUE TITLE
Add Australian small scale solar

### ISSUE THREAD

**Issue by superlonglong** [tmrowco/electricitymap#511]
Small scale solar is a significantly large proportion of solar in australia.

Details on installed capacity can be found here

https://d284f79vx7w9nf.cloudfront.net/attachments/analysis/7/states.csv

from http://pv-map.apvi.org.au/historical#4/-26.67/134.12

production data can be found here

http://pv-map.apvi.org.au/live

**Comment by adamtbeames** [comment]
Breaking it down further into postcode areas would be helpful too.
Data available from http://www.cleanenergyregulator.gov.au/DocumentAssets/Documents/Postcode%20data%20for%20small-scale%20installations%20-%20SGU-Solar.csv

**Comment by MariusKroon** [comment]
The last page shows a small overview of production per fueltype, including small scale solar generation. There is a redirect to http://www.nem-watch.info/widgets/RenewEconomy/ - it could be a good source as datafeed for all Australian territories.

**Comment by corradio** [comment]
I've already talked to the guys at nem watch and they don't have an API :/

**Comment by MariusKroon** [comment]
The apvi.org.au website delivers solar data for all states except the northern territory, the map is populated from http://pv-map.apvi.org.au/data/2017-06-25 - the url only work using the current date. The time series contain generation data for solar on a 5 minute interval. 
{"ts":"2017-06-25T00:15:00Z","nsw":479,"qld":718,"sa":113,"tas":14,"vic":165,"wa":62}, 
{"ts":"2017-06-25T00:20:00Z","nsw":460,"qld":735,"sa":121,"tas":14,"vic":160,"wa":70}

@corradio Is it possible to have multiple scrapers for one area in place? The current scrapers for Australia already collect solar, and should the values from apvi be added that value, or is the value from apvi the one and only value for solar?

**Comment by corradio** [comment]
I think we should edit the current parsers and add this new API. We should however make sure that we can indeed sum the two values.

**Comment by jarek** [comment]
I would work on integrating data from pv-map.apvi.org.au if no one else is doing it right now

**Comment by corradio** [comment]
go for it!

**Comment by jarek** [comment]
(still working on this, sorry it's taking a while, but should be able to have it done soon)
