### ISSUE TITLE
Increase zoom-by-pinching intensity to match google map

### ISSUE THREAD

**Issue by brunolajoie** [tmrowco/electricitymap#513]
On my macbookPro/chrome, the pinching intensity is about 2/3 time smaller than that of google map. It makes the map a bit painful to use and I suggest to increase it to zoom-to-pinch ratio.

**Comment by corradio** [comment]
It seems like you can't decouple the scroll and pinch speeds.
Google actually has a very sensitive scroll zoom, translating to a "normal" pinch speed.
If you try to scroll zoom in GMaps, you'll see that it's much more sensitive than on the EM.
Should we increase the sensitivity on the EM?
