### ISSUE TITLE
Remove from Australia (South Australia) Northern, Playford B

### ISSUE THREAD

**Issue by superlonglong** [tmrowco/electricitymap#514]
All Coal power generators in South Australia have closed. Therefore there is no Coal generation capacity in South Australia.

The graph needs to be updated.

**Comment by corradio** [comment]
We get the capacities from this file:
http://services.aremi.nationalmap.gov.au/aemo/v3/csv/all
I would be reluctant to add a list of things to exclude from this CSV.
Maybe we can contact someone to update it at the source?

**Comment by superlonglong** [comment]
There are a few that will need to be removed as they are closed. i looked at the CSV, and noticed that they don't have "-" in the current output column that they are out of action. this differs from other generators which have a "0"

unfortunately you will have to rule them out manually as there are a bunch of generators (especially smaller ones) that have a "-" next to them

they are 

Hazelwood
Playford B
Northern

I havent checked to see if there are other plants that need to be removed

**Comment by corradio** [comment]
ok let's start a list of closed plants then. I'll add the ones you
mentioned.

Olivier

**Comment by superlonglong** [comment]
@corradio 

i checked the other power stations that have closed, they have been removed from the list.

these power stations may be removed in time.
