### ISSUE TITLE
Potential Issue with Australia - Tasmania to Victoria interconnector

### ISSUE THREAD

**Issue by superlonglong** [tmrowco/electricitymap#517]
Might the interconnector be showing the wrong direction?

Last night the connector was showing export from tasmania @$223 to victoria @$68, which would make the transmission company a loss of $155/MWH

As most companies don't wish to make a loss when they can avoid it, might we have the direction mixed up?

**Comment by superlonglong** [comment]
http://reneweconomy.com.au/tasmanian-government-cap-state-power-prices-95485/

This link says we have the direction the wrong way around.

**Comment by corradio** [comment]
Indeed they seem to be in the wrong direction.

![image](https://cloud.githubusercontent.com/assets/1655848/25608337/c32f6a70-2f1a-11e7-92c8-688fdccc8e7a.png)

![image](https://cloud.githubusercontent.com/assets/1655848/25608350/c99ad2a0-2f1a-11e7-8bb8-4b52f12bb76f.png)

**Comment by superlonglong** [comment]
Looks like the bug is back

@corradio

**Comment by corradio** [comment]
This is increadibly confusing.
What is the correct interpretation of the TAS->VIC interconnector?
![image](https://cloud.githubusercontent.com/assets/1655848/25742915/17813e72-3192-11e7-9361-317f0ffa35d6.png)

Right now a negative value from TAS->VIC means exchange from VIC to TAS. Where can we access to ground truth?

**Comment by superlonglong** [comment]
I have looked a little further, it would appear that there was a spike to $200 in tas, so the direction is correct, even though the price looks the other way. give it another 30 mins and see how it looks.

where did you get those images from?

**Comment by corradio** [comment]
aemo.com.au/Electricity/National-Electricity-Market-NEM/Data-dashboard#nem-dispatch-overview

**Comment by superlonglong** [comment]
yeah that should be accurate.

must have had a trip in tas, price spiked, and had the official price looking strange.

you can close this again now.

**Comment by corradio** [comment]
ok! good we clarified this.
