### ISSUE TITLE
Wind bar no longer showing wind potential at mouse cursor

### ISSUE THREAD

**Issue by superlonglong** [tmrowco/electricitymap#518]
you used to be able to see what the wind was at your cursor by turning on wind and moving your mouse around. this is broken now.

**Comment by superlonglong** [comment]
not sure this has  been fixed on chrome, windows 7

**Comment by corradio** [comment]
It's not pushed to production yet. It will be in a few minutes :)
Deployment information are sent to Slack on #electricitymap

**Comment by superlonglong** [comment]
Good news. Works beautifully.
