### ISSUE TITLE
With & Without CO2 trades

### ISSUE THREAD

**Issue by DZafirakis** [tmrowco/electricitymap#527]
You could also include what the national CO2 factor looks like, with and without electricity trade...Check out our article on that...A more static version :) http://www.sciencedirect.com/science/article/pii/S0306261914013117

**Comment by corradio** [comment]
Hi @DZafirakis ,

It seems to me that this would be exploring a potential scenario where there is no trade. Quite interesting, but the map in this current state should only show a "real" view of the system right now.
Thanks for sharing though!

**Comment by DZafirakis** [comment]
Hi @corradio 

Now you give one value for carbon intensity per country. Does this include electricity trade or is it based on local production alone? This is what I propose. Having two values to demonstrate the impact of electricity trade on the national carbon intensity...Best

**Comment by corradio** [comment]
Hello @DZafirakis ,

Yes indeed it does take into account trade. See https://github.com/tmrowco/electricitymap/blob/master/CO2eq%20Model%20Explanation.ipynb
