### ISSUE TITLE
Realtime total electricity production Netherlands

### ISSUE THREAD

**Issue by TogetherForLess** [tmrowco/electricitymap#528]
You can find the realtime total electricity production in the Netherlands at this site

[http://www.tennet.eu/nl/elektriciteitsmarkt/data-dashboard/productie/](url)

The theoretical production of renewables here
[http://energieopwek.nl/](url)

**Comment by corradio** [comment]
Hello @TogetherForLess,
We already have an issue to cover NL: #78
Unfortunately the data sources you mention won't help, as they don't give us a live breakdown of the generation.
