### ISSUE TITLE
South Australia is broken

### ISSUE THREAD

**Issue by superlonglong** [tmrowco/electricitymap#529]
South Australia no longer displays generation as of 4 hours ago.

Now no longer links to http://services.aremi.nationalmap.gov.au/aemo/v3/csv/all

Interconnector still works.

**Comment by corradio** [comment]
It's because the coal production is unknown, and therefore it does not pass our data quality filter.
Any idea if SA should have a coal production?

**Comment by superlonglong** [comment]
thats not right.

All coal power plants have been closed in SA.

https://en.wikipedia.org/wiki/Playford_B_Power_Station
 Playford B was mothballed in 2012 and its permanent closure was announced by operator Alinta Energy in October 2015. 

https://en.wikipedia.org/wiki/Northern_Power_Station_(South_Australia)
 The plant ceased electricity production in May 2016 and decommissioning is underway.

Notice of demolition works
http://flinderspower.com.au/news/media-release-re-northern-power-station-site-demolition/

**Comment by corradio** [comment]
Great, I'll add that information to the parser then. Any other production mode we can, for sure, set to 0?

**Comment by superlonglong** [comment]
Nuke, Geothermal.

For South Australia, there isnt any hydro either.

**Comment by corradio** [comment]
Noted. SA should be back now.
