### ISSUE TITLE
realtime production in Bulgaria

### ISSUE THREAD

**Issue by TogetherForLess** [tmrowco/electricitymap#530]
I think you can find the real time electricity production in Bulgaria at this site

[http://tso.bg/default.aspx/page-707/bg](url) 

but my Bulgarian isn't so good  :)

**Comment by corradio** [comment]
That's interesting. ENTSOE already gives us data, but slightly delayed:

![image](https://cloud.githubusercontent.com/assets/1655848/25738545/0add9224-317e-11e7-931b-140f2d59749c.png)

**Comment by Dalius-ENTSO-E** [comment]
We are checking with Bulgarian TSO which production types should be not expected and when this data submission delay can be reduced. Waiting for feedback from ESO.

**Comment by corradio** [comment]
Thanks for looking into this!

**Comment by Dalius-ENTSO-E** [comment]
clarification from ESO: About data submission delay for Aggregated Generation per Type ESO send files every hour but the data is collected 4 times per day, i.e. 1:00, 6:00, 12:00 and 20:00.
Unfortunately we cannot change this in the near future.

**Comment by corradio** [comment]
@Dalius-ENTSO-E any idea where they get this (apparently real-time) data feed?
http://tso.bg/default.aspx/page-707/bg

**Comment by ultibo** [comment]
Hello, I can write a parser for bulgaria based on that page if it's worth it and no one is working on it ? 
http://tso.bg/default.aspx/page-707/bg
Apparently it's not working right now and the ENTSOE website gives only N/A

Should I proceed ? Let me know

![image](https://user-images.githubusercontent.com/5710280/29251863-7c47c5aa-805d-11e7-938c-aa96ae03e1ff.png)

![image](https://user-images.githubusercontent.com/5710280/29251879-af74d3aa-805d-11e7-9dee-fc66637acc3a.png)

**Comment by corradio** [comment]
Good job @ultibo ! Is it possible to update the parser to make sure it returns an array of past values instead of only the latest one?

**Comment by ultibo** [comment]
Hello, thanks. 
I wrote a parser based on http://tso.bg/default.aspx/page-707/bg that was merged this morning #682, I don't think I have access to anything other than realtime data, you know where i can find daily history ?

**Comment by corradio** [comment]
Mmh not sure. I think that's fine for now! I'm closing this issue. Thanks @ultibo !
