### ISSUE TITLE
Add other environmental indicators

### ISSUE THREAD

**Issue by lvandepaer** [tmrowco/electricitymap#531]
Hello, 

Would you be interested to add complementary environmental indicators in addition to CO2 emissions and/or update the actual ones? Typical examples of other categories are : smog formation, ozone layer depletion, human toxicity, land occupation, metal depletion etc.

Let me know,

**Comment by corradio** [comment]
Hi,
Thanks for the idea. For now we don't think it would make sense, but if someone wants to make such a project we would really love that!

Olivier
