### ISSUE TITLE
ALL Australia is broken

### ISSUE THREAD

**Issue by superlonglong** [tmrowco/electricitymap#533]

**Comment by corradio** [comment]
It seems like the CSV we use (http://services.aremi.nationalmap.gov.au/aemo/v3/csv/all) was updated.
Also it seems like new stations were added. Can you help me map them to the proper state?
cc @snoblenet

feeder_1         | WARNING: station Yambuk Wind Farm does not belong to any state
feeder_1         | WARNING: station Braemar Power Station does not belong to any state
feeder_1         | WARNING: station Braemar Power Station does not belong to any state
feeder_1         | WARNING: station Braemar Power Station does not belong to any state
feeder_1         | WARNING: station Hunter Valley Gas Turbine does not belong to any state
feeder_1         | WARNING: station Mt Mercer Wind Farm does not belong to any state
feeder_1         | WARNING: station Bendeela / Kangaroo Valley Power Station does not belong to any state
feeder_1         | WARNING: station Snowtown Wind Farm Units 1 to 47 does not belong to any state
feeder_1         | WARNING: station Uranquinty Power Station does not belong to any state
feeder_1         | WARNING: station Uranquinty Power Station does not belong to any state
feeder_1         | WARNING: station Uranquinty Power Station does not belong to any state
feeder_1         | WARNING: station Uranquinty Power Station does not belong to any state
feeder_1         | WARNING: station Moranbah North Power Station, Grosvenor 1 Waste Coal Mine Gas Power Station does not belong to any state
feeder_1         | WARNING: station Hornsdale Wind Farm does not belong to any state
feeder_1         | WARNING: station Barcaldine Solar Farm does not belong to any state
feeder_1         | WARNING: station Hornsdale Wind Farm 2 does not belong to any state

**Comment by superlonglong** [comment]
On mobile atm, will do.

**Comment by snoblenet** [comment]
Is it possible to change the matching algorithm to a fuzzy/regex match instead of an exact match? New power stations come and go and are officially renamed very slowly, but who knows how quickly AREMI changes the identifiers in the names column? Busy for the next two days but I might be able to progress this Sunday Australian time.

**Comment by superlonglong** [comment]
how can i submit this easiest? is there a table you want me to fill?

**Comment by corradio** [comment]
You can see the existing table here:
https://github.com/tmrowco/electricitymap/blob/master/parsers/AU.py#L38
You can either submit a pull request to change that file, or you can just send us the changes here.

**Comment by corradio** [comment]
@snoblenet yes we could do regexp!

**Comment by superlonglong** [comment]
feeder_1 | WARNING: station Yambuk Wind Farm does not belong to any state,VIC
feeder_1 | WARNING: station Braemar Power Station does not belong to any state,QLD
feeder_1 | WARNING: station Braemar Power Station does not belong to any state,QLD
feeder_1 | WARNING: station Braemar Power Station does not belong to any state,QLD
feeder_1 | WARNING: station Hunter Valley Gas Turbine does not belong to any state,NSW
feeder_1 | WARNING: station Mt Mercer Wind Farm does not belong to any state,VIC
feeder_1 | WARNING: station Bendeela / Kangaroo Valley Power Station does not belong to any state,NSW
feeder_1 | WARNING: station Snowtown Wind Farm Units 1 to 47 does not belong to any state,SA
feeder_1 | WARNING: station Uranquinty Power Station does not belong to any state,NSW
feeder_1 | WARNING: station Uranquinty Power Station does not belong to any state,NSW
feeder_1 | WARNING: station Uranquinty Power Station does not belong to any state,NSW
feeder_1 | WARNING: station Uranquinty Power Station does not belong to any state,NSW
"feeder_1 | WARNING: station Moranbah North Power Station, Grosvenor 1 Waste Coal Mine Gas Power Station does not belong to any state",QLD
feeder_1 | WARNING: station Hornsdale Wind Farm does not belong to any state,SA
feeder_1 | WARNING: station Barcaldine Solar Farm does not belong to any state,QLD
feeder_1 | WARNING: station Hornsdale Wind Farm 2 does not belong to any state,SA

**Comment by superlonglong** [comment]
So i discovered i dont know how to upload csv.

**Comment by corradio** [comment]
That's good enough thanks!
