### ISSUE TITLE
Numerous issues in australia

### ISSUE THREAD

**Issue by superlonglong** [tmrowco/electricitymap#535]
Gas isnt showing in QLD,
Hydro isnt showing in QLD or VIC
Wind isnt showing in VIC

**Comment by corradio** [comment]
Seems like the names in the CSV changed again:

feeder_1         | WARNING: station Barcaldine Power Station does not belong to any state
feeder_1         | WARNING: station Bendeela / Kangaroo Valley Pumps does not belong to any state
feeder_1         | WARNING: station Ararat Wind Farm does not belong to any state
feeder_1         | WARNING: station Teralba Power Station does not belong to any state
feeder_1         | WARNING: station Jindabyne Small Hydro Power Station does not belong to any state
feeder_1         | WARNING: station Basslink HVDC Link does not belong to any state
feeder_1         | WARNING: station AGL SITA Landfill1 Kemps Creek does not belong to any state
feeder_1         | WARNING: station Bankstown Sports Club Plant Units does not belong to any state
feeder_1         | WARNING: station Basslink HVDC Link does not belong to any state
feeder_1         | WARNING: station Nine Network Willoughby Plant does not belong to any state
feeder_1         | WARNING: station Mugga Lane Solar Park does not belong to any state
feeder_1         | WARNING: station Eildon Pondage Hydro Power Station does not belong to any state
feeder_1         | WARNING: station Barcaldine Power Station does not belong to any state
feeder_1         | WARNING: station Bendeela / Kangaroo Valley Pumps does not belong to any state
feeder_1         | WARNING: station Ararat Wind Farm does not belong to any state
feeder_1         | WARNING: station Teralba Power Station does not belong to any state
feeder_1         | WARNING: station Jindabyne Small Hydro Power Station does not belong to any state
feeder_1         | WARNING: station Basslink HVDC Link does not belong to any state
feeder_1         | WARNING: station AGL SITA Landfill1 Kemps Creek does not belong to any state
feeder_1         | WARNING: station Bankstown Sports Club Plant Units does not belong to any state
feeder_1         | WARNING: station Basslink HVDC Link does not belong to any state
feeder_1         | WARNING: station Nine Network Willoughby Plant does not belong to any state
feeder_1         | WARNING: station Mugga Lane Solar Park does not belong to any state
feeder_1         | WARNING: station Eildon Pondage Hydro Power Station does not belong to any state
feeder_1         | WARNING: station Barcaldine Power Station does not belong to any state
feeder_1         | WARNING: station Bendeela / Kangaroo Valley Pumps does not belong to any state
feeder_1         | WARNING: station Ararat Wind Farm does not belong to any state
feeder_1         | WARNING: station Teralba Power Station does not belong to any state
feeder_1         | WARNING: station Jindabyne Small Hydro Power Station does not belong to any state
feeder_1         | WARNING: station Basslink HVDC Link does not belong to any state
feeder_1         | WARNING: station AGL SITA Landfill1 Kemps Creek does not belong to any state
feeder_1         | WARNING: station Bankstown Sports Club Plant Units does not belong to any state
feeder_1         | WARNING: station Basslink HVDC Link does not belong to any state
feeder_1         | WARNING: station Nine Network Willoughby Plant does not belong to any state
feeder_1         | WARNING: station Mugga Lane Solar Park does not belong to any state
feeder_1         | WARNING: station Eildon Pondage Hydro Power Station does not belong to any state

with a new production mode

feeder_1         | WARNING: key Landfill / Biogas is not supported
feeder_1         | WARNING: key Hydro is not supported

**Comment by superlonglong** [comment]
Ugh! Perhaps we should change the unique key to the shorter power station
code?
