### ISSUE TITLE
Add Taiwan

### ISSUE THREAD

**Issue by Liang** [tmrowco/electricitymap#544]
I found the open data from the Taiwan Power.

Web Page:
http://www.taipower.com.tw/content/new_info/new_info_in.aspx?LinkID=27
API: (Encode issue)
http://data.taipower.com.tw/opendata01/apply/file/d006001/001.txt

**Comment by corradio** [comment]
It would be nice to:
- Add capacities inside the parser, and remove it from the static json file
- Understand what Pumping load and Pumping gen means. Is it storage?

**Comment by MariusKroon** [comment]
The capacities could easily be extracted and reported back from the request URL. In the current parser they are discarded. Can the capacities be made part of the dictionary that is returned by fetch_production or is there a fetch_capacity function ?

**Comment by corradio** [comment]
Juste add a dict `capacity` that has the same format as the `production` one 👍

**Comment by MariusKroon** [comment]
Plenty of room for improvement in the code - I'll see if I can pull this one off :)

**Comment by MariusKroon** [comment]
Capacities in there now - could be closed since no transfers to other countries or prices on site.

**Comment by corradio** [comment]
Closing!
