### ISSUE TITLE
missing translation in tooltip

### ISSUE THREAD

**Issue by magol** [tmrowco/electricitymap#545]
Please make it possible to translate ["**of CO2eq per minute**"](https://github.com/tmrowco/electricitymap/blob/master/web/app/tooltip.js#L22), see image below
Maybe we should change the unit to CO<sub>2</sub>eq too?

![image](https://cloud.githubusercontent.com/assets/493140/26017399/9a01e9be-3769-11e7-90a5-afc13c16d0cb.png)

**Comment by corradio** [comment]
Of course! Will do it as soon as I have a bit of time.
Feel free to also just add it yourself by a pull request.

On Fri, May 12, 2017 at 11:29 PM, Magnus Österlund <notifications@github.com
