### ISSUE TITLE
New Zealand Parser

### ISSUE THREAD

**Issue by BobGrun** [tmrowco/electricitymap#547]
In the parser of New Zealand, the information on Gas energy (given on the source) are not read.
Since this is nearly 1/3 of the total energy (on the north island), the resulting total energy is wrong.

In order to fix, the following lines must be added to the two different blogs:

'gas': productions.get('Gas', {'generation': 0.0})['generation'],

'gas': productions.get('Gas', {'capacity': 0.0})['capacity'],

Cheers,
Bob
![image](https://cloud.githubusercontent.com/assets/24443218/26042814/598a0842-398c-11e7-91a8-e6a46884550c.png)

**Comment by adamtbeames** [comment]
@BobGrun it looks like Gas and Coal are bundled together at the moment:

'coal': productions.get('Gas/Coal', {'generation': 0.0})['generation'],
'coal': productions.get('Gas/Coal', {'capacity': 0.0})['capacity'],

You might consider cloning the repo and submitting a pull request.
