### ISSUE TITLE
Circular gauges for territory header

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#552]
![image](https://cloud.githubusercontent.com/assets/1655848/26057354/98ad81a6-3979-11e7-920d-ecd94ad87f51.png)

Would be nice to use a circular gauge to better show % fossil fuel and carbon intensity, for example (I don't like the style though):
![image](https://cloud.githubusercontent.com/assets/1655848/26057370/ad20f212-3979-11e7-9cd9-63fe3886a438.png)

Example:
https://codepen.io/rogerxu/pen/rLqvd

**Comment by corradio** [comment]
More inspiration: http://gallery.echartsjs.com/editor.html?c=xB1N7IfL1Z

**Comment by corradio** [comment]
![image](https://user-images.githubusercontent.com/1655848/28104908-8798aa26-66dd-11e7-995c-c9bdb47c9e60.png)

**Comment by corradio** [comment]
Also see http://unfccc.int/paris_agreement/items/9485.php

**Comment by brunolajoie** [comment]
Love the idea of a circular gauge! makes perfect sense for a 0-100% indicator such as "% low-carbon" and "% renewable"
