### ISSUE TITLE
Lithuania - Sweden Exchange Arrow disappears sometimes

### ISSUE THREAD

**Issue by allocater2** [tmrowco/electricitymap#559]
It's this connection:

https://transparency.entsoe.eu/transmission-domain/physicalFlow/show?name=&defaultValue=false&viewType=TABLE&areaType=BORDER_CTY&atch=false&dateTime.dateTime=23.05.2017+00:00|CET|DAY&border.values=CTY|10YLT-1001A0008Q!CTY_CTY|10YLT-1001A0008Q_CTY_CTY|10YSE-1--------K&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)

It might be because this connection fills up all future numbers with "0" whereas all other connections fill up future numbers with "-". To see this, jump to "today" if you read this after 2017.05.23. It might only disappear during a certain portion of the hour when the current hour hits a reporting line with double "0".

edit: might be related to the "Swedish export disappears bug" because all of Swedish connections fill up future numbers with "0".

**Comment by corradio** [comment]
If a current value is 0, then the arrow is hidden.
Indeed, future valued should be "-" instead of 0. This would show the last valid value instead.

**Comment by corradio** [comment]
@Dalius-ENTSO-E can you help us here? Seems to be the same issue as https://github.com/tmrowco/electricitymap/issues/556#issuecomment-305692294

**Comment by Dalius-ENTSO-E** [comment]
testing solution today for SE-LT on test platform. if this will be fine, I will apply changes on production next week.

**Comment by corradio** [comment]
You don't realise how many users you will make happy @Dalius-ENTSO-E !

**Comment by Dalius-ENTSO-E** [comment]
task #1 on Monday. If all fine, then the fix will be done for all borders, not only for the border with LT.

**Comment by Dalius-ENTSO-E** [comment]
cross border physical flows are ok now for country and control area levels.

**Comment by corradio** [comment]
Thank you @Dalius-ENTSO-E ! 
@allocater2 feel free to re-open the issue if it happens again
