### ISSUE TITLE
How to provide exchange CO2 intensities when unknown

### ISSUE THREAD

**Issue by jarek** [tmrowco/electricitymap#563]
The Canadian province of Prince Edward Island generates only wind electricity (outside of emergencies), and imports electricity from New Brunswick otherwise.

Unfortunately we don't currently have real-time production breakdown for New Brunswick. Based on historical data from Statistics Canada, it is on the order of 300 gco2eq/kwh. (~32% nuclear, ~20% hydro, ~4% wind, remainder various fossils - I will provide more details on how I got the number.)

In absence of information on generation in New Brunswick, https://api.electricitymap.org/v1/state reports CA-PE's exchangeCo2Intensities from CA-NB as 12 gco2eq/kwh, so it assumes that the import is the same as the local generation. In this edge case this is pretty off, and most of the time draws PEI unreasonably green.

As far as I can tell the code behind api.electricitymap.org is not open source, so I can't find how exactly it determines the exchangeCo2Intensities.

Can you tell us if there is a way to specify CO2 intensity of an export in a way that the API will understand, short of hardcoding a value for New Brunswick current generation?

(I also have calculated the intensity for Quebec at around 28 gco2eq/kwh - they are vast majority hydro - that could help Ontario's imports be more accurate, especially if/when Ontario imports more in the summer. Currently that's assumed to be the same as Ontario generation, which will go up when air conditioning season starts and their gas peakers turn on.)

**Comment by corradio** [comment]
Hi @jarek 
I can make the necessary changes, probably here:
https://github.com/tmrowco/electricitymap/blob/master/config/co2eq_parameters.js

Do you have any public trustable source/report that we can use to document the use of those specific intensities?

**Comment by jarek** [comment]
I'm working on writeup/jupyter notebook of how to estimate the Canadian intensities - will update when done :)

**Comment by jarek** [comment]
Here is the notebook: https://gist.github.com/jarek/bb06a7e1c5d9005b29c63562ac812ad7 and the write-up with links to the Statistics Canada data tables: http://piorkowski.ca/rev/2017/06/canadian-electricity-co2-intensities/

Around 300 to maybe 400 g for New Brunswick exports (depending on how conservative we want to be) should do it :). I'll try to agitate for proper real-time data in Canada...

**Comment by corradio** [comment]
Will work on this as soon as I get the chance. Good job for pushing this forward @jarek !

**Comment by jarek** [comment]
Hi @corradio do you think this will be possible soon?

**Comment by corradio** [comment]
Yes I'll do that this weekend. Thanks for reminding me.

Olivier

**Comment by corradio** [comment]
Working on this now

**Comment by corradio** [comment]
Hi @jarek, 
I've looked at this extensively, and currently we don't have an easy way to solve it because there is currently no way to hardcode a carbon intensity without having it colour the country on the map.
I think it would be pretty bad to start colouring countries based on hardcoded intensities as it will shift our map away from real-time.
Unfortunately I see no easy way around this other than to update our backend to differentiate between values used for computation and for display, but that would require a significant amount of work.

I'm closing this for now but feel free to re-open if you see a quick fix that I did not see.

Olivier

**Comment by systemcatch** [comment]
I think this is still worth doing as some countries like Namibia look good but in reality import electricity from South Africa which is heavily coal based. However it's clearly not a simple thing to implement so think of it as 'nice to have' rather than 'must do'.

**Comment by jarek** [comment]
I agree this would be nice if possible. Logically this seems equivalent to assuming an intensity for "unknown" production based on statistics of production in past few years. But it requires changes in backend I'm not familiar with.

It seems that zones have three properties:
- carbon intensity
- percent renewable
- percent low-carbon

In particular, when importing, the percent renewable and low-carbon of the source are taken into account when computing the properties of the importer.

It seems that the best way would be to allow specifying approximate values for those three properties for a zone being imported from with unknown production, along with source for this data. Optimally this would be displayed somewhere in the UI, without actually colouring the zone.

Some places this would make more accurate:
- Namibia
- Georgia gets around 10% from Azerbaijan
- New England gets around 10% of supply from Quebec which is almost entirely hydro
- the chain from Quebec into New Brunswick and Prince Edward Island (PEI being rather inaccurate whenever it's not very windy)
- possibly Manitoba exports to MISO, if we happen to find the export value but not Manitoba production data
- this could be used to cleanly specify intensity of Kaliningrad exports

This is not well suited for interconnected areas, where we know a zone with unknown production imports from one neighbour and exports to another, since carbon intensity then also significantly depends on the zone's production level. Current examples are Croatia and Belarus.

**Comment by corradio** [comment]
What about someone submits a PR with changes in co2eq_parameters.js for a test case and then we can start seeing if we can make a quick win on the backend on our side?

**Comment by corradio** [comment]
Should be good now!

**Comment by jarek** [comment]
:tada: 

I also found a source with 2016 Canadian data, including for New Brunswick https://www.neb-one.gc.ca/nrg/ntgrtd/mrkt/nrgsstmprfls/nb-eng.html - will make a PR for NB soon then, and let's find values for Namibian imports :+1:

**Comment by alixunderplatz** [comment]
Some figures for Namibia's neighbours for 2015 from IEA: 
- [Zambia](https://www.iea.org/statistics/statisticssearch/report/?country=ZAMBIA&product=electricityandheat&year=2015) had 98% hydro 2% oil
- [South Africa](https://www.iea.org/statistics/statisticssearch/report/?country=SOUTHAFRIC&product=electricityandheat&year=2015) had 91.5% coal, 5% nuclear, 1.5% hydro, 1%wind, 1% solar

Wind and solar might have increased in South Africa, but rather insignificantly.
