### ISSUE TITLE
Add data for South America

### ISSUE THREAD

**Issue by jarek** [tmrowco/electricitymap#566]
South America generally has decentralized/privatized electricity markets, which might lend itself to real-time reporting.

In addition, someone went through and added a whole bunch of information to Wikipedia: from https://en.wikipedia.org/wiki/Category:Electric_power_in_South_America, follow links to "Electricity sector in [country]" articles that might be good starting points: they have external links to regulators, energy ministries, etc.

I created a separate issue for Argentina, which seems very doable: https://github.com/tmrowco/electricitymap/issues/565

Other results of my exploration, not yet fully suitable:
* Brazil has quite interesting breakdown of generation, but I only see daily data, uploaded with a day's delay, unfortunately not realtime http://www.ons.org.br/resultados_operacao/SDRO/Diario/index.htm
* biggest utility in Uruguay (covering about 50-60% of the country's generation) has a lovely graph http://portal.ute.com.uy/novedad/suministro-la-demanda-0 but I haven't found chart with the same data yet

**Comment by j3j5** [comment]
I think the data for Uruguay can be found here http://www.ute.com.uy/SgePublico/ConsComposicionEnergeticaXFuente.aspx
There is an endpoint which can export the data to `.xls`, but I'm not sure it isn't just easier to scrape the site ¯\_(ツ)_/¯

**Comment by corradio** [comment]
Great @j3j5 . I'm opening up a new issue for this one: #598

**Comment by systemcatch** [comment]
Searching around I've found data for Panama but unfortunately it is for the previous day only.  It has good breakdown by type and hour.  I'll leave the link for future reference in case things change.
https://www.cnd.com.pa/index.php

**Comment by jarek** [comment]
Other related issues:
#671 Bolivia
#655 Chile
#591 Peru

And elsewhere in Latin America:
#658 Guatemala
#617 Costa Rica
#605 Dominican Republic

**Comment by corradio** [comment]
I'm closing this one to favour opening issues for individual countries
