### ISSUE TITLE
monthly or annual average

### ISSUE THREAD

**Issue by mpsteenstrup** [tmrowco/electricitymap#573]
first thank you for this wonderful applet. As a physics teacher I use it to show from which energy sources our energy comes from. A natural question is weather the momentary picture is representative for the countries production. 

If it is possible a toggle to se some aggregated data would be very instructive.

hope that it is possible,

best regards Mads Peter Steenstrup, physics teacher Rysensteen Gymnasium, Denmark.

**Comment by corradio** [comment]
Hi Mads Peter,

Happy to see that this is used in classes in Denmark! We're already working on those issues, see #427 and #83. It's going to be part of a paid premium offering, but we're investigating whether or not it should be free for academia/schools. Either way, we'll probably make some aggregated analysis that we'll throw around the internet that you'll be able to use.
For now: I suggest you subscribe to the two other issues.

Have a nice day,

Olivier

**Comment by mpsteenstrup** [comment]
Thank you for the fast reply. 

Mads Peter Steenstrup, Frederiksberg
