### ISSUE TITLE
Map should be screenshot friendly

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#574]
Screenshots taken in the past should have a timestamp associated.
This means removing the X minutes ago in favor of a time + date.

![image](https://user-images.githubusercontent.com/1655848/26885104-ee8a65dc-4ba1-11e7-82de-8216203d073f.png)

**Comment by scarlac** [comment]
A few points comes to my mind:
- Almost all phones carry a clock, so only date would be necessary.
- To shorten "a few seconds ago" it's worth considering staying with something like "June 5, Now" or "June 5, Just updated" and if last update is older than a threshold, it should use the server data stamp, not device time, so screenshots reveal actual data.

**Comment by corradio** [comment]
That's a very good idea!
