### ISSUE TITLE
Add data for Ukraine

### ISSUE THREAD

**Issue by MariusKroon** [tmrowco/electricitymap#575]
For the Ukraine the link https://ua.energy/diyalnist/dyspetcherska-informatsiya/dobovyj-grafik-vyrobnytstva-spozhyvannya-e-e/  could be used. 
My Ukrainian (Russian?) is really bad, not sure what exactly is mentioned on the site.

**Comment by corradio** [comment]
Maybe @scottlee120 can help?

**Comment by jarek** [comment]
In top right there is a link to switch it to English.

The chart works with one Ajax POST call to get a JSON list, very workable.

My Cyrillic is poor, but I take the codes to be:
NPP/"aes" in JSON: nuclear
RES/"vde" in JSON: wind
HPP/"gesgaes": hydro
"consumptiongaespump": hydro storage - negative when water is being pumped
"tec" and "tes" are thermal - tec is cogeneration

Thermal generation is mostly coal per Wikipedia - can probably assume all tec and tes is coal?

**Comment by jarek** [comment]
Throwing https://ru.m.wikipedia.org/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_%D1%82%D0%B5%D0%BF%D0%BB%D0%BE%D0%B2%D1%8B%D1%85_%D1%8D%D0%BB%D0%B5%D0%BA%D1%82%D1%80%D0%BE%D1%81%D1%82%D0%B0%D0%BD%D1%86%D0%B8%D0%B9_%D0%A3%D0%BA%D1%80%D0%B0%D0%B8%D0%BD%D1%8B into translator says all of tes/ТЭС is coal, tec/ТЭЦ is specified about 50% capacity gas, some coal, some unknown.

**Comment by Dalius-ENTSO-E** [comment]
Please note, that ETNSO-E is working to add data for Moldova and Ukraine in near future. We are testing internally new area concept at the moment and we should deploy this new concept on our test platform next week.

**Comment by corradio** [comment]
Great @Dalius-ENTSO-E ! Can you keep us updated? Thanks.

**Comment by corradio** [comment]
Let's re-open when ENTSOE gets data
