### ISSUE TITLE
ENTSOE: Estonia disappeared

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#576]
@Dalius-ENTSO-E do you know why?

**Comment by Dalius-ENTSO-E** [comment]
yes, Elering is not reporting anymore actual generation per production type data. I will warn them and I will provide you some update tomorrow

**Comment by Dalius-ENTSO-E** [comment]
data submission has been restored. Elering should upload missing data for the period 9/6 18:00 - 13/6 11:00 . So, Estonia is back

**Comment by corradio** [comment]
Hurray! Thanks :)
