### ISSUE TITLE
Idea: Annual averages

### ISSUE THREAD

**Issue by eteyssan** [tmrowco/electricitymap#580]
Hi team,

Well done on putting this together, it is a brilliant tool!

Unless you already have it and I have simply missed it, I was wondering if you could have an option to show annual averages for grid carbon intensity?

Thanks!

**Comment by corradio** [comment]
Hi @eteyssan.
Definitely on our roadmap - but will be part of the "pro" version of the product.

Olivier

**Comment by corradio** [comment]
Duplicate of #763
