### ISSUE TITLE
ENTSOE: Denmark data is offline

### ISSUE THREAD

**Issue by jarek** [tmrowco/electricitymap#582]
Since at least Thursday (15 June) evening European time.

If it's a problem with data not making it to ENTSOE, do we know if there is a list of outages that are known to ENTSOE and that they expect to resolve within a short period?

**Comment by jarek** [comment]
Norway data also missing since 00:01 UTC 17 June

**Comment by corradio** [comment]
@Dalius-ENTSO-E do you have any insights?

**Comment by MariusKroon** [comment]
Data is back again, but historically there are still some timestamps missing on the ENTSO-e site

**Comment by jarek** [comment]
To answer my question, https://transparency.entsoe.eu/news/widget has updates about missing Denmark data posted on 16.06.2017 and then about it being back on 21.06.2017, so we could check there if data is missing.

**Comment by corradio** [comment]
I'm closing this because data is back
