### ISSUE TITLE
Add regional data for the US

### ISSUE THREAD

**Issue by daniel-callejas-sevilla** [tmrowco/electricitymap#584]
From a [reddit comment](https://www.reddit.com/r/dataisbeautiful/comments/6hzgmf/live_map_over_co2_emissions_from_electricity_in/dj2mgcs/?context=3), 

[Here's the live data at a regional level](https://www.eia.gov/beta/realtime_grid/#/status?end=20170618T12) for the US.

**Comment by jarek** [comment]
Hi Daniel,

Thanks for the link. U.S. regional integration was previously discussed as part of #143. Last update on that was that it was problematic more on the display level than on the data level - the system operator area borders are really tough to map and draw accurately. Hopefully it can happen sometime though!

**Comment by corradio** [comment]
Indeed, check #143.
The main problem is to figure out if we split depending on the regions given by the data (less user friendly) or if we split by state (data is harder to find).
Let's keep the discussion on #143
