### ISSUE TITLE
Australia PV production capacity not reflecting reality

### ISSUE THREAD

**Issue by jkfm** [tmrowco/electricitymap#586]
Apparently, the PV capacity in Australia shows only utility-scale plants. The actual capacity is much bigger: http://pv-map.apvi.org.au/historical#4/-26.67/134.12

Should we include it or was it excluded on purpose as there would be no real-time production data? What about scaling?

**Comment by corradio** [comment]
Hi @jkfm ,

This is definitely related to #511 . Production is being excluded right now because we don't have data for it. Let's continue the discussion on #511
