### ISSUE TITLE
Split lang.json into separate files for each language.

### ISSUE THREAD

**Issue by magol** [tmrowco/electricitymap#588]
[lang.json](https://github.com/tmrowco/electricitymap/blob/master/web/app/configs/lang.json) has begun to become quite big now when more and more languages have arrived, it has become harder to find in the file. And you can not see when there are changes in the source language (English) or if an commit only concerns another language. You must go through each commit to see what changes affect English. I wish the file is divided into one file per language.

Then I do not really understand why [lang.json](https://github.com/tmrowco/electricitymap/blob/master/web/app/configs/lang.json)  is separated from the files in [/web/locales](https://github.com/tmrowco/electricitymap/tree/master/web/locales).
Is it not possible to merge lang.json with this files or at least keep them in the same place?

**Comment by corradio** [comment]
Agreed. Will take care of this when I get a bit of time.

**Comment by corradio** [comment]
Allright so we need to merge both locale files. Some keys will be user by the node server to generate markup. Others will be used by the javascript bundle.
I'm not sure how to tell webpack to require all files in the locales directory though.
One solution could be to make one bundle per language.
