### ISSUE TITLE
Add 🇺🇾 Uruguay

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#598]
Thanks to a tip from @j3j5, I found this link:
http://www.ute.com.uy/SgePublico/ConsPotenciaGeneracionArbolXFuente.aspx
I'll write a parser :)

**Comment by corradio** [comment]
Can anyone help in understand if the interconnections mean import or export when positive?

![image](https://user-images.githubusercontent.com/1655848/27438391-63d22dd8-5765-11e7-8a3c-7f2a39d91f81.png)

**Comment by j3j5** [comment]
I'm sorry, I have no idea, my guess is that positive means export, but I couldn't be sure. On the other hand... is this page useful? http://www.ute.com.uy/SgePublico/ConsBalance.aspx

I see there's an endpoint there to feed to the highcharts graph returning a json.

**Comment by corradio** [comment]
Actually I can see that Salto Grande is a hydro dam in Argentina, counted both as interconnection and as a part of hydro. So the interconnections are imports.
However, do you know if there's a direct cable from the hydro dam to UY? In this case, we should count a direct import of hydro, and not an import of the average mix from Argentina.

**Comment by j3j5** [comment]
Actually it isn't that simple, [Salto Grande](https://en.wikipedia.org/wiki/Salto_Grande_Dam) is a hydro dam shared between Argentina and Uruguay.

**Comment by corradio** [comment]
Yes so we can assume that everything bought from (not necessarily produced from) Salto Grande is hydro power, and not an import (that would have a mix equal to the one of Argentina)
