### ISSUE TITLE
ENTSOE: PL->UA exchange is missing

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#602]
Hello @Dalius-ENTSO-E ,

![image](https://user-images.githubusercontent.com/1655848/27489081-88f7e146-5839-11e7-80d3-87d9d39b3838.png)

It seems like there's two exchanges between PL and UA. It seems like the one with id `10YUA-WEPS-----0` is missing (whereas it is working with all other exchanges to/from UA), whereas the one with `10Y1001A1001A869` works. The above screenshot makes me think there could be a mistake because there shouldn't be two entries in the list?

Thanks for your help.

Olivier

**Comment by Dalius-ENTSO-E** [comment]
No, all is correct. Let me explain what is there. PL have lines with 10YUA-WEPS-----0 (Burshtyn island) but all lines are disconnected. There is only one active connection between PL and UA (DobTPP island). DobTPP is working through one line to PL and flow can be only from UA-DobTPP to PL. This is why data is not expected for one direction (PL>UA-DobTPP) and data exists only for direction UA-DobTPP (10Y1001A1001A869 ) > PL . 
We are testing new area concept to UA on our test platform and names on UA areas will change soon.

**Comment by corradio** [comment]
Hi @Dalius-ENTSO-E,

Thanks for the explanation. We are working on a country-level for PL and UA (and neighbouring countries).
For PL, we use the identifier `10YPL-AREA-----S`
For UA, there are two country identifiers `10Y1001A1001A869` and `10YUA-WEPS-----0`.
We use `10YUA-WEPS-----0` because it has data for HU, RO and SK.
Shouldn't there be only one identifier, thus enabling us, with a single UA identifier, to fetch the exchanges between UA and neighbouring countries?

**Comment by Dalius-ENTSO-E** [comment]
Aggregation of commercial schedules on country level is implemented only for Germany. We will add aggregation of commercial schedules on country level for all countries starting from 1/1/2018. 
There will be only one identifier for UA only when we will change area concept for UA. btw., EIC code for country and bidding zone UA will be 10Y1001C--00003F . 
Currently, there are 2 identifiers for UA: 10YUA-WEPS-----0 for (WEPS) borders with HU, RO and SK, and 10Y1001A1001A86 for the border with PL. These EIC codes will remain on control area level.

**Comment by corradio** [comment]
Thanks for the clarification.
