### ISSUE TITLE
works some weeks ago, but now

### ISSUE THREAD

**Issue by rregn** [tmrowco/electricitymap#611]
with new browsers i get only:

Fehler 113 (net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH): Unbekannter Fehler.

with very old browsers there is no such error, but no funtionality
please provide a unsecured access !

**Comment by corradio** [comment]
Hi @rregn . Thanks for raising this.
This SSL problem shouldn't happen.
Can you tell me which browser, version and operating system you use?

**Comment by corradio** [comment]
Hi @rregn please re-open if you still have this issue
