### ISSUE TITLE
Properly manage storage UI

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#616]
![image](https://user-images.githubusercontent.com/1655848/27996857-e20df626-64eb-11e7-9937-547a362d7465.png)

- [ ] Properly verify co2 model for produced storage electricity
- [ ] Fix UI
- [ ] Check all parsers

**Comment by brunolajoie** [comment]
My bad, it's my local dataset that is out of date. Can you send me the latest CSV ? Do you store them somewhere? You showed me how to do it but i forgot the comand line!

**Comment by corradio** [comment]
Look in your command history (using ctrl+r or `history|grep scp`)

My command is:
scp 'olivier.corradi@146.148.127.137:/home/shared/electricitymap/data_export/*'
.
