### ISSUE TITLE
add Costa Rica

### ISSUE THREAD

**Issue by jarek** [tmrowco/electricitymap#617]
I researched this but probably won't have time to work on it in next 10 days, so putting the resources here in case someone is looking for a parser to implement:

Main website with links: https://appcenter.grupoice.com/CenceWeb/CenceMain.jsfm

Current demand: https://appcenter.grupoice.com/CenceWeb/CenceCurvaDemandaSEN.jsf?init=true

Production: https://appcenter.grupoice.com/CenceWeb/CencePosdespachoNacional.jsf
- change date to current day to see today's data
- as far as I can tell, "6:00" means "between 6:00 and 6:59", data is available with about a 15 minutes delay after the hour ends
- unit is MWh but since it's shown for an hour's duration, the value can be taken verbatim
- needs to be mapped to type (using data from operator or local government or Wikipedia or NGO resources?)

Interchange: https://appcenter.grupoice.com/CenceWeb/CenceIntercambiosRegionalesSEN.jsf?init=true

See also regional flows and per-country generation/demand in realtime at http://www.enteoperador.org/newsite/flash/SER.html (Flash required)

**Comment by mlucchini** [comment]
@jarek I'm on it. I'll try to implement this today.

**Comment by mlucchini** [comment]
For the record, interchange is presented with Flash indeed and the data itself is at: http://www.enteoperador.org/newsite/flash/data.csv

**Comment by mlucchini** [comment]
List of power stations that need to be classified into {biomass, coal, gas, hydro, nuclear, oil, solar, wind, geothermal}:
Aeroenergía (wind)
Altamira
Angostura
Arenal (hydro)
Balsa Inferior
Barranca
Barro Morado
Bijagua
Birris12
Birris3
Boca de Pozo
Cachí
Campos Azules
Canalete
Caño Grande
Caño Grande III
Cariblanco
Carrillos
Chiripa
Chocosuelas
Chucás
CNFL
Cubujuquí
Daniel Gutiérrez
Dengo
Don Pedro
Doña Julia
Echandi
El Angel
El Angel Ampliación
El Embalse
El General
El Viejo
Garabito
Garita
Guápiles
Hidrozarcas
Intercambio Norte
Intercambio Sur
La Esperanza (CoopeL)
La Joya
Los Negros
Los Santos
Matamoros
Miravalles I
Miravalles II
Miravalles III
Miravalles V
Moín II
Moín III
MOVASA
Orosí
Orotina
Otros
Pailas
Parque Solar Miravalles
PE Mogote
PEG
Peñas Blancas
Pirrís
Plantas Eólicas
Platanar
Poás I y II
Pocosol
Reventazón
Río Lajas
Río Macho
San Antonio
San Lorenzo (C)
Sandillal
Suerkata
Taboga
Tacares
Tejona
Tilawind
Torito
Toro I
Toro II
Toro III
Tuis (JASEC)
Valle Central
Vara Blanca
Ventanas-Garita
Vientos de La Perla
Vientos de Miramar
Vientos del Este
Volcán

**Comment by jarek** [comment]
Here's a partial classification. I think the hydro plants cover most of the generation, so can someone try plugging these classifications in and seeing how much production remains as unknown?

Sources:
wikipedia: https://en.wikipedia.org/wiki/List_of_power_stations_in_Costa_Rica
geo: http://globalenergyobservatory.org/form.php?pid=2353 and links in "hydro in Costa Rica" link box
enipedia: http://enipedia.tudelft.nl/wiki/Costa_Rica/Powerplants
industcards: http://www.industcards.com/hydro-costa-rica.htm, http://www.industcards.com/wind-costa-rica.htm

Plants:

Aeroenergía (wind)
Altamira
Angostura - hydro (wikipedia)
Arenal (hydro)
Balsa Inferior
Barranca - diesel per http://www.industcards.com/cc-c-america.htm
Barro Morado
Bijagua
Birris12 - hydro (geo)
Birris3 - hydro (geo)
Boca de Pozo - geothermal per http://www.industcards.com/geo-cent-am.htm
Cachí - hydro (wikipedia)
Campos Azules
Canalete
Caño Grande - hydro (enipedia)
Caño Grande III - hydro (enipedia)
Cariblanco - hydro per http://en.centralamericadata.com/en/search?q1=content_en_le%3A%22Hydroelectric+Cariblanco%22
Carrillos - hydro (geo)
Chiripa
Chocosuelas - hydro (geo)
Chucás
CNFL
Cubujuquí
Daniel Gutiérrez - hydro (industcards)
Dengo - possibly hydro listed in wikipedia as Corobici and geo as "Corobici (Miguel Pablo Dengo) Hydroelectric Power Plant"; listed as hydro named "Miguel Dengo Benavides" aka Corobici in industcards
Don Pedro - hydro (geo)
Doña Julia - hydro (industcards)
Echandi
El Angel
El Angel Ampliación
El Embalse
El General - hydro (industcards)
El Viejo
Garabito - heavy oil per http://www.industcards.com/ic-central-am.htm
Garita - hydro (geo)
Guápiles - 675 g/kwh per enipedia (-> unknown thermal)
Hidrozarcas
Intercambio Norte - interchange to the north
Intercambio Sur - interchange to the south
La Esperanza (CoopeL)
La Joya - hydro (wikipedia)
Los Negros
Los Santos
Matamoros
Miravalles I - geothermal (wikipedia)
Miravalles II - geothermal (wikipedia)
Miravalles III - geothermal (wikipedia); confirmed by http://www.industcards.com/geo-cent-am.htm
Miravalles V - geothermal (wikipedia); confirmed by http://www.industcards.com/geo-cent-am.htm
note: Miravalles might have a solar photovoltaic part as well, per enipedia - deduce which is which from production at night and during the day
Moín II - oil/diesel (wikipedia, http://www.industcards.com/ic-central-am.htm / http://www.industcards.com/cc-c-america.htm)
Moín III - diesel oil (wikipedia, http://www.industcards.com/cc-c-america.htm)
MOVASA
Orosí - wind (wikipedia, industcards)
Orotina
Otros
Pailas
Parque Solar Miravalles - solar from name
PE Mogote
PEG
Peñas Blancas - hydro (wikipedia)
Pirrís - hydro (wikipedia)
Plantas Eólicas - wind from name
Platanar - hydro (industcards)
Poás I y II
Pocosol
Reventazón - hydro (wikipedia)
Río Lajas
Río Macho - hydro (wikipedia)
San Antonio - 571 g/kwh per enipedia (-> unknown thermal)
San Lorenzo (C) - hydro (industcards)
Sandillal - hydro (wikipedia)
Suerkata
Taboga - biomass (enipedia)
Tacares
Tejona - wind (industcard)
Tilawind - wind from name
Torito - hydro (industcards)
Toro I - hydro: http://globalenergyobservatory.org/form.php?pid=5749
Toro II - hydro (wikipedia)
Toro III
Tuis (JASEC) - hydro (enipedia)
Valle Central - wind (enipedia, industcards)
Vara Blanca
Ventanas-Garita - hydro (wikipedia)
Vientos de La Perla
Vientos de Miramar
Vientos del Este
Volcán - hydro (http://globalenergyobservatory.org/form.php?pid=5106, industcards)

**Comment by systemcatch** [comment]
I've mapped most of the plants using google and wikipedia.  There's a few that I haven't found any info on.
[plant mapping](https://gist.github.com/systemcatch/8cf05aeae16718c6bf37997cfbb7043d)

**Comment by jarek** [comment]
ref #656

**Comment by mlucchini** [comment]
FYI Will update this PR today. Thanks for the power station classification!

**Comment by systemcatch** [comment]
As discussed with @jarek it looks like the parser is returning the totals for the day as data for the upcoming hour (which currently has no data).  See below for an example of the last dict returned in the array just now.

`{'capacity': {}, 'countryCode': 'CR', 'storage': {}, 'datetime': datetime.datetime(2017, 8, 13, 8, 0, tzinfo=tzfile('/usr/share/zoneinfo/America/Costa_Rica')), 'source': 'grupoice.com', 'production': {'coal': 0.0, 'geothermal': 914.68000000000006, 'oil': 0.0, 'solar': 0.14999999999999999, 'unknown': 329.65000000000003, 'nuclear': 0.0, 'gas': 0.0, 'biomass': 0.0, 'wind': 635.99999999999977, 'hydro': 5709.3999999999987}}`

**Comment by mlucchini** [comment]
Well spotted @systemcatch @jarek. Submitted a fix.

**Comment by corradio** [comment]
I'll close this one as we now have a parser
