### ISSUE TITLE
Data quality: ignore big jumps in production

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#621]
NI recently had the case where they reported a production of 1TW of power, whereas they normally are at 1GW.
We should have some checks in place to validate that. Not sure how to formulate the check however.

**Comment by corradio** [comment]
What we could do is define an acceptable range (in terms of powers of 10?) of the production, per parser.

**Comment by allocater2** [comment]
If you have capacity data, you can ignore production above capacity.

**Comment by jarek** [comment]
Idea: If you have easy access to past results, compare the total  supply (production + imports) being reported now with the value from 15 minutes ago. Reject values that indicate a change in supply by a factor of 2 or more from the last known good value.

**Comment by systemcatch** [comment]
Another possible idea is to use the capacities file to check whether the generation data makes sense.  E.g. if a countries generation is 200% of total capacity then something is wrong and the map should show unknown generation for that time.  

Likewise if country is only using 10-15% of capacity that's likely wrong as well.  We could set a ceiling of 105% capacity (allows for addition of new plants before we update capacities file) and the floor could be calculated by seeing what the minimum ever observed for that country is then allowing some extra leeway.

**Comment by corradio** [comment]
I've done a bit of thinking and I think we should add some more checks to each specific parser.
Everything that can be generalised (such as checking wrt capacity etc..) will be centralised though.
However, capacities are often outdated or not reliable enough compared to real-time data.

For now the simplest check that I recommend we add to all new parsers should be based on a reference production value, and allow a factor X deviation (for now its 10) from it:

https://github.com/tmrowco/electricitymap/commit/ef4c909d1c9fd2e470e6c787bd9c2d212a8d3bea
