### ISSUE TITLE
Spain <-> Morocco

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#623]
According to http://www.ree.es/en/activities/operation-of-the-electricity-system/international-interconnections, Spain has an interconnection with Morocco.

**Comment by allocater2** [comment]
Shouldn't ENTSOE track it then?

**Comment by corradio** [comment]
That's a good point. Any insights @Dalius-ENTSO-E @rustyb?

**Comment by blackleg** [comment]
See in the [Esios Api](https://www.esios.ree.es/en/page/api), the 563 indicator. 
[https://api.esios.ree.es/indicators/563 (Require access token)](https://api.esios.ree.es/indicators/563)

**Comment by blackleg** [comment]
The esios data isn't real time, It is published one hour later. They are useful?
```
{
            "name": "Morocco interconnection balance real time measurements",
            "description": "<p>Net summation of the real time measures of the production through the international interconnections.</p><p>The breakdown of this indicator provides the telemetrics in the interconnection with Morocco, each one with its sign.</p><p><b>Publication:</b> hourly with the information of the previous hour.</p>",
            "id": 10209
        },```

**Comment by corradio** [comment]
One hour later is an acceptable latency. In the Electricity Map we have an upper bound of 2h delay.

**Comment by Dalius-ENTSO-E** [comment]
I know about this border, but REE requested to remove it from TP at very early stage, informing that they are not obliged to report data for this border according to the Regulation 543/2013.

**Comment by corradio** [comment]
Thanks for adding this @blackleg !
