### ISSUE TITLE
No map at all

### ISSUE THREAD

**Issue by strassburger** [tmrowco/electricitymap#625]
https://www.electricitymap.org/?wind=false&solar=false&page=map
No map at all.
Updated 2 hours ago

**Comment by strassburger** [comment]
Hope may help:
Firefox: 54.0 (32-Bit) 
https://www.electricitymap.org/?wind=false&solar=false&page=map
No map at all.
Updated 2 hours ago

chromium: Version 58.0.3029.110 Built on Ubuntu , running on Ubuntu 14.04
https://www.electricitymap.org/?wind=false&solar=false&page=map
Map is shown
Updated 2 hours ago

**Comment by strassburger** [comment]
Sorry, not closed, still do not work

**Comment by corradio** [comment]
I think it's related to the backend. I had to restart it as we're running more and more countries.
Can you confirm it has been fixed?

**Comment by strassburger** [comment]
Sorry no.
Reboot ---> same problem.
Firefox: problem no map at ll, only 
Updated 2 minutes ago

chromium ---> working
Letzte Aktualisierung vor 3 Minuten
backends:
2x PC ubuntu 14.04 

1x nexus 7  
cyanogenMod-Version 12.1 .... grouper / android-Version 5.1.1
google last updates

PS: is it possible to split canary island into the islands.
El Hierro is very impressiv: rigth now 100% RE
source:
https://demanda.ree.es/movil/canarias/el_hierro/total


![firefox-2017-07-14 14 01 29](https://user-images.githubusercontent.com/28303688/28211511-549711a0-689d-11e7-8c8a-2691347de6f8.png)

![chromium-2017-07-14 14 03 02](https://user-images.githubusercontent.com/28303688/28211515-5da238ce-689d-11e7-9f51-2f032bb58300.png)

**Comment by blackleg** [comment]
I confirm that map not work in firefox. Checked in Ubuntu 16.04 and Android.

@strassburger Open new issue to discuss split the canary islands in separate islands. https://help.github.com/articles/creating-an-issue/

**Comment by corradio** [comment]
Should be fixed now!

**Comment by strassburger** [comment]
It is fixed.
