### ISSUE TITLE
Split generation by island for Canaries

### ISSUE THREAD

**Issue by strassburger** [tmrowco/electricitymap#626]
Is it possible to split canary island into the islands.
they are really working for there own.
see  also:
http://ree.es/en/activities/canary-islands-electricity-system/canary-electricity-demand-in-real-time

El Hierro is very impressiv: rigth now 100% RE /  0 CO2
source:
https://demanda.ree.es/movil/canarias/el_hierro/total

**Comment by strassburger** [comment]
"inside look" from outside to El Hierro "Gorona del Viento":
http://euanmearns.com/el-hierro-portal/

**Comment by systemcatch** [comment]
A quick look at this one reveals that the page makes a request to https://demanda.ree.es/WSvisionaMovilesCanariasRest/resources/demandaGeneracionCanarias?callback=angular.callbacks._2&curva=EL_HIERRO&fecha=2017-10-31 which then returns json data for each 10 minute interval.  It shouldn't be hard to write a parser for this.

**Comment by jarek** [comment]
As was mentioned in the Slack channel, the current parser for Canary Islands uses pypi.python.org/pypi/reescraper which already splits up the data by island. Unfortunately our map data source (Natural Earth) doesn't break apart the islands, so integration on the map side is a bit tricky.

It should be feasible to just use the currently generated GeoJSON (/web/app/world.json) and extract the polygons for all the islands, then split it into separate islands manually - they're already separate polygons for each island on the map.

**Comment by systemcatch** [comment]
I've managed to separate out the individual Canary Island's from the natural earth .shp files which I'll submit a PR for soon. @blackleg you should be able to return data by Island rather than in aggregate now.

**Comment by blackleg** [comment]
@systemcatch Great work. :+1:

**Comment by strassburger** [comment]
Thanks very much you all.

**Comment by blackleg** [comment]
![screen shot 2018-01-26 at 18 42 40](https://user-images.githubusercontent.com/4323228/35452957-c45002de-02c8-11e8-94d4-8f7b97f0af6e.png)

**Comment by blackleg** [comment]
The pull request: https://github.com/tmrowco/electricitymap/pull/1028
