### ISSUE TITLE
api code

### ISSUE THREAD

**Issue by fuocor** [tmrowco/electricitymap#640]
I was wondering if the web service code is available? I have additional grib data that I would like to add for my implementation.

thanks

**Comment by corradio** [comment]
Hi @fuocor ,

Unfortunately the backend is not open source, mainly because there's a lot of infrastructure-specific code. What additional grib data would you like to add?

**Comment by fuocor** [comment]
thanks...
NOMADS has some higher resolution data for the US that was of interest s well as some data from Environment Canada.

What is your licensing  for accessing the api? your wind and solar data is very interesting as-is.

thanks,
rich

**Comment by corradio** [comment]
Weather data is going to be included in our professional offering (https://pro.electricitymap.org), but it is not yet. If you send us an email at pro@electricitymap.org telling us exactly what your use case is we can give you access to the beta and figure out a proper license.
FYI the data source we use is here: https://github.com/tmrowco/electricitymap#real-time-weather-data-sources

Olivier
