### ISSUE TITLE
Singapore has solar data

### ISSUE THREAD

**Issue by jarek** [tmrowco/electricitymap#653]
https://www.emcsg.com/ has generation mix for Singapore. It's overwhelmingly gas, but it is real time... Raw data comes from https://www.emcsg.com/ChartServer/blue/ticker (updated half-hourly).

The data has demand and "system loss" in MW, and mix in percent. Should generation be calculated based on demand plus system loss, then?

The data also contains prices for the following categories: USEP, LCP, Primary Reserve,
Secondary Reserve, Contingency Reserve, and Regulation. Is one of those of interest for the price parser?

**Comment by jarek** [comment]
Found this for the explanation of the prices https://www.emcsg.com/marketdata/guidetoprices

**Comment by systemcatch** [comment]
@jarek  nice find on the data.  I searched around and found this [report](https://www.ema.gov.sg/cmsmedia/Publications_and_Statistics/Publications/SES/2016/Singapore%20Energy%20Statistics%202016.pdf) from the government which may be useful in cross checking some figures.  System loss looks quite low but Singapore is very compact so it makes sense I guess.

**Comment by corradio** [comment]
Indeed generation should be based on demand + loss.
For the prices I think that's a tricky issue. In general we have to rethink how we want to show prices, because currently they are very hard to compare.
Let's leave prices out for now, or simply take the spot price.

**Comment by jarek** [comment]
OK, I'll write a parser for the generation and the USEP now then.

**Comment by corradio** [comment]
Awesome!

**Comment by jarek** [comment]
Now done :tada:

**Comment by alixunderplatz** [comment]
@corradio @jarek 
I found a link to Singapore's PV production. 
https://www.ema.gov.sg/solarmap.aspx

Unfortunately, it's a png-image only.
https://www.ema.gov.sg/cmsmedia/irradiance/plot.png?ref=636512085214679676

Installed inverter capacity is ~109 MW, so only 1% of natural gas capacity / <2% of current daily peak demand.
Installed PV module capacity is ~141 MW according to:
https://www.ema.gov.sg/cmsmedia/Publications_and_Statistics/Statistics/31RSU.pdf

It's a quite insignificant share at the moment, but is there any way to use OCR or something similar for reading the data?

![image](https://user-images.githubusercontent.com/25743609/34770246-b7094592-f600-11e7-8e10-9a30cdb340d1.png)

**Comment by systemcatch** [comment]
@alixunderplatz OCR would be fun to try.

Running the following commands on your image.
```
convert sing_pv.png -threshold 30% sing_bw.gif
tesseract sing_bw.gif output
Tesseract Open Source OCR Engine v3.03 with Leptonica
```
Gives me this result in a .txt file.
![result](https://user-images.githubusercontent.com/30196510/34783816-75559384-f624-11e7-96ec-3d9a148c354e.png)
We're in business!

**Comment by alixunderplatz** [comment]
@systemcatch That simple, wow :) 👍 ❤️

**Comment by alixunderplatz** [comment]
@systemcatch I noticed the image's URL is changing - it is refreshing every minute according to the site https://www.ema.gov.sg/solarmap.aspx

**Comment by brunolajoie** [comment]
haha that's brilliant! 🔍

**Comment by jarek** [comment]
Maybe we can email them and ask if same info is available in text format somewhere

**Comment by systemcatch** [comment]
Built a function that gets this data. Only question is whether it should be added to SG.py or in parsers/lib like AU_solar.

**Comment by systemcatch** [comment]
All done here, feel free to reopen if anything new comes up.
