### ISSUE TITLE
Data for Guatemala

### ISSUE THREAD

**Issue by igorarduin** [tmrowco/electricitymap#658]
Found hourly production data for Guatemala: http://www.amm.org.gt/portal/

I'll write a parser if nobody is on it!

**Comment by igorarduin** [comment]
I have a first version of parser for Guatemala. Should I just drop it in the parsers folder ? Or do you have a pre-prod environement to test it?

I only have hourly production and consumption data so far, so only wrote fetch_production and fetch_consumption functions. I'll dig a bit more to see if I can have real time prices and exchanges.

Other question, if I find it, where should I put the installed capacity per technology ? I can see on several countries that you can depict the % for each type of resources used.

**Comment by corradio** [comment]
Awesome - simply submit a pull request with the parser in the parsers folder, remembering to update those files:
- https://github.com/tmrowco/electricitymap/blob/master/parsers/config.py
- https://github.com/tmrowco/electricitymap/blob/master/config/capacities.json

**Comment by igorarduin** [comment]
@corradio I would like to add the installed capacities for Guatemala I found [here](http://www.amm.org.gt/pdfs2/2017/Capacidad_Instalada_2017.xls). Main biomass plants are combined with another combustible (coal or oil). Should I attribute these plants to coal or oil to be more conservative ?

**Comment by corradio** [comment]
How do you treat this issue in the parser?

**Comment by igorarduin** [comment]
In the parser the webservice directly gives me the production per type, without specifying whether the "biomass/biogas" variable includes the other combined sources.

**Comment by corradio** [comment]
Then I think you should assign biomass plants as biomass, regardless of
combustible added (as it seems the parser works with that assumption).

Olivier

**Comment by EHHS15** [comment]
HELLO
I want to know how to solve the problem that Guatemala has, I understand that you have to make a parser, however I do not know anything about computers, but I want to help, in advance I appreciate any help that I can provide.
