### ISSUE TITLE
Querystring country code argument does not center map around country

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#672]

**Comment by kandunoori** [comment]
@corradio ,

Can you provide more details on this issue, steps to recreate?

**Comment by corradio** [comment]
Hi @kandunoori,

The map is currently centred around the geolocation obtained by the server that represents the origin of your IP.
When linking to a country, using e.g. https://www.electricitymap.org/?wind=false&solar=false&page=country&countryCode=BO, the map should override and center around the country.
The issue is not totally straightforward to fix because the code needs to be refactored. State is not managed properly. You're welcome to try though!

Olivier
