### ISSUE TITLE
FO data quality

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#674]
This should not happen:

![image](https://user-images.githubusercontent.com/1655848/29161201-a27a0666-7db5-11e7-86fd-a99a7cff8b70.png)

**Comment by jarek** [comment]
Could be solved generally by #621. (See also similar issue in #668, and it's likely to happen eventually for other parsers too.)

The system can probably assume total supply in given territory is unlikely to change by a factor of 2 or more within 15 minutes, and reject data points that say that - that should solve most of the issues I've seen so far...

**Comment by corradio** [comment]
Yes indeed. Problem is that this kind of check requires keeping track of
previous values, which complicates things.
However I will think of a way to simplify those checks because we already
have 2-3 parsers that would benefit from that
