### ISSUE TITLE
CR: ValueError: labels [u'Intercambio Sur' u'Intercambio Norte'] not contained in axis

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#683]
cc @mlucchini
```
fetch_production() ->
Traceback (most recent call last):
  File "lib_electricitymap/parsers/CR.py", line 212, in <module>
    print fetch_production()
  File "lib_electricitymap/parsers/CR.py", line 165, in fetch_production
    df_to_data(country_code, today, df_today)
  File "lib_electricitymap/parsers/CR.py", line 124, in df_to_data
    df = df.drop([u'Intercambio Sur', u'Intercambio Norte', u'Total'])
  File "/usr/local/lib/python2.7/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/usr/local/lib/python2.7/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels [u'Intercambio Sur' u'Intercambio Norte'] not contained in axis
```

**Comment by mlucchini** [comment]
I'll assume the parser works fine most of the time as there is data returned by the API.
Also at this stage in the script, we managed to extract the data for yesterday that is on a different page.

One hypothesis would be that this happens at the point at which today's page is in an incomplete state: did that happen around midnight CR-time? +/- 7am BST?

It's hard to reproduce but I could add more data sanity checks.

**Comment by corradio** [comment]
Mmh it was happening right when I opened this issue..
Let's keep a close eye on it.

**Comment by corradio** [comment]
It is currently 00:13 in CR and the error happens again. I can see that the tables are empty (which is expected because there's no data for today. What I do to avoid this error for ENTSOE parsers is that I actually fetch day D and day D-1

**Comment by corradio** [comment]
My bad, I actually read the parser and see that you do exactly what I mentioned.
Will dig deeper.

**Comment by mlucchini** [comment]
Just solved it on my side as well with if len(df.index) > 1: but you were
faster.
Great.

2017-08-16 7:41 GMT+01:00 Olivier Corradi <notifications@github.com>:
