### ISSUE TITLE
GT: key biomass has negative value -1.1956

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#690]
It happens quite a lot:

![image](https://user-images.githubusercontent.com/1655848/29333131-f6131064-8202-11e7-8b2e-24241d89fc6f.png)

Error: GT: key biomass has negative value -1.1956

**Comment by igorarduin** [comment]
I planned to modify Guatemala's parser in order to get a right/similar data output as I did for Bolivia (empty production list for futur hours of the day). Do you want me to force Biomass to be at least 0 at the same time ?

**Comment by corradio** [comment]
I think that's a good idea.
Don't forget to mention if your PR fixes or references this issue! That way it will be easier to keep track of what is getting done.
Thanks
