### ISSUE TITLE
Hydro missing from DO

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#691]
![opbeat com-tomorrow-electricity-map-backend-errors-329-](https://user-images.githubusercontent.com/1655848/29333158-11e0dec0-8203-11e7-9e38-a24c2d74e42f.png)

**Comment by systemcatch** [comment]
So hydro data is missing sometimes?  Weird because the parser should set it to None if the value is missing (not updated yet).  Regardless I can change fetch_production to return 0.0 or None if the key is missing.
