### ISSUE TITLE
CR->NI: List index out of range

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#692]
![opbeat com-tomorrow-electricity-map-backend-errors-174-](https://user-images.githubusercontent.com/1655848/29333213-3af0c8b6-8203-11e7-8325-94f561b1e891.png)

**Comment by corradio** [comment]
https://opbeat.com/tomorrow/electricity-map-backend/errors/456/

**Comment by systemcatch** [comment]
Looks like part of the interchange list is missing sometimes.  Easy fix is to wrap that whole block in a try/except (default to 0.0 if absent?).  Another idea is to use ENTE.py to get this exchange, it's all setup but not implemented yet.

**Comment by corradio** [comment]
Let's use the ENTE if it is more stable then.
Can you help?

Oli
