### ISSUE TITLE
AU_SA <-> AU_WA exchanges

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#693]
Q: Is there an interconnection? Do we have data for it?

**Comment by jarek** [comment]
Likely not any substantial one. Take a look at [a population density map of Australia](https://i.imgur.com/Np74KFZ_d.jpg) and cross-compare with [simulated satellite image](https://en.m.wikipedia.org/wiki/File:Australia_New_Guinea_continent.jpg). Population of WA is in southwest corner, population of SA close to Victoria border, and a lot of desert in between

**Comment by jarek** [comment]
Better https://i.imgur.com/Np74KFZ_d.jpg?maxwidth=640&shape=thumb&fidelity=high

**Comment by superlonglong** [comment]
there is no interconnector. 

you can see this on the front page of this website

http://aemo.com.au/

**Comment by corradio** [comment]
Thanks @superlonglong
