### ISSUE TITLE
Panama

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#696]
Unfortunately only data for the previous day, hour by hour:
https://www.cnd.com.pa/index.php

Data seems to be generated server side and inserted directly into highcharts.

**Comment by igorarduin** [comment]
You can have forecasted productions and exchanges for the current day though ([here](https://www.cnd.com.pa/informes.php?tipo_informe=2&cat=1)).

**Comment by paulotaviodr** [comment]
Here’s the live data: http://sitr.cnd.com.pa/m/pub/gen.html

**Comment by jarek** [comment]
Thanks @paulotaviodr! That looks like a suitable source. Are you interested in writing a parser? We can help.

**Comment by paulotaviodr** [comment]
Great, sure. I can learn how to. I've seen the example as well as some from other countries and it doesn't seem to be rocket science. I may begin to work on it tomorrow as it is a holiday in Panama.

**Comment by paulotaviodr** [comment]
Hi everyone. Sorry for the delay. Last weekend I ended up working with the translation of the interface to Portuguese instead and didn't have time to work on the parser.

OK, so I just made the very basic as I am looking for some info first (the website mentions having a certain percentage of "thermal energy" but I'm still looking for further info that indicates the exact kind of energy (coal, oil, etc). In the meanwhile, I made this part:

`TIMEZONE = 'America/Panama'
DATE_FORMAT = 'DD/MM/YYYY'
MONTH_FORMAT = 'MM/YYYY'

MAP_GENERATION = {
  'Hídrica': 'hydro',
  'Eólica': 'wind',
  'Solar': 'solar',
  'Biogas': 'gas',
  'Térmica': 'unknown'`

But I'm not sure if I got it right, as the website outputs the MW amount right after the name (see the graphics): http://sitr.cnd.com.pa/m/pub/gen.html
So I perhaps I'll have to write one line for each of the specific sources show below, right?

Their website also features the demand & supply graphs (http://sitr.cnd.com.pa/m/pub/sin.html), imports and exports (http://sitr.cnd.com.pa/m/pub/int.html) and flow (http://sitr.cnd.com.pa/m/pub/flow.html).

Any help would be appreciated. Thanks :)

**Comment by jarek** [comment]
I think http://sitr.cnd.com.pa/m/pub/gen.html has all the info we need - we already get exchange to Costa Rica from the central ENTE parser.

The way I would do it would be to get the HTML of gen.html, load it into BeautifulSoup, and find the `<table>` with class_="sitr-pie-layout". Then each of the `<span>`s within that table contains a generation type. Split the text of each `<span>` on whitespace, then the first item of the result is the key for MAP_GENERATION and the second item is the MW value (though you'll need to parse it with `float()`).

Then get the timestamp of the data by looking for the `<div>` with class_="sitr-update" and parsing that. I don't know if there is a way to parse Spanish strings into dates easily in Python, maybe others do? If nothing else comes up, make a lookup table mapping "noviembre" to 11 and so on.

I'm shamelessly suggesting my own code here, but you can take a look at CA_YT and CA_NB among existing parsers for fairly straightforward implementations of BeautifulSoup parsing. You can also search through the parsers directory for other examples of using BeautifulSoup

**Comment by systemcatch** [comment]
@paulotaviodr 
jarek's suggestions are good.  If you've not seen it already the [example parser](https://github.com/tmrowco/electricitymap/blob/master/parsers/example.py) is useful for understanding the overall structure of a parser.

As regards Spanish date strings, datetime.strptime will do it if you manually set the locale to Spanish, however a mapping dict might be simpler overall.

Thanks for having a go at this one, if you've got any more questions post them here or on [slack](http://slack.tmrow.co/).

**Comment by systemcatch** [comment]
@paulotaviodr any progress with this?

**Comment by 7hibault** [comment]
I've written a parser https://github.com/7hibault/electricitymap/blob/master/parsers/PA.py

I've used @paulotaviodr 's mapping to fetch the production. I still need to format the date and add this to zones, etc.

**Comment by systemcatch** [comment]
Nice!  When you're ready submit a pull request and we can go through it.

**Comment by corradio** [comment]
@7hibault feel free to close the issue if it's done.

**Comment by paulotaviodr** [comment]
Sorry everyone. I’ve been extremely busy with some emergencies at home, so My schedule is all messed up. :( Thanks a bunch, @7hibault.

**Comment by systemcatch** [comment]
Closing this since the parser is built and working.  There is no exchange between Panama and Columbia at this time though one is planned for [2020](http://www.elp.com/articles/2014/07/panama-columbia-to-interconnect-power-grids-by-2020.html)
