### ISSUE TITLE
NI KeyError

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#697]
```
feeder_1     | Exception while fetching production of NI
feeder_1     | Traceback (most recent call last):
feeder_1     |   File "feeder.py", line 106, in fetch_production
feeder_1     |     obj = parser(country_code, session)
feeder_1     |   File "/home/feeder/parsers/NI.py", line 208, in fetch_production
feeder_1     |     production, data_datetime = get_production_from_summary(requests_obj)
feeder_1     |   File "/home/feeder/parsers/NI.py", line 189, in get_production_from_summary
feeder_1     |     standard_name = type_translator[name.replace('\'', '')]
feeder_1     | KeyError: u'TERMICO DIESEL'
```

**Comment by systemcatch** [comment]
Does this happen often or was it just a one off error?

**Comment by corradio** [comment]
Seems to be a one off.
I'll re-open if it happens again.

**Comment by corradio** [comment]
Unfortunately it is happening again (right now)

**Comment by systemcatch** [comment]
Ok so this isn't occurring now which means that the type 'Termico Diesel' only appears occasionally in the data.  The question is do both 'Termico Bunker' and 'Termico Diesel' appear at the same time or is it one or the other only?  I haven't been able to verify this yet.  

They are likely the same type of generation (oil).  We can change the type mapping to return 'unknown' if no match is found to avoid KeyErrors.  If we're sure that 'Termico Diesel' is oil it can be added to the type mapping dict but then we will have to sum duplicate oil keys if both appear at the same time.

**Comment by corradio** [comment]
I would go with your second suggestion: we're quite sure Termico Diesel is
oil.

Olivier
