### ISSUE TITLE
Australia AEMO parser sometimes returns double the production 

### ISSUE THREAD

**Issue by jarek** [tmrowco/electricitymap#704]
I'm guessing at some points, the source CSV contains information about production at two different timestamps (e.g. 03:30 as well as 03:25). The carbon intensity remains mostly correct, except the effect of solar production (which comes from a different source) is halved. Still, would be good to only return data for one timestamp per plant.

Compare the following screenshots, where generation from coal doubles from 5.32 GB to 10.6 GW - and so does the reported installed coal capacity.

<img width="315" alt="au bug 1" src="https://user-images.githubusercontent.com/47415/29496801-4cbf7698-85da-11e7-9d0f-2294e66d5ba9.PNG">
<img width="332" alt="au bug 2" src="https://user-images.githubusercontent.com/47415/29496802-4fd8db9e-85da-11e7-83a9-a30cdb26adbb.PNG">

**Comment by systemcatch** [comment]
There could be a check at the start where the max or most common timestamp is found.  Then any key that has a different timestamp to that is dropped.

**Comment by jarek** [comment]
I've seen it again and I really don't understand why, since it really should be fixed. Maybe this time the datasource was actually just wrong. Or blame #1196 like for everything else.

![image](https://user-images.githubusercontent.com/47415/42903823-57f4ae62-8ad3-11e8-9dcf-2b0c71c91618.png)
