### ISSUE TITLE
GT: Some datapoints are in the future

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#705]
If datapoints in the future are present, that's likely an error in the parser and thus it is ignored.
That's why GT is not appearing anymore

**Comment by igorarduin** [comment]
Should you merge this issue with #690 ? The modification I'll make with GT's parser include deleting the futur dates from the final data output.

**Comment by corradio** [comment]
I'll mention it in the PR

**Comment by corradio** [comment]
That's two different issues. Just mention that you fix both issues when you submit your PR. It's perfectly valid for one PR to fix two issues.
