### ISSUE TITLE
Suggestion :  Display the renewable quote

### ISSUE THREAD

**Issue by Alsatian67** [tmrowco/electricitymap#712]
Everywhere, you display CO2 informations, so a country like France is always green because its power is highly produced with nuclear plants. Nuclear is assumed to emit less carbon as coil or gas, but is it really "greener" ?

I think you should add another display mode, which displays the renewable production quote.

**Comment by systemcatch** [comment]
There is the fossil fuel % displayed for each country that gives an indication of it's renewable enegy production.  The map ranks countries by gCO2eqv/KWh so yes the more solar/wind/hydro/geothermal/nuclear a country has the greener it will be on the map.

**Comment by corradio** [comment]
Hi @Alsatian67 
We get that question a lot. The map is really focussing on carbon emissions, and other externalities (nuclear waste, water usage ....) are not taken into account - and therefore we never say that a country is "green", but rather that it is low-carbon.
However, the feature you're request will be part of the premium version (pro.electricitymap.org). Let me know if you're interested.

**Comment by corradio** [comment]
Hi @Alsatian67,
Yes we get that question a lot. We only focus on carbon emissions, and other externalities (nuclear waste, water usage etc..) are not taken into account, because it is really hard to make a true "greenness" indicator.
However, the feature you're requesting will be available on our [premium](https://pro.electricitymap.org) offering. Let me know if you're interested.

**Comment by Alsatian67** [comment]
OK, good. No i'm just an anonym user curious about electric production, I won't use a premium version.

I didn't know if someone proposed it before.

**Comment by systemcatch** [comment]
@Alsatian67 if you're interested in electricity production then maybe you'd enjoy helping out on the project?  There's quite a few issues to look at and plenty of ways to help that don't require being able to code.

**Comment by magol** [comment]
I understand why this question is asked and see a reason to implement it. But I see a problem. Who will decide what to be classified as "green" production, it is a question that does not have an obvious answer.

What should be classified as green electricity generation is something that different groups have different opinions about. Some say that burning of biomass is NOT green production, while others have opposite opinion. It is the same for nuclear power plants. Many think it is absolutely not a green production, while others think that it is required for the switch to green electricity production.

What I would say is that no matter how we would implement such a feature, someone would think it's wrong.

If electricitymap is going to start taking a stand in various discussions, electricitymap will lose confidence among its visitors. Electricitymap should not be political and just show one angle of incidence by many.

The best thing is to continue to stick to hard numbers that can not be disputed.

**Comment by Alsatian67** [comment]
I didn't though green / not green, but a renewable / not renewable indicator. (added to the existing indicators).

And as most countries have renewable target quotes it is an important value to know.
