### ISSUE TITLE
ENTSOE: Italy is missing coal

### ISSUE THREAD

**Issue by ThierryOllivero** [tmrowco/electricitymap#72]
Information on Italian generation can be found here: 

http://www.terna.it/SistemaElettrico/TransparencyReport/Generation/Expostdataontheactualgeneration.aspx

Data are ex-post, meaning they show the day before. The XLS shows hourly data for the 6 regions of Italy: North, South, Central North, Central South, Sicily and Sardaigne. The production type supported are: Geothermal, Thermal, Solar, Wind, Hydro (Rivers, Pumps, Reservoirs) and Others.

A realtime Load graph is available here: http://www.terna.it/DesktopModules/GraficoTerna/GraficoTernaEsteso/ctlGraficoTerna.aspx?sLang=it-IT

**Comment by corradio** [comment]
ENTSOE is missing coal for now.

**Comment by corradio** [comment]
Seems like we're getting data for Italy now!

![image](https://cloud.githubusercontent.com/assets/1655848/21109548/d9225634-c099-11e6-90cc-55cb62e544b6.png)

**Comment by ThierryOllivero** [comment]
Nope. Italy has 50 M inhabitants, they should produce more than 60 GW.

+ other is geothermal. Coal is still missing.

**Comment by corradio** [comment]
Good catch. Let's keep this issue opened.

**Comment by corradio** [comment]
@rustyb can you help us here?

**Comment by rustyb** [comment]
Hi Folks - The values for Coal are reported through the bidding zones. For example see 
- [IT-Centre-South](https://transparency.entsoe.eu/generation/r2/actualGenerationPerProductionType/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&datepicker-day-offset-select-dv-date-from_input=D&dateTime.dateTime=27.01.2017+00:00|CET|DAYTIMERANGE&dateTime.endDateTime=27.01.2017+00:00|CET|DAYTIMERANGE&area.values=CTY|10YIT-GRTN-----B!BZN|10Y1001A1001A71M&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2))
- [IT-Centre-North](https://transparency.entsoe.eu/generation/r2/actualGenerationPerProductionType/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&datepicker-day-offset-select-dv-date-from_input=D&dateTime.dateTime=27.01.2017+00:00|CET|DAYTIMERANGE&dateTime.endDateTime=27.01.2017+00:00|CET|DAYTIMERANGE&area.values=CTY|10YIT-GRTN-----B!BZN|10Y1001A1001A70O&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2))
- [IT-Sardinia](https://transparency.entsoe.eu/generation/r2/actualGenerationPerProductionType/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&datepicker-day-offset-select-dv-date-from_input=D&dateTime.dateTime=27.01.2017+00:00|CET|DAYTIMERANGE&dateTime.endDateTime=27.01.2017+00:00|CET|DAYTIMERANGE&area.values=CTY|10YIT-GRTN-----B!BZN|10Y1001A1001A74G&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2))

I will pass your message on this to the team.

**Comment by corradio** [comment]
Thanks @rustyb 

Seems like we're now getting a lot of "unknown" values. Is that the sum of coal given in each bidding zone?

![image](https://cloud.githubusercontent.com/assets/1655848/22639401/37cdde12-ec4e-11e6-9c20-39e82b83fb91.png)

**Comment by corradio** [comment]
We know receive coal values, but it would be nice to understand what the "unknown" corresponds.
