### ISSUE TITLE
Spain reports solar production in the middle of the night

### ISSUE THREAD

**Issue by jarek** [tmrowco/electricitymap#727]
(The timezone where this screenshot was taken is same as Madrid's)
![spain solar in the night](https://user-images.githubusercontent.com/47415/29998522-71129432-902d-11e7-8b92-edc20cb431b5.png)

**Comment by jarek** [comment]
Actually I guess this could be stored solar / molten salt production. Do we have any way of checking what stations are responsible for that production?

**Comment by systemcatch** [comment]
Spain is down now but I also saw about 2GW of solar 30mins ago.  Which is during the night.

**Comment by corradio** [comment]
I think we should check with ENTSOE (we get the data from their transparency platform).
cc @Dalius-ENTSO-E - maybe you can help us investigate / debug?

**Comment by jarek** [comment]
It was indeed reporting 2.49 GW at 23:45. However that appears to be because the production numbers were the same from 20:00 until 23:45 - only reported import from Portugal changed:
![spain 8pm](https://user-images.githubusercontent.com/47415/30001475-d586e988-908f-11e7-83ae-256ac3a6aa8e.png)
![spain midnight](https://user-images.githubusercontent.com/47415/30001476-d88fad72-908f-11e7-8457-0b8fdea57a72.png)

**Comment by corradio** [comment]
The production numbers should only be valid for two hours actually,
specially to avoid the kind of situation you're describing.
Maybe there's an error in the backend.

**Comment by corradio** [comment]
I'm closing this as this shouldn't happen anymore. If it does, please re-open the issue.
Thanks for reporting @jarek
