### ISSUE TITLE
IPCC target carbon intensity

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#731]
Someone answered the survey saying "IPCC recommends staying under 50g CO2 per kWh, it would be great if each country showed how much it exceeds or meets CO2/kWh targets.".
Does someone know the source of that comment? 
cc @brunolajoie

**Comment by brunolajoie** [comment]
I haven't seen IPCC being prescriptive on that. They rather make scenarios and compute least cost pathways. But it's not really a political recommendation

**Comment by corradio** [comment]
http://energyrealityproject.com/category/canada/ says
> well under 50g/kWh, which is where the IPCC recommends we need to be for all new sources of stationary energy generation beyond 2030 to have the best chance of mitigating the worst effects of anthropogenic climate forcing.

I'm struggling to find the source.

**Comment by brunolajoie** [comment]
Spent 2 hours looking at it, didn't see anything. The chapter that should have had these figure is [IPCC AR5 WG3 chapter 7.11.3](https://www.ipcc.ch/pdf/assessment-report/ar5/wg3/ipcc_wg3_ar5_chapter7.pdf), but we only see contional shares of renewables in 450ppm-compatible scenarios. Not gCO2eq/kWh. If anyone has a better clue, let me know!
