### ISSUE TITLE
Brazil regions hover state

### ISSUE THREAD

**Issue by alexanmtz** [tmrowco/electricitymap#762]
There's a issue with the Northeast region of Brazil when is hovered. There's a "limbo" region, like the hover is not covering all the region. The regions on hover differs from the normal state as shown on the screenshot

<img width="386" alt="screen shot 2017-09-20 at 10 26 52 am" src="https://user-images.githubusercontent.com/88840/30634200-96347e0a-9dee-11e7-8e48-e60b2b45b727.png">
<img width="586" alt="screen shot 2017-09-20 at 10 27 07 am" src="https://user-images.githubusercontent.com/88840/30634198-9633e2ba-9dee-11e7-9622-7b46e253d700.png">
<img width="680" alt="screen shot 2017-09-20 at 10 26 57 am" src="https://user-images.githubusercontent.com/88840/30634199-963470a4-9dee-11e7-8b36-bb4cbaa734ac.png">

**Comment by systemcatch** [comment]
Yeah I can see this as well.

**Comment by corradio** [comment]
Seems like the `topojson.merge` method doesn't work as expected.
We should maybe try to add/remove states in B-NE to see which state causes the error.
It might be an idea to upgrade the version of topojson, but at this point I have no idea if it would solve the issue.

**Comment by jarek** [comment]
The phantom area is the state of Maranhão (BR.MA). When you hide the SVG path for North-East using browser developer console, you can see that it is also contained in North region. It looks like Maranhão gets its opacity from North region, but colour from North-East - somehow.

![image](https://user-images.githubusercontent.com/47415/30650492-4ede1afe-9e23-11e7-9bb8-497b8a54d56a.png)

**Comment by corradio** [comment]
Could it be that it is included in both regions?

**Comment by jarek** [comment]
The current world.json has code_hasc=BR.MA and hasc_maybe=BR.TO|BRA-MRN. The current countrytopos.js has looks in hasc_maybe and picks it up. BR.TO is the neighbouring region. This was introduced in https://github.com/tmrowco/electricitymap/commit/5fdb3bbc03bf700d5472aa5e404bffbed121ee69

**Comment by corradio** [comment]
ah! Well spotted. I had to use the hasc_maybe as the hasc_code for India
disappeared..
We should probably remove the hasc_maybe and use the fips code for India
instead (but requires a bit of manual work to map them..)

Olivier
