### ISSUE TITLE
Ranking update: show now vs yearly

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#763]
Here's an idea on the ranking page.
We could have two modes: 1/ yearly 2/ live
On each mode we could show how the ranking changes compared to the other.
The idea is to show something that looks like a "hit list", highlighting volatility, and enabling to answer debates like "yeah but you only look at the live view, I wonder what it is on aggregate".

@brunolajoie we have to make sure this doesn't jeopardise our professional offering though.

**Comment by systemcatch** [comment]
Will this still happen? I'm trying to find old issues to close.

**Comment by corradio** [comment]
Yeah let's close. I still like the idea but we have more important things to do.
