### ISSUE TITLE
HTTPError 500  at https://api.electricitymap.org/v3/state

### ISSUE THREAD

**Issue by kandunoori** [tmrowco/electricitymap#772]
When I run the app in local, I am getting below error, any idea?

main.js:261 Error Caught! Error: HTTPError 500  at https://api.electricitymap.org/v3/state: {"status":"error","message":"Unknown error occured. Please contact admin@electricitymap.org"}

https://api.electricitymap.org/v3/state

{"status":"error","message":"Unknown error occured. Please contact admin@electricitymap.org"}

**Comment by chtompki** [comment]
Yes I agree on this. I was getting the same thing when I tried to run (in separate terminal windows), from the root of the project:

```
docker-compose run --rm web npm run watch
```
and
```
docker-compose up --build
```

the headers to the endpoint even looked the same, although the cookies weren't present if that matters.

**Comment by corradio** [comment]
Hello,

Yes indeed. You will need a token. Ping me on Slack if you want to
contribute, and I'll send you the required token.
I'll also update the README as soon as I get a bit of time.

Olivier
