### ISSUE TITLE
Add Portuguese translation

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#775]

**Comment by corradio** [comment]
Checkout this commit for ref, where I added japanese:
https://github.com/tmrowco/electricitymap/commit/e081e3e3286eadd462dbfe03a78a5751b4189756

**Comment by corradio** [comment]
@alexanmtz can you help here? Then we can start communicating to Brazilians

**Comment by alexanmtz** [comment]
@corradio I'm writing a post about your project in Portuguese in my blog ([http://www.alexandremagno.net](http://www.alexandremagno.net)) and making a call for developers community in Brazil to collaborate!

**Comment by corradio** [comment]
Awesome!

**Comment by paulotaviodr** [comment]
I'm Brazilian and I have some professional experience with translation. I can help.

**Comment by corradio** [comment]
@paulotaviodr thank your for proposing your help. Are you able to translate the file located at https://github.com/tmrowco/electricitymap/blob/master/web/locales/en.json ?
Already translated languages can be seen here:
https://github.com/tmrowco/electricitymap/tree/master/web/locales

**Comment by alexanmtz** [comment]
Nice @paulotaviodr !

**Comment by paulotaviodr** [comment]
All done @corradio :)
[https://www.dropbox.com/s/wpyoxpufm96bs3u/pt-br.json?dl=0](url)

**Comment by corradio** [comment]
Thanks!
