### ISSUE TITLE
Update the Readme for required token.

### ISSUE THREAD

**Issue by kandunoori** [tmrowco/electricitymap#777]
@corradio 
For the below issue, it needs a token. Readme should be updated for required token.
----------------------------------
When I run the app in local, I am getting below error, any idea?

main.js:261 Error Caught! Error: HTTPError 500 at https://api.electricitymap.org/v3/state: {"status":"error","message":"Unknown error occured. Please contact admin@electricitymap.org"}

https://api.electricitymap.org/v3/state

{"status":"error","message":"Unknown error occured. Please contact admin@electricitymap.org"}

**Comment by corradio** [comment]
Done in https://github.com/tmrowco/electricitymap/commit/3e270791877d14b64c548b413eeb442a055a7481
