### ISSUE TITLE
UK: Biomass shown as coal

### ISSUE THREAD

**Issue by otravers** [tmrowco/electricitymap#781]
In the UK, DRAX 1, 2 and 3 were converted to biomass (wood pellets) a couple years ago but still show as coal in ENTSO-E, so you're showing 0% biomass in the UK which is no longer true.

**Comment by corradio** [comment]
Thanks for reporting @otravers .
@Dalius-ENTSO-E , do you have the contact information of the data provider for UK? Maybe we can give him the feedback and potentially correct?

Olivier

**Comment by jarek** [comment]
This is same issue as #219, right? Looks like it keeps on slipping through and is wrong in operators' submissions to ENTSOE?

**Comment by otravers** [comment]
@jarek you are correct, apologies for the duplicate ticket.

**Comment by jarek** [comment]
No worries @otravers, thanks for bringing this up anew as it's been around for a while. I'll close this so we can continue in #219 :)
