### ISSUE TITLE
Wind Installed capacity of Belgium

### ISSUE THREAD

**Issue by jimich** [tmrowco/electricitymap#782]
On the map, on this 28/9/2017, there is 364 GW /1.96 GW for wind in Belgium.
This is not correct. On the "Installed Capacity per Production Type" on the entso-e website, there is 1745MW for onshore wind and  877 for offshore wind, so 2618 MW in total, and not 1960 as currently displayed.

https://transparency.entsoe.eu/generation/r2/installedGenerationCapacityAggregation/show?name=&defaultValue=true&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime=01.01.2017+00:00|UTC|YEAR&dateTime.endDateTime=01.01.2018+00:00|UTC|YEAR&area.values=CTY|10YBE----------2!BZN|10YBE----------2&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19

**Comment by corradio** [comment]
Indeed - we should update the capacity values.

**Comment by corradio** [comment]
@jarek @systemcatch @brunolajoie can someone double check and correct? Thanks!
