### ISSUE TITLE
Unable to create a local environment

### ISSUE THREAD

**Issue by prson** [tmrowco/electricitymap#783]
Hi, 

Following the instructions, I have downloaded Docker, cloned the repository, compiled the front end using_: docker-compose run --rm web npm run watch_ and started a server using: _docker-compose up --build_

I am able to load the website at: http://localhost:8000/?wind=false&solar=false&page=map
But the apis are not loading at the start as well as on clicking on any of the countries. So, none of the countries except Brazil (South) shows any colour.
![image](https://user-images.githubusercontent.com/10982376/31008773-e852ed12-a522-11e7-9aca-b563686c97d2.png)

The docker throws these logs:
_mockserver_1  | [Fri Sep 29 2017 08:10:57 GMT+0000 (UTC)] "GET /v3/history?countryCode=BR-S" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
mockserver_1  | [Fri Sep 29 2017 08:10:57 GMT+0000 (UTC)] "GET /v3/history?countryCode=BR-S" Error (404): "Not found"_

Also, the console shows two warnings:
![image](https://user-images.githubusercontent.com/10982376/31008538-23424ea0-a522-11e7-8ab0-4c580e2205d4.png)

I plan to understand and then contribute to the interesting initiative.

Thanks,

**Comment by corradio** [comment]
Hello @prson ,

As stated in the README, the backend is responsible for calculation carbon emissions, so the map will be empty.
You can run individual parsers by looking here:
https://github.com/tmrowco/electricitymap#testing-parsers-locally
Note that a random carbon intensity value will be generated, so the colour will effectively be random.

Simply write on Slack if you have other troubles (or re-open the issue).

Olivier

**Comment by prson** [comment]
thank you, I understand. I am still struggling to create the local environment.

**First**, I am unable to set PYTHONPATH using: 
C:\Windows>PYTHONPATH=. python mockserver/update_state.py 'FR'
'PYTHONPATH' is not recognized as an internal or external command,
operable program or batch file.
C:\Windows>PYTHONPATH=. python mockserver/update_state.py 'FR'
'PYTHONPATH' is not recognized as an internal or external command,
operable program or batch file.
I am getting this despite setting PYTHONPATH in System Variables in Windows. Any ideas? I am just starting in Python.

Second when I try to run the command:
C:\Windows>PYTHONPATH=. python mockserver/update_state.py 'FR'
'PYTHONPATH' is not recognized as an internal or external command,
operable program or batch file.
I get an exception: C:\Windows>PYTHONPATH=. python mockserver/update_state.py 'FR'
'PYTHONPATH' is not recognized as an internal or external command,
operable program or batch file.

Thank you for taking out time to solve my problems.

Thanks,
Pratik
