### ISSUE TITLE
California (CAISO)

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#787]
Unfortunately we only have renewable data live.
Can someone help us get access to fossil?

**Comment by corradio** [comment]
I've been able to gather the following potential sources:
- https://github.com/WattTime/pyiso/blob/master/pyiso/caiso.py

And I got a reply from CAISO:
> Good morning and thank you for the inquiry. This data can be found on oasis.caiso.com where it can be downloaded in CSV or XML format under the System Demand tab. There is also an API specification that allows users to pull this data without going to the User Interface found here - 
http://www.caiso.com/Documents/OASIS-InterfaceSpecification_v4_3_3Clean_Independent2016Release.pdf 
The ISO also offers the below option in CSV as well. http://www.caiso.com/Pages/TodaysOutlookCSVFileInstructions.aspx

**Comment by systemcatch** [comment]
They responded to your email which is a good sign, and the API spec looks quite hefty.  If we can get a renewable breakdown that includes hydro we may be in business.

**Comment by corradio** [comment]
New response:
> Thank you for your e-mail. Yes, we have changed our Daily Renewable Watch. The information that we have provided is what is sent to that report.

!

http://content.caiso.com/green/renewrpt/20171009_DailyRenewablesWatch.txt now reports breakdown over last day. Can someone take the lead and make a parser?

**Comment by systemcatch** [comment]
When I try to set the date for today it gives a 404 error.  Assume I'm missing something?
http://content.caiso.com/green/renewrpt/20171101_DailyRenewablesWatch.txt

**Comment by corradio** [comment]
I'm reaching out to them.

**Comment by systemcatch** [comment]
At a guess today's txt file is on the server and a script writes new lines to the file every hour.  Or it's possible that the data is stored elsewhere and the txt file is auto generated at the end of each day.  Their live renewable graph is just an image so it must be fed today's data from elsewhere then updated on the page.

**Comment by 7hibault** [comment]
Hello, I'm new here, I'd like to help. I assume this is generated at the end of each day, as the latest available is yesterday's: http://content.caiso.com/green/renewrpt/20171112_DailyRenewablesWatch.txt

I could work on the parser if there's no urgency, I should be able to start working on it in a week or so

**Comment by corradio** [comment]
Yes but data is only available at midnight every day.
I'm trying to get in touch with them but I'm struggling to get a response.

Olivier

**Comment by corradio** [comment]
CAISO is not being very opened to increasing the rate at which they publish data.
I suggest writing this scraper. The view of the last 24h will still be very useful, and hopefully it will start bringing attention to this issue!

Olivier

**Comment by 7hibault** [comment]
I'll get started with this if this is fine for everyone.

Is it conceivable to fill in the data with predictions at some point?

**Comment by corradio** [comment]
I personally don't like it (because I'd rather show missing data to
motivate data providers to fill their gaps).

Olivier

**Comment by 7hibault** [comment]
That makes sense. 

I have a question about the parser: the fetch_production, fetch_price and fetch_exchange functions are supposed to return the last known information. Here, the last known (hourly) information will always be at midnight from the day before, no matter when you query it. How does the backend get its historical information? Is there a way to fetch historical data or is it based on previous queries that are stored? If it's the latter, we might have to tweak the functions to return something like the information from 24 hours ago, but it's a bit ugly to change the meaning of the functions in one parser.

**Comment by corradio** [comment]
You can actually return a **list** of dictionaries containing the history:
that is how the backend fetches previous data.
I suggest that the `fetch_production` method returns all the data contained
in the last valid file exposed by CAISO.

Olivier

**Comment by 7hibault** [comment]
Here's a first version of the parser: https://github.com/7hibault/electricitymap/blob/master/parsers/US_CA.py

I've only tested it locally (aka checking the list I'm getting from the request, not integrating it in the map, I'm having issues with docker). It returns a list of objects with the energy mix. Some choices I've made:
* I've added hydro and small hydro for hydro
* I've added solar pv and solar thermal for solar
* Measurements are dated at the end of the past hour UTC-8, e.g their line for the first hour is dated at 16:59 UTC (which is 00:59 in California)
* I've chosen the country code US_CA
* Their info about thermal energy isn't used in the mix
* Imports aren't used yet

Is it somewhere near what you expected?

**Comment by corradio** [comment]
very good. Can you submit a PR?

**Comment by systemcatch** [comment]
@7hibault Thanks for taking the time to write this, it's appreciated.

As oli said submit a pull request so it can be reviewed properly.  Couple of points for now.

- Both fetch_price and fetch_exchange functions can be deleted as they won't be used in this parser.
- You may want to look at using [arrow](https://arrow.readthedocs.io/en/latest/) for datetimes as currently they don't seem correct.

**Comment by 7hibault** [comment]
Should we close this to keep the issue tracker clean?

**Comment by corradio** [comment]
All good! Thanks for the help

**Comment by corradio** [comment]
Re-opening because live data is now available here:
http://www.caiso.com/TodaysOutlook/Pages/supply.aspx

**Comment by systemcatch** [comment]
@corradio Looks like your emails paid off!  The breakdown is really detailed.

**Comment by 7hibault** [comment]
Nice, congrats @corradio ! There's a warning at the bottom of the page:

> Today’s Outlook is provided for informational purposes ONLY and should not be relied upon by any party for the actual billing values or operational planning.
> Official data is available in OASIS.

I can't find the same information on http://oasis.caiso.com/mrioasis/logon.do

**Comment by HansHyde** [comment]
Well done.  Great information sources.  Any further details on imports (and what they include)?  Currently imports are between 35-40% of system load.

**Comment by corradio** [comment]
Unfortunately I don't know more. No problem with warming. That's expected.
Maybe we can take a look at how the graphs get their data?
Didn't dig, but indeed I saw that oasis didn't have that info yet.

**Comment by systemcatch** [comment]
The main graphs get their data from www.caiso.com/outlook/SP/fuelsource.csv

**Comment by 7hibault** [comment]
Should we use this data as well then even if they explicitly say not to?

**Comment by corradio** [comment]
They didn't say not to use it?

**Comment by 7hibault** [comment]
They say it's not official, for informational purposes only and unreliable for operational purposes. That's what I meant by "they said not to use it"

**Comment by corradio** [comment]
What they mean is that we shouldn't use it for *billing*. That's because
they might get late information and update their data. That's the same with
ENTSOE.
We can still use it to display. They basically don't want to be liable in
case decisions involving $ are taken :)

**Comment by HansHyde** [comment]
@systemcatch fyi on fuelsource graphs - last night NYISO...

Daily Mix is NOT registering imports - Checked numbers
- Load (Reported) =                  23,185 MW
- Generation (Reported) =        18,967 MW  <-- from the Generation Mix graph
- Diff (Load - Gen)                    -4,218 MW
- Imports (Reported) =               3,862 MW

As I posted above, 35-40% of CAISO's load/generation is "unknown" for CO2eq calculations.

**Comment by corradio** [comment]
@HansHyde let's stick on using the proper issues.
#898 is for NYISO. This one is for CAISO.

**Comment by 7hibault** [comment]
@corradio won't the pro version involve $$ ?

**Comment by corradio** [comment]
No billing information, so it's fine. But thanks for questioning this!

**Comment by 7hibault** [comment]
Updated version of the parser here: https://github.com/7hibault/electricitymap/blob/master/parsers/US_CA.py

I will submit a PR but a few things before that:
- We should check the remarks from @HansHyde before addind this to prod. Have you checked that the difference is not somewhere in storage?
- How is the previous data generated? I'm not sure if the way I'm setting the date would break the history data generation.
- What should we do with the reported imports?
- Do you agree with this mapping?
```
    production_map = {
        'Solar': 'solar',
        'Wind': 'wind',
        'Geothermal': 'geothermal',
        'Biomass': 'biomass',
        'Biogas': 'gas',
        'Small hydro': 'hydro',
        'Coal': 'coal',
        'Nuclear': 'nuclear',
        'Natural gas': 'gas',
        'Large hydro': 'hydro',
        'Other': 'unknown'
    }
    storage_map = {
        'Batteries': 'battery'
    }
```

**Comment by corradio** [comment]
@7hibault let's rather talk on the PR to avoid too many messages on the issue.
Mapping looks good to me. My only concern is whether or not we should mix biogas and gas.
Do we know where imports come from?

**Comment by HansHyde** [comment]
@7hibault I am currently working on an excel workbook that will be able to account for these variations & "unknowns" for NYISO.  It should be able to be applied to CAISO & all the other Balancing Authorities in the US.

Here is a screenshot of the worksheet, that is supported by other worksheets in the excel workbook.

![nyiso - backend mechanics sample](https://user-images.githubusercontent.com/33690988/34041309-db12c51c-e197-11e7-88e1-175f5fc4c41a.png)

Maybe there is a way to import realtime data (ie from CAISO or NYISO) into Excel that you are aware of?  If so, that would be a great assistance to me, instead of manually importing current "realtime" data.

Thanks!

**Comment by brunolajoie** [comment]
@corradio @systemcatch for all other countries we"ve mapped TSO's biogas category to EMap's biomass one. Then, we can alway refine the c-int factor for biomass!

**Comment by corradio** [comment]
Sounds like the next step is to add imports/exports. Do we have any data for this? I think they have exchanges with multiple neighboring zones, so taking compounded imports won't work..

**Comment by HansHyde** [comment]
This is likely the case.... have you looked at the CAISO "ISO Today" app?  In that they give pricing across CA, NV, Utah.... Oregon???  in a regional all inclusive electric market perspective.  This will likely be the route to determining import/export pathways, then through other methods determining generation mix.

**Comment by corradio** [comment]
New issue specifically for imports:
https://github.com/tmrowco/electricitymap/issues/959

Thanks all for making this happening!

**Comment by Methanogen** [comment]
Hi,
It seems that you have done a lot of good work in this area!
I have been looking at negative prices for CAISO and have heard that Hydro is a factor. The daily sheet you refer to does provide 5-minute data for Small Hydro and for Large Hydro.
Have either of you compiled a time series that goes back months or even a year by any chance?
Regards,
David Willson

**Comment by brunolajoie** [comment]
@Methanogen thanks! yes we do, please contact us at hello@electricitymap.org!
