### ISSUE TITLE
AU-VIC <-> AU-NSW interconnector error

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#804]
We seem to have swapped the interconnector in the parser, cf this tweet: https://twitter.com/HMike01/status/924871957320933377

@jarek or @systemcatch  would you have time to debug the parser? I think it might apply to the other interconnectors too..

![image](https://user-images.githubusercontent.com/1655848/32156846-fdcf0bc8-bd3f-11e7-839b-1a242eb01122.png)

**Comment by systemcatch** [comment]
At a glance it seems that NSW-VIC, NSW- QLD and SA-VIC are going in the wrong direction.  TAS-VIC is correct.  @jarek how's it look to you?

**Comment by jarek** [comment]
The page in the screenshot is http://aemo.com.au/Electricity/National-Electricity-Market-NEM/Data-dashboard#nem-dispatch-overview

SA-VIC and TAS-VIC seem fine to me. NSW-VIC and NSW-QLD seem wrong.

**Comment by jarek** [comment]
While we're on the subject of AU interconnectors, I don't really understand the import/export limits. Right now most of them have exportlimit positive and importlimit negative, except for:

* TAS-VIC {"name":"T-V-MNSP1", "value":60.00000, "exportlimit":279.90000, "importlimit":60.00469} 
* one of NSW-QLD {"name":"N-Q-MNSP1", "value":-57.20000, "exportlimit":-57.20000, "importlimit":-136.70000}

Is this something to do with how the grid operates? TAS *cannot* export less than 60 MW to VIC or Bad Things will happen to The Grid? But I guess that's not used in the calculations, so less imporant...

**Comment by systemcatch** [comment]
Yup SA-VIC is actually correct.  As to the import/export limits maybe there are contracts in place between different regions which specify max electricity transfer in either direction.  I read that as max transfer to VIC is 279MW and max transfer to TAS is 60MW.
