### ISSUE TITLE
Data of previous days

### ISSUE THREAD

**Issue by Greenlaus** [tmrowco/electricitymap#807]
Dear team, 
this is a terrific site and I will certainly visit it very often - thanks for the work!
My proposal: it would be great if one could scroll back in time and view the data/weather conditions of the past (e.g. CO2 intensity of German electricity on windy days). Is this a money issue (storage capacity)?
Best regards + thanks again
Jutta

**Comment by corradio** [comment]
Hi @Greenlaus,

It's part of our professional offering (pro.electricitymap.org). Send us a mail if you're interested!

Olivier
