### ISSUE TITLE
Malaysia 🇲🇾

### ISSUE THREAD

**Issue by jarek** [tmrowco/electricitymap#809]
https://www.gso.org.my/LandingPage.aspx has data for Peninsular Malaysia (~80% of population) including total generation every 10 minutes, but fuel mix appears to only be on a per-day basis right now. There is already some fuel mix data for today (it is 18:00 in Malaysia), perhaps we can ask if they can publish at least hourly fuel mix?

As I understand it, https://www.gso.org.my/SystemData/TieLine.aspx  are interchanges - EGAT is the Thai operator so probably to Thailand (http://www2.egat.co.th/hvdc/INTRODUCTION.HTML), PLTG seems to be with Indonesia, and HVDC with Singapore (see https://github.com/tmrowco/electricitymap/blob/master/parsers/SG.py#L53). I don't know if positive means import or export.

**Comment by jarek** [comment]
*Actually* it looks like https://www.gso.org.my/SystemData/FuelMix.aspx might be providing current values when no date range is specified. Currently it gives a sum of 15012 MW which *just happens* to be exactly equal to the latest current generation reported in https://www.gso.org.my/SystemData/CurrentGen.aspx ? Should keep an eye on this for a few days.

**Comment by systemcatch** [comment]
Watching the Fuel mix link the sum total has matched the amount given in current generation for the past hour (6 datapoints).  How'd you find their website out of interest?

**Comment by jarek** [comment]
Yeah, it also holds for me now. We can re-check later but it seems feasible.

So I guess a parser should read the FuelMix.aspx and CurrentGen.aspx pages. Sum up the values in fuel mix and verify that the sum is the same as the latest value in current gen. If yes, report the fuel mix, using the timestamp of the latest value in current gen table.

For map, we will have to include all of Malaysia's subdivisions except for MY.SK and MY.SA, which are the states not in Peninsular Malaysia.

Sounds like a good first issue for someone, too! Feel free to reach out if you need some more help.

--

I was actually looking for Vietnam real-time data, which I didn't find, but http://en.evn.com.vn/ has a link to https://www.tnb.com.my/. TNB is the organisation that usually comes up when searching for "Malaysia electricity", and browsing around there, https://www.tnb.com.my/suppliers-investors-media-relations/daily-system-generation-summary has a link to http://www.st.gov.my/index.php/en/component/content/article/12-industry/364-commitment-schedule-ucs-and which doesn't have real-time data, but under "Industry" section of ST website I saw the link to GSO. Following links between different operators has been most productive for me...

**Comment by jarek** [comment]
Peninsular Malaysia now added by systemcatch :)

Remaining areas are the states of Sarawak and Sabah. They are presently not interconnected due to mountainous terrain. There is also a small island named Labuan, it seems to be connected to Sabah.

Their utilities are Sarawak Energy and Sabah Electricity (SESB) respectively. I have not yet seen real-time generation data for those, though I only looked briefly.

**Comment by systemcatch** [comment]
Places to start looking;

- [Sabah](https://www.sesb.com.my/)
- [Sarawak](http://www.sarawakenergy.com.my/)
- [General data for Malaysia](http://www.data.gov.my/)

**Comment by alixunderplatz** [comment]
@jarek @systemcatch if you like to add the imports/exports of Malaysia, I had a look at the data from
https://www.gso.org.my/SystemData/TieLine.aspx

Positive means export, negative means import. I calculated the balance of generation and demand, and what was left was very close to the balance of exchanges.

These are the meanings behind the interconnections:

![image](https://user-images.githubusercontent.com/25743609/37664460-b1222874-2c5b-11e8-862a-4362f4c0bec2.png)

**EGAT** and **HVDC** must be the connections with Thailand. 
- The EGAT values have constantly been near 0 MW in the last 2 weeks, so pobably it is offline? I suggest including it anyway. AC capacity is 80 MW. 
Positive is flow towards Thailand.
![image](https://user-images.githubusercontent.com/25743609/37664719-282d40c0-2c5c-11e8-9dea-14203727b3eb.png)

- The HVDC values show clear behaviour of a DC interconnector (~constant output over time). HVDC Capacity is 300 MW.
![image](https://user-images.githubusercontent.com/25743609/37664879-6052ce48-2c5c-11e8-8de7-de495d663e1f.png)

**PLTG** is leading to Singapore via two AC cables, capacity seems to be 2x 250 MVA : 
See:
![image](https://user-images.githubusercontent.com/25743609/37665168-fb6a2ca0-2c5c-11e8-9942-28fcf2ac00bf.png)
and:
![image](https://user-images.githubusercontent.com/25743609/37665200-0e1ed2ba-2c5d-11e8-96f2-0b75c05ab3ef.png)
from "Peninsular Malaysia Energy Supply Outlook 2017"

For similar info, see https://ms.wikipedia.org/wiki/Grid_Nasional#Sambungan_ke_Negara_Thai

**Comment by jarek** [comment]
Thanks for checking on that! That's a great compilation, will make implementation easy.

**Comment by jarek** [comment]
Hello,

Thanks everyone for your help on Malaysian data! As far as I understand, we've implemented all useful data available. Insular Malaysia is missing, but we haven't seen suitable data sources. As there is nothing more to do, I'll close this issue for now, but please do reopen it if more data is found.
