### ISSUE TITLE
Germany (and some other countries) do not show current data

### ISSUE THREAD

**Issue by Ablinne** [tmrowco/electricitymap#816]
Possibly due to the recent change from CEST to CET? It seems to have data from "one hour ago" all the time when scrobbling over the "** Carbon intensity in the last 24 hours **"

**Comment by corradio** [comment]
For Netherlands, see https://github.com/tmrowco/electricitymap/issues/78
For Germany, data is actually delayed by much more than 1h.
We get data from ENTSOE, and they are reporting empty values:

![image](https://user-images.githubusercontent.com/1655848/32283110-c7917d9e-bf23-11e7-9fdd-f6263cb0c087.png)

**Comment by corradio** [comment]
I'm closing this as there's nothing we can do. Let's keep an eye out however.
