### ISSUE TITLE
Germany installed capacity wrong in staging

### ISSUE THREAD

**Issue by icfly2** [tmrowco/electricitymap#824]
In the released map th einstalled capacities are correct, in the staging one, German capacity is correct in the strings but the bar displaying the max capacity is wrong for wind, solar, gas and coal. (It shows 63 GW the overall max demand)

**Comment by icfly2** [comment]
Correct: https://www.electricitymap.org/?wind=false&solar=false&page=country&countryCode=DE
Wrong: https://staging.electricitymap.org/?wind=false&solar=false&page=country&countryCode=DE

**Comment by corradio** [comment]
@brunolajoie can you double check? Thanks for reporting @icfly2 !

**Comment by icfly2** [comment]
Other countries i checked at random were fine in both maps.

**Comment by corradio** [comment]
@icfly2  I have deleted your comment with the link to staging because we want to avoid people going there (so we keep the link private)

**Comment by icfly2** [comment]
So turns out a few other nations (USA, Quebec have this problem too, Spain on the other hand doesn't)

**Comment by corradio** [comment]
Bug identified, we're on it.
