### ISSUE TITLE
ES6 transpiler does not work with cordova iOS

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#826]
@BrianCraig I had to disable ES6 transpiler as the cordova iOS app did not start because of it.
ref: https://github.com/tmrowco/electricitymap/commit/1635002164d8498b7d5ba1428b582e20ed8c0a09

We should try to pinpoint exactly the source of the error. I wasn't able to pull out the error because my Safari webview inspector was buggy.
Maybe a good first step is to add 'use strict' to all modules to correct all silly mistakes.

**Comment by BrianCraig** [comment]
I'm sorry, i don't have an IOS, neither a MacOs for XCode, so i cannot test it on IOS.

Yes, it would be nice to start using 'use strict', that also arises errors on my IDE before compiling.

**Comment by corradio** [comment]
I'll try to figure out what caused the error.
