### ISSUE TITLE
Use server-side geoloc. to speed up app launch

### ISSUE THREAD

**Issue by brunolajoie** [tmrowco/electricitymap#829]

**Comment by brunolajoie** [comment]
At the moment, we call the GPS from the phone at app launch, with a timeout of 5seconds. It can be very slow if the user has a bad GPS signal. We could think about using the IP adress provided at the API call to determine user localization faster

**Comment by corradio** [comment]
Note: remember to publish app on Huawei store when this is done:
http://developer.huawei.com/consumer/en/openPlatform/mcindex-corp.html#/application=100143607/service/hiGameDetail=101448869
