### ISSUE TITLE
Tooltip always compute wrongly: "0% emission in ... comes from ..."

### ISSUE THREAD

**Issue by brunolajoie** [tmrowco/electricitymap#844]
![fullscreen_10_11_2017__00_15](https://user-images.githubusercontent.com/22095643/32634580-988bb296-c5ac-11e7-9f3c-fcd3ba4a38d8.png)

**Comment by corradio** [comment]
Can you try to fix? Relevant code should be in helpers/tooltip.js.
Also, maybe the data object is not containing the right values.

**Comment by corradio** [comment]
@brunolajoie any luck?

**Comment by brunolajoie** [comment]
@corradio Can you put a proper test state in the master of electricitymap
repo, so I can test & debug it offline?

*Bruno Lajoie*
+33 6 67 95 10 92
brunolajoie@gmail.com
