### ISSUE TITLE
Asymmetrically placing of boxes when multi-line caption

### ISSUE THREAD

**Issue by magol** [tmrowco/electricitymap#850]
When the captions have different many lines of text, the boxes are placed asymmetrically to each other.

![image](https://user-images.githubusercontent.com/493140/32772752-2471da4c-c927-11e7-90b3-6ecfa5978a37.png)

**Comment by corradio** [comment]
Indeed. This would require having a grid layout (or stacking divs).
Anyone wants to take a look at this?
This really makes me think we should switch to React asap.
