### ISSUE TITLE
Data for South Korea

### ISSUE THREAD

**Issue by jarek** [tmrowco/electricitymap#855]
Organizationally, everything is ran by KEPCO: integrated utility doing ~90% of generation and all of distribution and end user billing.

I didn't find the exact data we need yet, but here is some of my research for the future:

"Big Data Center" http://home.kepco.co.kr/kepco/BD/bigData/main/bigDataMain.do

http://home.kepco.co.kr/kepco/BD/BDBAPP001/BDBAPP001.do has monthly statistics (currently up to 2017-09)

http://nrgmap.kepco.co.kr/einfo/viewDynamicPage.do has a dashboard that seems the best so far, hourly/15 minute consumption by region, but I didn't find fuel info

KPX "Korea Power Exchange" at http://www.kpx.or.kr/ and http://epsis.kpx.or.kr/ appears to have more more market data

http://epsis.kpx.or.kr/epsisnew/selectEkgeFfuChart.do?menuId=040300 - only historical up to 2015

http://www.kmos.kr/start.jsp has Windows and Android apps for some market software - looks like it's in Korean only and I don't know if it requires login or has fuel breakdown. If it's promising, the app could be decompiled to see the source URLs, if it doesn't require login.
Possibly http://www.kmos.kr/pluginfile/SmartKPX_manual_v2.pdf page 36 shows fuel breakdown?

**Comment by jarek** [comment]
I looked again and I didn't see live fuel data yet. I also downloaded the Android app but it requires login. In absence of data we can use, we can't do anything, so I will close the issue for now. Please do reopen if you find real-time fuel mix!

**Comment by tmslaine** [comment]
Some data sources:
https://www.kpx.or.kr/eng/index.do has real-time consumption
https://www.kpx.or.kr/eng/contents.do?key=307#n has information on conventional power plant ownership, Korean version of the same site has more power plants

http://cms.khnp.co.kr/eng/kori/realTimeMgr/list.do?mnCd=EN03020201&brnchCd=BR0302 and the respective sites for Hanbit, Wolsong, Hanul and Saeul have real-time nuclear production
http://cms.khnp.co.kr/eng/realTimeMgr/water.do?mnCd=EN04020301 has real-time data for KHNP-owned regular hydro power plants(?), the site is possibly stuck at roughly 300 MW

https://dataopen.kospo.co.kr/data/pwrGenTranList.do has power plant level d-1 hourly data published by KEPCO subsidiary KOSPO
