### ISSUE TITLE
Wind and Solar potential missing

### ISSUE THREAD

**Issue by ACParis** [tmrowco/electricitymap#857]
L'application "Electricity map" n'affiche plus le potentiel éolien (depuis hier sauf erreur de ma part.
Est-il prévu de rétablir cette indication fort utile ?

**Comment by systemcatch** [comment]
Seems like the solar potential is missing as well when I check the map.  This is likely a gap/bug in the data provided by [GFS](http://nomads.ncep.noaa.gov/).

**Comment by corradio** [comment]
Thanks for raising the issue.
The fix has been pushed. The wind/solar layers will be up again soon, depending on how quickly the caches get invalidated.
NExt time feel free to ping me on Slack. I was busy at COP23 but managed to update just in time!

Olivier
