### ISSUE TITLE
PYISO issue with US

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#864]
![image](https://user-images.githubusercontent.com/1655848/33124314-cdff56e2-cf7c-11e7-9b55-1096d9ddc58f.png)

![image](https://user-images.githubusercontent.com/1655848/33124309-c7c0b5fa-cf7c-11e7-8890-a0d6a17356e9.png)

**Comment by systemcatch** [comment]
It looks like the New York ISO have changed one of the column names on the fuel mix csv [here](http://mis.nyiso.com/public/P-63list.htm).

**Comment by systemcatch** [comment]
There is now a [PR](https://github.com/WattTime/pyiso/pull/183) that should hopefully fix this issue once it gets merged.

**Comment by r24mille** [comment]
WattTime/pyiso#183 has been merged into `master`. For electricitymap, this bug should be able to be fixed after:
1. the next version of `pyiso` gets packaged for PyPI, and 
2. https://github.com/tmrowco/electricitymap/blob/master/parsers/requirements.txt will need the `pyiso` version increased to that release.

I can try and get details from WattTime maintainers about when the next release will be packaged for PyPI.

**Comment by corradio** [comment]
Good news! Keep us updated.

**Comment by corradio** [comment]
Not relevant anymore as we don't use pyiso
