### ISSUE TITLE
Incorrect Italian translation

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#865]
Received by email:
>  please correct the Italian translation for Geothermal it should be "Geotermico" and not Geotermale as it is now

**Comment by icfly2** [comment]
According to my Italian, energy engineering colleague, Geotermico is correct.

**Comment by systemcatch** [comment]
@icfly2 the file for the Italian translation is [here](https://github.com/tmrowco/electricitymap/blob/master/web/locales/it.json), do you want to correct it?

**Comment by icfly2** [comment]
Sure, i'll issue a PR this evening

**Comment by icfly2** [comment]
I say that, I'm getting 403 for trying to push a  new branch to make a PR. Any magic I'm missing?
