### ISSUE TITLE
ENTSOE parser might not update past values

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#868]
Due to the logic in https://github.com/tmrowco/electricitymap/blob/master/parsers/ENTSOE.py#L396, the ENTSOE parser might ignore past datetimes that have a number of valid items less than the max number of valid items across all past datetimes asked for.
This is a problem some previous datetime has one value becoming missing, and others updated, as this datetime will be ignored and thus not updated in the db.

**Comment by jarek** [comment]
Oli, I've been looking through past bugs. Do you know if this issue got resolved since you logged it? Maybe when we added in more functionality to fetch backdated data in #1178?

**Comment by corradio** [comment]
This is still an issue IMO, but the new line ref is https://github.com/tmrowco/electricitymap/blob/master/parsers/ENTSOE.py#L579

**Comment by systemcatch** [comment]
Maybe the target_datetime parameter could be used to fill in gaps in the data?
