### ISSUE TITLE
South Australia Battery

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#869]
Apparently there's data here:
https://ausrealtimefueltype.global-roam.com/expanded

- [x] Add UI
- [x] Add data
- [ ] Add LCA GHG parameters

**Comment by corradio** [comment]
@systemcatch take a look at this article:
https://electrek.co/2017/11/30/tesla-100mw-battery-flexes-muscles-early-this-morning-delivers-70mw-of-stored-wind-energy-shows-off-fast-switching/?lipi=urn%3Ali%3Apage%3Ad_flagship3_feed%3B0Dkt70O6RUe9LRMLgFNNHw%3D%3D
I think the data source mentioned there might be better. For now I see only little charging..

**Comment by systemcatch** [comment]
@corradio You think the current data source is wrong?  From what I can see the source in the tweet shows only very slow charging as well.

NEMO does not have it yet.

**Comment by corradio** [comment]
Indeed. Let's keep an eye on this. At some point it was charging with 30MW - just want to make sure our data source is right.

**Comment by systemcatch** [comment]
@corradio Reading the nemlog api I think this is a better data source and we should switch the parser to use it.  Doesn't look like the battery has discharged to the grid yet, only charged in bursts.

**Comment by corradio** [comment]
I actually agree

**Comment by systemcatch** [comment]
Ok I will make the necessary changes.

**Comment by systemcatch** [comment]
There was a big charge at about 8am today, 70MW for 1hr.  Don't know if we missed it due to being offline though.

**Comment by corradio** [comment]
yes unfortunately the server was down, and because the parsers don't fetch data back in time we missed it :(
