### ISSUE TITLE
Faroe Islands(shaded) full installed capacity isn't shown

### ISSUE THREAD

**Issue by Bjarkigd** [tmrowco/electricitymap#877]
As can be seen in the image below, only the production numbers are shown, 

![udklip](https://user-images.githubusercontent.com/34088277/33397936-2c791726-d545-11e7-8d7b-a8db939379e7.PNG)

However when moving the cursor down to the CO2 Intensity or the "Origin of electricity in the last 24 hours" graphs then the shaded full capacity is shown up top. 

![unavngivet](https://user-images.githubusercontent.com/34088277/33398147-df264e8e-d545-11e7-996a-ab423e118e6f.png)

That being said, great job guys and keep it up, I'm a big fan of the map and use it quite regularily.

**Comment by jarek** [comment]
Could this be because the FO.py parser always returns `capacity: {}` in `fetch_production`?

**Comment by systemcatch** [comment]
I don't see this bug anymore on the production site, how about you guys?

**Comment by alixunderplatz** [comment]
@systemcatch don't see the bug, too!

**Comment by corradio** [comment]
I think @brunolajoie fixed it!
