### ISSUE TITLE
Global metrics

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#878]
Just received an email with a great idea: showing worldwide carbon intensity and % renewable.
I personally love that idea :)

**Comment by nathanjmassey** [comment]
It would be cool if after clicking on the current worldwide figure, it would take you to a graph showing the data for the last 24 hours.

I think this would show some quite interesting information (e.g how is carbon intensity effected when country x starts their day?)

**Comment by corradio** [comment]
cc @jbuverud (for inspiration).
Closing unless something has strong opinions.
