### ISSUE TITLE
Origin of electricity in the last 24 hours 

### ISSUE THREAD

**Issue by kharald** [tmrowco/electricitymap#884]
The graph _Origin of electricity in the last 24 hours_ is very helpful. I would although suggest to sort the categories a bit different. Put the categories with highest capacity factor in the bottom (i.e. with smallest variability) and categories with lowest categories (i.e. with highest variability) at the top.

Suggested order from bottom to top

1. unknown
2. nuclear (ca 80-90%)
3. geothermal (ca 80-90%)
4. coal (ca 70-80%)
5. biomass (ca 70-80%)
6. gas (ca 40-50%)
7. hydro (ca 40-50%)
8. hydro storage (ca 40-50%)
9. wind (ca 30-40%)
10. solar (ca 10-20%)
11. oil (ca 10-20%)

Sounds reasonable?

**Comment by corradio** [comment]
Actually, we've chosen to put categories with the highest variability at
the bottom.
That makes is very simple to see the magnitude of the variation. If you put
them at the top, you can't see the variability.
Furthermore, I find it quite nice to see that wind "eats" the other layers
just above it (hence why we put hydro above wind).

Olivier

**Comment by kharald** [comment]
Maybe. Instead its a lot harder to see the other sources are not variable. Fraunhofer ISE [_Energy Charts_](https://energy-charts.de/power.htm) have yet another way to stack the graph but a bit closer to my idea.
One option is to have this user selectable but then you loose a bit simplicity.
A matter of taste perhaps.

**Comment by corradio** [comment]
Maybe it's worth producing side-by-side comparaison?

Olivier

**Comment by kharald** [comment]
Not sure how that will look like?

**Comment by corradio** [comment]
I was thinking: build the frontend, change the order, take screenshots,
post here.

**Comment by kharald** [comment]
Sounds like a plan.

**Comment by magol** [comment]
I was actually thinking about posting your own issue with a similar proposal as @kharald. I also think it's difficult to get an overview when everything is moved up and down as variables power sources are changing.

**Comment by HansHyde** [comment]
The past 24hr generation mix graph at the bottom is indeed nice. Its order of stacking will probably never please everyone, but least variable does have its appeal.

Another visualization method may be (in addition to the graph) having a slider bar/vertical line on each generation source current production bar that registers/marks that gen type's peak (highest production) for the last 24 hrs.

**Comment by corradio** [comment]
I'm closing this one due to inactivity. Feel free to re-open if you have an example chart in order to discuss/improve!
