### ISSUE TITLE
Greenland

### ISSUE THREAD

**Issue by Bjarkigd** [tmrowco/electricitymap#886]
While there's no live data. Greenlands capacity is 118,38MW of Diesel Generation and 91,35MW of Hydro, and at least 117,3kW solar and 20k wind installed on a trial basis. 

That's an improvement from 100% Diesel in 1992 to 62% Hydro generation in 2015 and it is only getting greener.

https://www.nukissiorfiit.gl/nukissiorfiit/kort/?lang=da

If someone would like to add that info to the map then go ahead.

**Comment by systemcatch** [comment]
That's an impressive shift away from diesel.

**Comment by corradio** [comment]
Closing as we don't have real-time data
