### ISSUE TITLE
Bulgaria is missing

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#890]

**Comment by systemcatch** [comment]
Belgium and Italy have also been missing for a while.

**Comment by stgram** [comment]
As far as I can see in the [BG parser](https://github.com/tmrowco/electricitymap/blob/master/parsers/BG.py) the values are obtained from tso.bg, which is no longer an active domain. Instead the Bulgarian Operator is currently housed under eso.bg, with the operational data provided here: http://www.eso.bg/?did=124 . Looking at the python code, the parser looks for a table that looks identical to the one in the active link, from which it extracts data to send to the website.
In my opinion simply changing the url would fix the problem, but I am not competent in Python to verify that, if somebody could help that would be greatly appreciated.

**Comment by systemcatch** [comment]
Ah I thought Bulgaria was part of the ENTSOE parser but clearly it's separate.

@stgram I quickly tried the new url in the parser but it throws errors with the datetime.  Looking at the page source the data is still in a table but certain parts have changed enough that altering the parser is needed.  If you wanted to have a go at fixing it we could help out if you get stuck, shouldn't need any extra modules or more complex code.

**Comment by stgram** [comment]
@systemcatch Thank you for the response. Unfortunately I am not familiar with Py, I only understand the general concept of the code. Looking at the [source of the page](view-source:http://www.eso.bg/?did=124) the datetime is on line 81:
```
<div class='dashboardDiv'>
<div class='dashboardCaptionDiv'>Генерация и товар на ЕЕС за <b>
04.12.2017 20:53:14  </b></div>
<center><small style='color:#555;'>
```

The parser used to look for a tag with the id lblTecDate, which does not exist anymore.
```
datetime = None
    local_time = soup.find(id='lblTecDate')
    if local_time:
        time = local_time.string.split(':')
        if len(time) == 3:
            datetime = arrow.now('Europe/Sofia').floor('day').\
                replace(hour=int(time[0]), minute=int(time[1]), second=int(time[2]))
    if not datetime:
        raise Exception('No datetime')
```
Instead would it be possible to fetch the content of the div tag, which includes the whole date & time information? I found this [documentation](https://www.crummy.com/software/BeautifulSoup/bs4/doc/#id12) on the issue, searching for the bulgarian text "Генерация и товар на ЕЕС за" in the tag should return the whole tag, from which the datetime could be extracted, or perhaps a regex expression for the datetime format? I cannot understand how the arrow commands work.
Please help me with the issue, if you need assistance with the bulgarian language I am here to translate.

**Comment by systemcatch** [comment]
I would do the following to find the tag.  The div class attribute is not unique so we also search by text.  Then we find the b tag and get the text within. 

```python
div = soup.find('div', 'class' = 'dashboardCaptionDiv', text = 'Генерация и товар на ЕЕС за')
b = div.find('b')
time_string = b.contents
```
We can use the [strptime method](https://docs.python.org/2.7/library/datetime.html#datetime.datetime.strptime) to convert the time string into a datetime object.

**Comment by stgram** [comment]
Could somebody try this? Sounds like a simple thing, lets get one more country on the map!
