### ISSUE TITLE
Add currency information / tooltip

### ISSUE THREAD

**Issue by Bjarkigd** [tmrowco/electricitymap#897]
The price of electricty is (at least as far as I can see) not indicated by what currency it is in, I'm assuming it is in whatever local currency any given country uses, but one could also easily (imho) be led to think it's all in the same currency, and then assume $, € or whatever.

**Comment by systemcatch** [comment]
Prices were partly removed in #744, looks like currency wasn't added to the replacement graph.

**Comment by corradio** [comment]
Indeed. We have currency information but it simply needs to be added to the
graph. A tooltip would be nice too!

**Comment by Bjarkigd** [comment]
A zoom button would be good as well, some of the smaller countries can be a bit tricky to see clearly.

**Comment by corradio** [comment]
See https://github.com/tmrowco/electricitymap/issues/504 for the zoom issue.
