### ISSUE TITLE
Country vs Region

### ISSUE THREAD

**Issue by magol** [tmrowco/electricitymap#908]
More and more countries are divided into different regions. It is interesting if you want to see the details, but on a higher level it becomes too detailed.

I suggest that you can choose whether to look at the regional level, or just at the country level (where the numbers are summed up for all regions in each country).

If you choose to look at it with country level, the map only shows the borders of the countries, and hides the regions in each country. The map then becomes cleaner and it is easier to navigate.

**Comment by corradio** [comment]
I suggest having a thicker line that delimits the country (and keep regions visible within).
The reason is that we have quite a few countries for which we don't have all states, and thus we wouldn't be able to aggregate to country level.

**Comment by HansHyde** [comment]
@magol 

10 largest countries - 
Russia:  17,075,200 km2 (6,592,771 mi 2)
Canada: 9,984,670 km2 (3,854,082 mi2)
United States: 9,631,418 km2 (3,717,727 mi2)
China: 9,596,960 km2 (3,704,426 mi2)
Brazil: 8,511,965 km2 (3,285,618 mi2)
Australia: 7,686,850 km2 (2,967,124 mi2)
India: 3,287,590 km2 (1,269,009 mi2)
Argentina: 2,766,890 km2 (1,068,019 mi2)
Kazakhstan: 2,717,300 km2 (1,048,877 mi2)
Algeria: 2,381,740 km2 (919,352 mi2)

US, CAN, India, Australia - have known different regions for electrical & CO2 gen purposes
Russia - maybe different regions, but also likely State Controlled - ability to get access to data???
The 5 others - most likely State Controlled utilities - unlikely for any need to divide countries into regions

All other countries - ask are the utilities State Owned.  If answer is yes, there is no need to divide the countries, data is unlikely to be divided by region as is.

**Comment by magol** [comment]
@corradio That makes sense

This may be more interesting when we begin to get more complete data for most countries.

@HansHyde This might be a bit more complex than I first thought.

Maybe we can handle physical states (eg, US states) and logical regions (eg bidding areas, separate electricity systems, etc.) different?

**Comment by HansHyde** [comment]
@magol please see #903 - because it is far more complex than anyone is thinking, and state lines are not going to work in the US.

**Comment by corradio** [comment]
@magol I agree with you but I'm going to close this one as we won't have time to work on it currently.
The roadmap I have in mind is:
- add ability to have geoJSON
- update the map layer to mapbox-gl to have better performances
- add data at multiple granularities (i.e. creates aggregates), and find a way to show it in the frontend as you suggest

Once we have mapbox-gl working we can start working on this (and it will be quite natural to do so, hence closing this issue to try to keep the number small)
