### ISSUE TITLE
Ranking in alphabetical order

### ISSUE THREAD

**Issue by magol** [tmrowco/electricitymap#909]
It's starting to be many countries, and finding a particular country in the ranking list can be hard. I suggest that you can choose to see the list in alphabetical order.

As an alternative (or complement) you may add a search box. If you write the first letters of a country, the country will be highlighted in the list and on the map.

This may be good if you do not know where on the map a particular country is located, or if it's so small that it's hard to select on the map.

**Comment by corradio** [comment]
Makes sense!

**Comment by systemcatch** [comment]
Search box is now in place!
