### ISSUE TITLE
ValueError: CL-SING: key unknown has negative value -21832.63

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#912]
```
feeder_1  | Exception while fetching production of CL-SING
feeder_1  | Traceback (most recent call last):
feeder_1  |   File "feeder.py", line 174, in fetch_production
feeder_1  |     validate_production(obj, country_code)
feeder_1  |   File "/home/feeder/lib_electricitymap/parsers/lib/quality.py", line 36, in validate_production
feeder_1  |     if v < 0: raise ValueError('%s: key %s has negative value %s' % (country_code, k, v))
feeder_1  | ValueError: CL-SING: key unknown has negative value -21832.63
```

**Comment by systemcatch** [comment]
![cl_spike](https://user-images.githubusercontent.com/30196510/33987387-a3b36b1a-e0b8-11e7-8fe4-a8492475baeb.png)
There was a big spike in generation around 6pm and midnight (UTC-4) which must of been bad data as the totals were 5x installed capacity.  Is this error repeating?

**Comment by corradio** [comment]
Indeed. Right now the whole history is not kept because a couple of data
points are invalid. We should probably only ignore the failing datapoints.

**Comment by systemcatch** [comment]
Yes it should drop the bad ones from the list and keep the good.  Just needs to loop over the list and check each dictionary.

**Comment by systemcatch** [comment]
feeder.py is in the backend so there's not much more that can be done with this issue.  One thing that comes to mind is whether it's worth open sourcing feeder.py like you did with quality.py so others can fix problems with it.  Obviously if there's sensitive stuff inside then don't but food for thought otherwise.

**Comment by corradio** [comment]
Yes this was my original thought. I'll look at this.

**Comment by systemcatch** [comment]
Cool I'll close this for now.
