### ISSUE TITLE
GeoJSON support

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#913]
We should probably merge the `topogen.js` script and the `countrytopos.js` in order to produce compressed a geoJSON file that we can use in any GIS system.
Furthermore, this will allow us to incorporate custom geometries.

**Comment by HansHyde** [comment]
Can you link to a thread or list types of files that can be used for geography shape files please?

**Comment by corradio** [comment]
What do you mean? The file type that I suggest we add support for is GeoJSON.
It relates to a large number of issues already existing.

**Comment by HansHyde** [comment]
Ok, GeoJSON is the target/goal for shape files to be used.

What type of shape file formats would you be able to convert/edit/modify into GeoJSON?  I am asking so I can help track down shape files/geometries we can use for... notably the US.

**Comment by corradio** [comment]
I think shapefiles (.shp) are easy to convert to geojson. I don't know of other formats as I'm not a GIS expert but some others might be able to help.

**Comment by HansHyde** [comment]
Great!  Can you tag a few others who have been helping in this area please, so they can provide some guidance?  Thanks!

**Comment by corradio** [comment]
@jarek @systemcatch I just discovered that we actually already support geoJSON.
In https://github.com/tmrowco/electricitymap/blob/master/web/app/countrytopos.js#L68, the countries object has as value a geoJSON object.
The `topojson.merge` command merges topoJSON and converts to geoJSON, which also means that we can simply import a geoJSON and assign it to a country!

I'll focus on rewriting that part to have higher performances and faster loading time, but in the meantime, feel free to add custom geometries if needed. Let's however try to stick to natural earth as much as possible.

Olivier
