### ISSUE TITLE
"Gas", "Coal" & "Battery" definitions - Subcategories

### ISSUE THREAD

**Issue by HansHyde** [tmrowco/electricitymap#915]
**_"Gas"_** - There are 5 or 6 distinct generation profiles impacting CO2eq per MW.  The differences are not small, and depending upon installed fleet in the "Region/Country", this will affect net CO2eq significantly.  

For example, a CT (Combustion Turbine) can have a CO2eq/MW twice that of a CCGT or H-Frame.  From 30% to 60% efficiencies.

**Suggested "Gas" Types** 

1. "Gas1" - 
2. "Gas2" -
3. "Gas3" - 
4. "Gas4" -
5. "Gas5" - 
6. "Gas6" - CHP - Combined Heat & Power (ie District Heating or Process Heat with electric generation).  CHP can take efficiency to 80-85% in a MWinput-energy = MWe + MWth.

**_"Coal"_** is similar, although the variation by generation plant is much less, 30 - 45% efficiencies.  However, brown vs black results in a much larger variation in CO2eq per MW. 

**Suggested "Coal" Types**
      - Realtime data is available for Germany (black vs brown coal)

1. "Coal1" - Black/Hard - new (i.e. SuperCritical, UltraCritical - these are in Japan & Germany for example - efficiencies up to 45%)
2. "Coal2" - Black/Hard - old (i.e. sub SC/UC - much of the world - efficiencies up to 35%)
3. "Coal3" - Brown/Lignite - new (i.e. SC/UC - newer German fleet)
4. "Coal4" - Brown/Lignite - old (i.e. sub SC/UC)
5. "Coal5" - CHP - Combined Heat & Power (i.e. Germany, Bulgaria & I believe Finland has this)

- [ ]  I can "filling in the blanks" if this is an approach we'd like to take.

**A Note on Batteries**

There are currently no batteries in the world that are used for "bulk power storage" - they are only used for localized grid balancing at this point in time.  Even the Tesla battery in South Australia only has a "bulk storage" capability of a few to tens of minutes for SA's regional grid.  

For example, 
SA average load 4,000 MW x 24 hours = 96,000 MWhr
Tesla Battery = 100 MW (instant flow in/out) by 150 MWhr capacity
Tesla Battery vs SA Average Load =  3.775%  = 2 minutes & 20 seconds

Total yearly production output of Telsa's Gigafactory in Nevada (once it is fully operational) is around 32,000 MWhr of capacity.  If all of it was to be used in California for "bulk storage" (which it will not be) against a 25,000 MW average load = ~45 minutes

This said - listing batteries in the generation profile section is likely to never (in the short term) register a visible value on the bar charts.  One day yes, but not for the next 5 years anyways.

A reasonable defined category might be "Non-Pumped Hydro Storage", which might include chemical batteries, "gravity storage rail cars" (which looks promising for bulk electrical storage) or more importantly currently - **_Demand Response_**.

**Comment by alixunderplatz** [comment]
@HansHyde I agree, some sub-categories are definitely needed, especially for seperating lignite and hard coal (as well as peat from biomass, btw!).
However, I think it is nearly impossible to seperate the capacities/generation for the different sub-types of coal and gas power plants. There are too many units/power plants, too many differences throughout the countries and realiable sources for the actual category and heat output of a power plant are very hard to find.

I'm not sure how/whether the various efficiencies are already covered in the IPCC emission factors which are used here.

**Comment by corradio** [comment]
For the first part, see #162 (also applies to gas)
For the second, the reason we have battery as an separate line is exactly to show the order of magnitudes that you are talking about.
I'm closing this one as it's a duplicate.

**Comment by HansHyde** [comment]
@alixunderplatz  I would agree it may be difficult to find, but I do not think it is impossible.  

I just reached out to some good sources which will be able to get me Heat Rates and charts based on the above.  Once a country/region's fleet is examined (again not impossible), capacity for each "type" could be assigned.  Until a time when it's determined, possibly a "default" type is used based on the IPCC averages - basically what is being used now.

If I understand the backend coding, "Gas" kicks out the IPCC default value.  Adding a "Gas1", "Gas2", etc., table with appropriate values, would then be assigned in the code for the country/region when the generation mix is mapped.

I would also say, within the backend coding, "well informed decisions" will need to be made based on known factors.  For example, Country X has 100% black coal, Country Y has 100% lignite and Country Z is 50/50.
