### ISSUE TITLE
ENTSOE geojson bidding zones

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#917]
It would be great if we could find ENTSOE geojsons for the bidding zones in order to start increasing granularity!

**Comment by tmsLaine** [comment]
For Norway one way to get price zones is through the NVE map service:
For example https://temakart.nve.no/link/?link=vannkraft
Click "Kartlag", uncheck "NVE vannkraft utbygd og ikke utbygd" and select "NVE Elspot områder"  in the dropbox. Then one can draw the polygons manually on the map using the red and yellow lines as a reference and download them as ESRI shapefiles. Conversion to geojson should be simple using for example geopandas.

For Denmark one can use the administrative regions.
DK1 = Nordjylland, Midtjylland and Syddanmark
DK2 =Sjælland, Hovedstaden (incl. Bornholm)
One reference is:
http://driftsdata.statnett.no/Web/map/snpscustom
Also the Danish TSO themselves show the exchange between Fynn Island and Sjælland
on energinet.dk

For Sweden polygons in json format for price areas can be found in the source code of:
https://www.natomraden.se/
The SE3 polygon lacks Åland Islands. A source for them belonging to the Swedish bidding zone is the Finnish TSO Fingrid: https://www.fingrid.fi/en/electricity-market/cross-border-transmission/power-transfer-between-aland-and-sweden/

For Italy http://www.mercatoelettrico.org/En/mercati/MercatoElettrico/Zone.aspx has a list of how Italian administrative regions are split into bidding zones.

**Comment by corradio** [comment]
Closing this and replacing by #1381
