### ISSUE TITLE
World resources data

### ISSUE THREAD

**Issue by tewllew** [tmrowco/electricitymap#919]
Hi, I'm sure it would create too many layers and may deviate from your main objectives but have you guys though of using any data about world resources? Www.wri.org have loads of data sets. Could be interesting to visualise the flux between where our resources come from and where energy is used.

**Comment by corradio** [comment]
Hi @tewllew ,

It's definitely a good idea, but not one we will pursue in this particular project. It's on our radar :)

Olivier
