### ISSUE TITLE
EXCESSIVE value assignation in biomass

### ISSUE THREAD

**Issue by jluzuria2001** [tmrowco/electricitymap#921]
We found a possible error in the emission intensity assigned to the biomass of [230 gCO2e/kWh] 
due to from our point of view it is EXCESSIVE.
You can check that this value is less in this publication (page 135 - http://www.revistasice.com/CachePDF/CICE_83_117-140__78E2E154C2BB213409D09C083013930C.pdf - ) made by Complutense University of Madrid, that said: "En cuanto a biomasa, distingue 7 tipos, siendo las respectivas estimaciones de gCO2e/kWh 14, 22, 23, 27, 31, 35 y 41."

Thank you so much.

**Comment by corradio** [comment]
Hi @jluzuria2001,
Thanks for raising this. Can you explain briefly what the biggest difference is with the IPCC number we currently use? We should have a very good reason to change from a worldwide accepted IPCC publication to something else.
Also, do you have the study in english?
Olivier

**Comment by thomasgibon** [comment]
If I may chime in to clarify the issue: the publication that @jluzuria2001 refers to is based on a Sovacool (2008) publication, itself reusing 2005 numbers from a widely-cited [paper by Martin Pehnt](https://www.sciencedirect.com/science/article/pii/S0960148105000662).

On the other hand, the review paper that the IPCC is using is a [2012 article](**http://iopscience.iop.org/article/10.1088/1748-9326/7/4/045902/pdf) covering more ground: they use more sources, they account for differences in albedo, carbon reabsorption over time (i.e. accounting for increased radiative forcing as long as carbon is still in the atmosphere "waiting" to be reabsorbed in the biogenic cycle), etc. The [supporting information](http://iopscience.iop.org/1748-9326/7/4/045902/media/erl437090suppdata.pdf) is particularly interesting to understand the time dynamics of the biogenic carbon cycle, I invite you to look at the figures.

In this regard, the IPCC numbers are the most refined and realistic. They are the state of the art and should be kept.

**Comment by jluzuria2001** [comment]
Thank you @thomasgibon for your clarification.

**Comment by corradio** [comment]
@thomasgibon I'm closing the issue in light of your message (keeping the IPCC values).
Feel free to re-open if I misunderstood something.
