### ISSUE TITLE
Add Moldova

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap#926]
Hey guys,

another part of the puzzle: I just found a site with accessible data for generation and cross-border exchanges for **Moldova**.

http://www.moldelectrica.md/ro/activity/system_state

![image](https://user-images.githubusercontent.com/25743609/34084338-8abbd552-e37e-11e7-9fd5-c6a82ad3bd27.png)

The best thing about it: **it refreshes every minute** and provides the latest numbers.

**POWER PLANTS**:
Numbers next to the symbols represent the electricity generation of the following plants:
- The two NHE are hydro power plants,
- the three units displayed as "CET" run on natural gas and are CHPPs, 
- and the "CERS" power plant may run on multiple fuels, such as gas, coal or oil.

**EMISSION FACTORS**:
For the **unknown CERS fuel-mix**, I would suggest using the "other" category with **700 g/kWh**.

For the **CETs**, I found a [document](https://www.google.de/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjhvbnshpLYAhWIEVAKHaIIACQQFgguMAA&url=http%3A%2F%2Fget-moldau.de%2Fdownload%2Fpolicypapers%2F2010%2FGET%2520Moldova_PP%252001%25202010_en.pdf&usg=AOvVaw37WEhiS1RHEn9lR52Ono--) saying the CET's efficiency may be as low as 22% or lower:
 
![image](https://user-images.githubusercontent.com/25743609/34084317-3dee7482-e37e-11e7-8deb-6830db71dc9f.png)

The emission factor should be higher than for modern efficient gas power plants. Based on the efficiency of 22% and released emissions of ca.[ 220 g/kWh(gas)](http://www.klimaneutral-handeln.de/php/kompens-berechnen.php#rechner) **a country-specific gas emission factor of 1,000 g/kWh(el)** for generation of the CET-units might be applied. 

Seems like Estonia and Poland get another carbon-intensive companion ;-)

**INSTALLED CAPACITIES** (presentation from December 2016):

- hydro: 64 MW
- natural gas CHPP (CET): 335 MW
- other (CERS-mix): 2,520 MW 

![image](https://user-images.githubusercontent.com/25743609/34084355-fe2c6380-e37e-11e7-81b3-312b05c3b659.png)

There seem to be some industrial power plants with about 100 MW, and some renewables as PV and wind, but they may be neglected for now, as their generation is unknown anyways.

**CROSS-BORDER FLOWS**
Interconnectors to Ukraine and Romania are also part of the scheme ("Fluxurile MD-UA" and "Fluxurile MD-RO"), where positive values are imports and negative values are exports.

**MISC**
Moldova was previously mentioned in #575 in July, where it says, entso-e were working on implementing data from Moldova in near future. So far, there are no data on entso-e yet. 
So this source should work fine as well, as it is provided by the national TSO.

Greetings, Alex

**Comment by systemcatch** [comment]
@alixunderplatz Nice find!  Do you fancy having a go at writing a parser?

**Comment by alixunderplatz** [comment]
@systemcatch Thanks! 

I'd really love to! I even think it might be pretty simple in this case. 
**But**, unfortunately, I focused on learning "_R_" (where I know how to webscrape) rather than "_Python_", so I have no idea how I'll get this to work properly.
From time to time, I look at the parsers folder and the code for different countries, but it remains way too cryptic to me. 😄 I am really sorry!!! 😭

Is there anything I can do like write down where exactly to find the relevant data in the website code?
something like 
- "all power plant data have class="tm2" and "tm3" or
- "the id="tmva378" refers to CET-2 Chişinău and therefore generation from natural gas
![image](https://user-images.githubusercontent.com/25743609/34115433-ebe359f8-e415-11e7-8d3e-d8adbe48a745.png)

Will that help another person writing a parser?

**Comment by alixunderplatz** [comment]
@systemcatch allright, I'll give it a try!

**Comment by alixunderplatz** [comment]
@systemcatch 
I hope it's that simple - I assigned the power plant id from the screenshot above to the types. 
I copied the style of the BG parser list.

```
TYPE_MAPPING = {                        # MOLDOVA
    u'tmva476': 'hydro',                # NHE Costeşti (run-of-river)
    u'tmva112': 'hydro',      		# NHE Dubăsari (run-of-river)
    u'tmva367': 'gas',      		# CET Nord (CHPP)
    u'tmva42': 'gas',             	# CET-1 Chişinău (CHPP)
    u'tmva378': 'gas',             	# CET-2 Chişinău (CHPP)
    u'tmva1024': 'other',             	# CERS Moldovenească (fuel mix coal, gas, oil)
    u'tmva1040': 'consumption',         # Consum
}
```

Further useful ids are:
'tmva1030': total generation
'tmva1052': cross-border flows with UA
'tmva1063': cross-border flows with RO
'time'        : time but without a date

**Comment by systemcatch** [comment]
@alixunderplatz  That's good but I don't think we will need the id's, just the plant name (e.g. CET Nord) mapped to type will be enough.

Inspecting the html there doesn't appear to be any values present for each plant.  Watching the developer console there's a request to http://www.moldelectrica.md/utils/load4.php every minute which returns a sequence of numbers that is probably inserted into the page by a script.

Luckily the numbers are in a consistent order so we should be in business.

**Comment by systemcatch** [comment]
@alixunderplatz do you have a link to the presentation of installed capacities?

**Comment by alixunderplatz** [comment]
@systemcatch : here's the link to the presentation:
http://en.fas.gov.ru/upload/other/National%20Agency%20for%20Energy%20Regulation%20(G.%20Pyrzy).pdf
