### ISSUE TITLE
Add PJM B "Pennsylvania"

### ISSUE THREAD

**Issue by HansHyde** [tmrowco/electricitymap#927]
**Parser** - new
**Name** - PJM B
**Geometry** - temp US-PA (Pennsylvania) from web/locales/en.json
**Exchanges (3)**
1. NYISO 1 - real time data from NYISO csv
2. PJM A - real time data TBD
3. PJM "C" rest of RTO - real time data TBD
**Gen Mix** - for NYISO 1 balancing, all imports to NY are contracted (given) as "Gas"

**Comment by corradio** [comment]
Is there real time generation mix for PA? I can't seem to locate from what you wrote.

**Comment by HansHyde** [comment]
it is within here... http://mis.nyiso.com/public/csv/ExternalLimitsFlows/currentExternalLimitsFlows.csv

**Comment by corradio** [comment]
Unfortunately that is only exchange data (we need real-time generation data in order to add a new zone)
Let's keep using #898 to investigate whether or not we can split NYISO.
