### ISSUE TITLE
add NYISO 2 "downstate New York"

### ISSUE THREAD

**Issue by HansHyde** [tmrowco/electricitymap#929]
**Parser** - new
**Name** - NYISO 2
**Geometry** - temp US-CT (Connecticut) from web/locales/en.json
**Exchanges (4)**
1. NYISO 1 - real time data available (backend calculations needed*)
2. NYSIO 3 - real time data from (backend calculations needed*)
3. NEISO - real time data from NYISO csv
4. PJM A - real time data from NYISO csv
**Gen Mix** - for NYISO 1, NYISO 2 & NYISO 3 balancing, all imports to NY from "PJM" are contracted (given) as "Gas"

**Comment by corradio** [comment]
Let's use #898 to investigate whether or not we have the data required to split NYISO.
