### ISSUE TITLE
Lakes are not shown (Ontario)

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#933]
Would be nice to add lakes in Ontario, probably by using proper natural earth geometries.

**Comment by jarek** [comment]
This is because topogen.sh uses ne_10m_admin_1_states_provinces.zip. Switching to ne_10m_admin_1_states_provinces_lakes.zip should do it.

**Comment by corradio** [comment]
you are right. I plan to work on the whole mapping thing pretty soon. Will fix this as I go along.

**Comment by corradio** [comment]
The thing is that the size of the file is x3 compared to the one without lakes.. Will see how well this compresses.

**Comment by jarek** [comment]
@corradio you should also change https://github.com/tmrowco/electricitymap/blob/master/web/topogen.sh#L8 or this will happen again next time world.json is regenerated

**Comment by corradio** [comment]
done :) Thanks!

**Comment by HansHyde** [comment]
In the countrytopos.js there are the 2 functions...

- function getStateByFips(countryId, fips)
- function getStatesByAdm1(adm1_codes)

Are they included to potentially drill down further into the geometry sources - in this example Country --> State --> County (for the US)?

On the plus side, this could more accurately build geometries like PJM or more accurately show water lines (for the Great Lakes), and potentially get to some utility/city levels; ie regularly requested Nevada Energy (Las Vegas) or Arizona Public Service (Phoenix), but...

On the negative side, the addition of thousands of more source geometries & their code lines - and however that impacts the "weight" of the app & compiling/fetch speeds.

Would it be possible to add "select" 3rd Tier geometries (or is our only option - include all 3rd Tier or none)?

And... well, I just saw that you have added the Great Lakes... well done!
