### ISSUE TITLE
Add option to merge imports into each fuel category on chart "Origin of electricity in the last 24 hours"

### ISSUE THREAD

**Issue by brunolajoie** [tmrowco/electricitymap#937]
- We have the data in the state to do it
- Idea would be to allow the user to toggle between "imports on top" vs. "imports merged"
- The exact same graph type can be used

Option 1: use the same front end that we have above:
![image](https://user-images.githubusercontent.com/22095643/34230852-f4100d40-e5d9-11e7-8bab-428682e763b8.png)

Option 2: add a more graphical ON/OFF "toogle" with legend "Merge imports into fuels types"

**Comment by corradio** [comment]
@brunolajoie is this still relevant? Else we should probably close (we have a looot of issues)

**Comment by brunolajoie** [comment]
Yes, it's not a prio (unfortunately!)
