### ISSUE TITLE
Canary Islands intermittently showing zero production

### ISSUE THREAD

**Issue by jarek** [tmrowco/electricitymap#938]
This has been going on for a few days, since 16 Dec at least.

Shouldn't the backend just reject empty results and average the values in between? Or is it because the parser returns 0 rather than None?

Also of note: the parser returns half-values sometimes, see values highlighted in green. That's likely incorrect.

![image](https://user-images.githubusercontent.com/47415/34265819-67f63034-e677-11e7-8c1e-4e25f0e0301a.png)

![image](https://user-images.githubusercontent.com/47415/34265598-a04da526-e676-11e7-835c-8c5df2a8c5bb.png)

**Comment by corradio** [comment]
Indeed this seems to be a bug in the backend. Will investigate.

**Comment by blackleg** [comment]
I think that I found the error. 
Now the last data of the response that is used in the parser only contain the consumption data.
I started to update the [scraper](https://github.com/blackleg/reescraper) to allow get all data for the day and try to fix it.
