### ISSUE TITLE
Part of Bosnia and Herzegovina is missing

### ISSUE THREAD

**Issue by systemcatch** [tmrowco/electricitymap#951]
There's been a few disappearing states with the natural earth update.  But part of Bosnia is missing and when I check the natural earth country shapes a big chunk is bordered off and unlabeled.  Looks like a mistake.
 
![missing_bosnia](https://user-images.githubusercontent.com/30196510/34365568-ad550c2a-ea89-11e7-8957-8bc50666f76a.png)

**Comment by corradio** [comment]
I've tried to fix this but it seems that the latest version of NE has an incomplete "Srpska" region.
I don't know if this is because of our processing or because it has disappeared from the NE source.

**Comment by systemcatch** [comment]
I'm sure it's a mistake in the NE source.  I've opened an [issue](https://github.com/nvkelso/natural-earth-vector/issues/239) on their Github repo.

**Comment by systemcatch** [comment]
As a temporary fix we could just build the zone from the states file which is still correct.

**Comment by corradio** [comment]
Are you sure the state file is still correct? I've tried that and it didn't
work :/

**Comment by systemcatch** [comment]
Think I've managed to get it to build properly.  I'll submit a PR.
