### ISSUE TITLE
Wrong Swedish spelling: “potensial”

### ISSUE THREAD

**Issue by kahlin** [tmrowco/electricitymap#967]
The Swedish word is spelled “potential”, not “potensial.”

Sorry for the nitpick. =)

**Comment by corradio** [comment]
@kahlin where do you see it spelled potensial?
I don't see it here:
https://github.com/tmrowco/electricitymap/blob/master/web/locales/sv.json

**Comment by kahlin** [comment]
Hmm, that is weird. It was definitely spelled wrong when I checked the app a couple of hours ago but it’s now spelled correctly.

The fix was made in 88d8aa9 (21 days ago). 

Anyway, the spelling has been corrected and everything looks good. Sorry about the trouble.

Closing.

**Comment by magol** [comment]
@kahlin 
Caching kan ställa till det :-)
Som du insåg själv, så fixade jag mitt pinsamma misstag för en knapp månad sedan (se #861)
