### ISSUE TITLE
Search for sub regions not possible

### ISSUE THREAD

**Issue by magol** [tmrowco/electricitymap#971]
**Steps to Reproduce**
1. Go to the Ranking panel
2. Search for "New York"

**Expected Result**
The search result should view "United States of America (New York)".

**Actual Result**
No result is viewed.

# Discussion

It should be possible to search for sub regions. 
To solve this, I suggest two solutions:
- View all regions that CONTAINS the search string
- Split the country and the region, and make it possible to search for both the county and the region. 

The second solution is the one I prefer. To solve that, I suggest to change the translation files in this way (and the same for other countries that have regions):
```JSON
"US": "United States of America",
"US-CA": "California",
"US-NEISO": "New England",
"US-NY": "New York"
```

It is nonetheless unnecessary to have the "United States of America" on each line for every state in the translation file. This can instead be automatically formatted in the user interface so it is presented as "United States of America (New York)". This also open for other features in the future (like grouping of sub regions)

**Comment by corradio** [comment]
I think it would make sense to make a more advanced search system.
A regexp match could do it. Instead of "begins with", we could do a regexp that matches the beginning of any word. That would already be a good improvement.

**Comment by jarek** [comment]
No need for regex IMO, the list of countries/regions is small enough that any substring match is going to be fine, I think. It's indexOf in JavaScript if I recall correctly.
