### ISSUE TITLE
Moldova MD / emission factor for gas

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap#973]
@brunolajoie

In #926, I mentioned that electricity production from natural gas in *Moldova* happens with an efficiency of ~22%, which leads to CO2-emissions of ~1000 g/kWh for the gas units. However, this efficiency was based on numbers from 2008, but I don't think that more efficient gas units were put into operation in the past decade in MD.

Here's the [source for the efficiency](https://www.google.de/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjhvbnshpLYAhWIEVAKHaIIACQQFgguMAA&url=http%3A%2F%2Fget-moldau.de%2Fdownload%2Fpolicypapers%2F2010%2FGET%2520Moldova_PP%252001%25202010_en.pdf&usg=AOvVaw37WEhiS1RHEn9lR52Ono--) (page -3-) 
![image](https://user-images.githubusercontent.com/25743609/34484931-345a12fe-efc8-11e7-8187-772e643b2e1c.png)

I used [this as source for the CO2 emissions](http://www.klimaneutral-handeln.de/php/kompens-berechnen.php#rechner): 

burning 1 kWh of natural gas leads to 220 g CO2 emissions.
So 220 g/kWh(thermal) / 22% = 1000 g/kWh(electrical).

If you think the data is precise, let's use a country specific factor for MD ;)

**Comment by HansHyde** [comment]
@alixunderplatz there is no such thing as "1 kWh of natural gas".

There are 52.16 kG of CO2 for every 1 million BTU of Methane combusted.  How the efficiency (heat rate) of the plant determines how many kWh of electricity produced from the combustion of a specific amount of natural gas releasing a given amount of CO2.  Everything else in the mass balance is lost as heat.

You can read a bit more here, but IPCC values are a very poor determiner of realtime CO2 emissions per kWH.  https://www.engineeringtoolbox.com/co2-emission-fuels-d_1085.html

**Comment by alixunderplatz** [comment]
@HansHyde 
My intention for opening this MD-related issue: I just wanted to point out, that for this rather overseeable country and its few generation units with a poor efficiency (info that I found by accident while searching for data for MD), we might as well change the factor here, like we did for Norwegian hydro or Estonian oil shale.


1 million BTU of pure methane = 293 kWh of methane in derived SI units.
So the converted emission factor from combusting 1 million BTU methane is 178 g(CO2)/kWh(CH4) according to your data. The site you linked says 180 g/kWh which is the same.
That is also fairly close to the 220 g/kWh and close to other info I could find (~200 g/kWh) for *natural* gas, which usually contains higher alkanes with more carbon atoms, too. So I don't get the point why there shouldn't be such thing as "1 kWh of natural gas".

**Comment by HansHyde** [comment]
@alixunderplatz 

Hi Alex, for simplicity's sake I will run 4000 MMBTU through 4 different "NG generators", and you can tell me if it is close.

4000 MMBTU over 1 hour
- GE 9A HA in its simple cycle mode will produce 480 MW/h
-  from its HRSG & Steam Turbine it will produce 230 MW/h more without additional MMBTU
- a conventional boiler with steam turbine would produce 366 MW/h, and would also require significant additional MMBTU to "ramp up" before it produced any MWHr.
- from a lower rated simple cycle gas turbine 420 MW/h

The fuel in was the same, so you could calculate the kgCO2 emitted, then compare against the g/kWh number if you like.

**Comment by HansHyde** [comment]
Ps your conversion above is wrong. I only know because today I used the same and energy magically appeared. When I asked others what I was doing wrong, one insisted the 1 MMBTU = 293KWh was correct.

It is not, because it forgets to take into account time.

A BTU = 1055 Joule. A Joule = a Watt-sec. Therefore, a BTU equals about 17.5 Watt-minutes.

https://en.m.wikipedia.org/wiki/British_thermal_unit

**Comment by alixunderplatz** [comment]
@HansHyde Hello Hans!
I totally get the point, that not every generating unit has the same efficiency, therefore different emissions appear. Some may produce more electricity from the primary energy provided by natural gas due to plant layout, load factor and operating mode (continuous or on-off-on-off), ambient temperature, cooling water temperature, gas composition and whatsoever.
By the way, what do you mean by "It is not, because it forgets to take into account time."? What time do you refer to? In terms of energy: 17.5 Watt minutes are still equal to 0.293 watt hours and 1055 watt seconds and 1 BTU.

However, in the case of **Moldova**, which this issue is all about, NG clearly provides base load:

![image](https://user-images.githubusercontent.com/25743609/34610444-69ee9a42-f221-11e7-8b6f-7bfdfdfd03cd.png)

**No ramp up during usual operation** of the gas CHPPs in the last days. The efficiency is **given as 22%.** Therefore, from the calculations above, I suggested 1000 g/kWh. This isn't equal to LCA emissions for these specific units, I'm aware of that. But for this specific country, it's the "more likely" value.

If this is of any relevance for a decision on that issue: Adding this emission factor would only influence MD itself, since currently there is no active connection with Romania and there are exlusively imports from Ukraine (for balancing). At the moment for example, emissions would increase from ~600 g/kWh to ~700 g/kWh.

I don't mind if this issue is closed without any changes to the emissions, I'll rather focus on finding more relevant stuff to cover the map :)

**Comment by HansHyde** [comment]
I have nothing to add in under 10 words.

**Comment by brunolajoie** [comment]
Thanks for the analysis @alixunderplatz. Let's keep that in mind for later on. I'd rather wait a bit to see if we can't find a more "standardized" approach to country-by-country GHG intensity factor refining.  See #738  If not, we'll come back to this issue and see what we can do.

**Comment by alixunderplatz** [comment]
This is not related to what I previously wrote about the smaller power plants, but suits the title of this issue:

I stumbled across some data regarding **the entire "unknown" part** of the generation for the first 9 months of 2017, which is supplied by the largest power station of MD with 2520 MW.

Actually, nearly 100% of its generation came from natural gas in these months of 2017 as well, so we could finally reassign this from "unknown" to "gas" :)

here is the mix:
gas / coal / oil
99.92 / 0 / 0.08 %

Note: the power station is capable of using oil, gas and coal as fuel, therefore we had put its capacity into the "other/unknown" category.

If we changed this, should we rather
- put the power station to "gas" instead of "unknown" or 
- assign 480 g/kWh to the "unknown" category and add the reason in the annotations/description?


[LINK TO SOURCE](http://moldgres.com/wp-content/uploads/2017/10/%D0%9F%D1%80%D0%BE%D0%B8%D0%B7%D0%B2%D0%BE%D0%B4%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D1%8B%D0%B5-%D0%BF%D0%BE%D0%BA%D0%B0%D0%B7%D0%B0%D1%82%D0%B5%D0%BB%D0%B8-%D0%B7%D0%B0-9-%D0%BC%D0%B5%D1%81%D1%8F%D1%86%D0%B5%D0%B2-2017-%D0%B3%D0%BE%D0%B4%D0%B0.pdf)

![image](https://user-images.githubusercontent.com/25743609/34675852-1ecc08da-f48b-11e7-9fdc-e11a79899ed8.png)

**Comment by corradio** [comment]
@alixunderplatz is there something that needs to be changed on the map based on your analysis? Else I think we can close the issue?

**Comment by alixunderplatz** [comment]
@corradio 

* the "unknown" category could be assigned the gas intensity of 480 g/kWh. This would keep the nice details of ramping of the large multi-fuel power plant which we map to unknown. Based on last year's figures, that power plant generated using a mix of 99.92% gas / 0.08% oil.

![image](https://user-images.githubusercontent.com/25743609/39618891-f9401542-4f85-11e8-86fb-a6227e5edd58.png)

* the carbon intensity for the CHP gas units providing the gas baseload stripe could be increased to 1000 g/kWh based on their efficiency of 22%. I calculated this on my own, see the first comment in this issue for details. But since these figures were old and the heat output is unknown, I'd leave it as it is.

But, all in all, I don't mind leaving Moldova as it is, because it is basically importing from UA all the time and it's carbon intensity has absolutely no influence on other zones. 

So I'll close.

**Comment by brunolajoie** [comment]
Thanks @alixunderplatz !
My guess is, If unknown is composed of 99.9% gas, it's a super quick win to assign it to "gas", and leave carbon intensity of gas as it is right now. First its usefull to understand where your electricity comes from, and second it's gonna be usefull later on if we refined carbon intensity factors per fuel that differs per country.

**Comment by alixunderplatz** [comment]
@brunolajoie I agree, so I'll change it in the mapping.

![image](https://user-images.githubusercontent.com/25743609/39620375-3d5a6502-4f8b-11e8-9349-cc85c738b011.png)
