### ISSUE TITLE
Mockserver server.py does not work in Python 3

### ISSUE THREAD

**Issue by systemcatch** [tmrowco/electricitymap#979]
```mockserver_1  | Traceback (most recent call last):
mockserver_1  |   File "../server.py", line 5, in <module>
mockserver_1  |     from SimpleHTTPServer import SimpleHTTPRequestHandler, BaseHTTPServer
mockserver_1  | ModuleNotFoundError: No module named 'SimpleHTTPServer'
```
Looks like some modules have been reorganized in Python 3.  Hopefully this is just a matter of updating the imports.

**Comment by corradio** [comment]
Have you tried to install simplehttpserver using pip? Maybe add the pip
install command in the docker file and rebuild the mockserver?

**Comment by systemcatch** [comment]
Running 2to3 made just one change to server.py.
```
-from SimpleHTTPServer import SimpleHTTPRequestHandler, BaseHTTPServer
+from http.server import SimpleHTTPRequestHandler, BaseHTTPServer
```
But I still get `ImportError: cannot import name 'BaseHTTPServer'` when running `python3 server.py`
Looks like 2to3 can't auto fix this.

**Comment by corradio** [comment]
According to this:
https://stackoverflow.com/questions/23264569/python-3-x-basehttpserver-or-http-server
apparently `BaseHTTPServer` is now `http.server`.
Maybe the correct import is
```python
from http.server import SimpleHTTPRequestHandler, HTTPServer
```

https://docs.python.org/3/library/http.server.html

Hopefully this can point you in the right direction.

**Comment by systemcatch** [comment]
Yeah I've been looking through those docs.  I've made the following changes so that it will run on the commandline.
```python
from http.server import SimpleHTTPRequestHandler, HTTPServer, test
```
```python
if __name__ == '__main__':
    test(CORSRequestHandler, HTTPServer)
```
```bash
chris@ThinkPad:~/electricitymap/mockserver$ python3 server.py 
Serving HTTP on 0.0.0.0 port 8000 ...
```
But no luck getting it to work on the map yet.

**Comment by corradio** [comment]
I think you need to do a `docker build` first in order to make sure to rebuild the docker image using python 3
