### ISSUE TITLE
Exchange arrows for 0 MW import/export are confusing

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap#980]
This doesn't have any influence on the data, but is there a way to make the exchange arrows disappear when export/import between countries is 0 MW? 
Is it because zero is considered a positive number, so the arrow is pointing in the positive/default direction?

![image](https://user-images.githubusercontent.com/25743609/34632254-aa53049e-f274-11e7-91f1-1ec7f1bdd474.png)

![image](https://user-images.githubusercontent.com/25743609/34632270-c36c9cf6-f274-11e7-8732-42fdecd705d2.png)

**Comment by corradio** [comment]
I think ideally the arrows should be there but there should be no animations?
What do others think?

**Comment by systemcatch** [comment]
I'd make them disappear because at a glance it still looks like there is an export/import going on unless you hover on the arrow for more info.

**Comment by corradio** [comment]
Actually we already hide them if they are 0. I suspect the flow to be close to 0, but not perfectly 0. Will be fixed.

**Comment by brunolajoie** [comment]
Yep, i'd vote in favor of hidding them when flow is 0 too
