### ISSUE TITLE
Windenergiepotenzial  Box + Solarenergiepotenzial Box no affect

### ISSUE THREAD

**Issue by strassburger** [tmrowco/electricitymap#986]
Windenergiepotenzial  Box + Solarenergiepotenzial Box no affect.
Clicking this Boxes no wind or solar shown in map.

Test- Envirement:
ubuntu14.04
firefox quantum 57.0.4

**Comment by jarek** [comment]
I can confirm.

Looks like requests to https://api.electricitymap.org/v3/gfs/solar?refTime=2018-01-08T06:00:00.000Z&targetTime=2018-01-08T12:00:00.000Z and https://api.electricitymap.org/v3/gfs/wind?refTime=2018-01-08T06:00:00.000Z&targetTime=2018-01-08T13:00:00.000Z fail - HTTP 404, response text is "Forecast was not found"

Possibly wind/solar forecast scrapers on API servers have broken. cc @corradio

**Comment by corradio** [comment]
noted. Will investigate with @brunolajoie

**Comment by corradio** [comment]
Have posted a fix. Should be up again soon.

**Comment by corradio** [comment]
Fixed
