### ISSUE TITLE
Make Singapore appear bigger

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap#993]
Of course, Singapore is a very tiny country with only 720 km² surface.
 
But I think it could be a little bigger on the map, since it is really hard to find below Malaysia on PC monitor and I very often fail to select it on my Galaxy S5 phone.

Is there a way to resize it on the map and extend it ovally to the east and a bit to the south?

For comparison: Faroe Islands have twice the surface, but appear waaaaay bigger (due to projection and their location in the far north of earth). 
See image for comparison (same zoom stage): left Singapore / right Faroe Islands:

![image](https://user-images.githubusercontent.com/25743609/34777479-bf4c99d8-f61a-11e7-8914-f464268f8e02.png)

**Comment by brunolajoie** [comment]
You'll be able to zoon much closer in the new mapbox redesign #958  that we are close to publish 
! 🔍  

[image](https://user-images.githubusercontent.com/22095643/34787959-62780980-f639-11e7-8f70-7af598711169.png)

**Comment by alixunderplatz** [comment]
@brunolajoie allright, thank you for the info! This will make selecting easier.

I think expanding it by a little would still be helpful to notice that it is generally on the map. 
Are we able to do that or do the countries' outlines depend on geometry we absolutely can't influence?

**Comment by corradio** [comment]
@alixunderplatz it's not something we'd want to do (also, it's complicated).
Is it better with the new version that is now in production?

**Comment by alixunderplatz** [comment]
@corradio yes, it's much better now, so I'll close this :)
